In [53]:
import pandas as pd
import numpy as np

In [ ]:
## 데뷔 기준 : 네이버 (why? 알빠노) 
((베스트 도전 : 현재 상황이 베스트 도전인 사람들임))

'김태경' :'남성' 데뷔 2019 / 정식웹툰
'정연' : '남성' 데뷔 2019 / 정식웹툰  
'자까' :'여성' 데뷔 2016,/ 정식웹툰   1993.05.12, ISFJ, 
'쌉초' :'여성' 데뷔 2024 /정식웹툰  
'감자' :'여성'  데뷔 2024  / 정식웹툰
'진돌', :'남성'  데뷔 2020 / 정식웹툰, 1989.01.06, 
'구나' :'여성???', 데뷔 2024 / 정식웹툰
'고추참치' :'여성' 데뷔 2023 / 정식웹툰 
'상금' :'여성' , 데뷔 2023 / 정식웹툰 
'잇선' :'남성',데뷔 2015 / 정식웹툰
'이담' :'여성', 데뷔 2021 / 정식웹툰
'박씨' : '남성', 데뷔 2024, / 정식웹툰 
'오성대' : '남성' 데뷔 2005 / 정식웹툰 , 	1982년 11월 18일 
'구아진': '여성', 데뷔 2008, / 정식웹툰
'스프링' : '여성', 데뷔 2020 / 정식웹툰
'모죠' :'여성', 데뷔  2019 / 정식웹툰
'지발', '여성' / 데뷔 2023 / 정식웹툰 
'최다킬' :'남성', 데뷔 2023 / 정식웹툰
'범배' :'여성' , 데뷔 2024 / 정식웹툰
'손하기' :'여성', 데뷔 2012 / 정식웹툰
'허새보' :'남성' , 데뷔 2023 / 베스트도전
'포스스튜디오' :'미정' 데뷔 2022 / 정식웹툰 --- 웹툰 레이블 회사라 성별 미정
'박태준' : '남성' 데뷔 2014 / 정식웹툰  1984년 9월 3일 (40세)
'모랑지' :'여성' 데뷔 2015/ 정식웹툰  1987년 3월 17일 (37세)
'혀노', :'남성' 데뷔 2012 / 정식웹툰  1991년 2월 18일 (33세)
'HO9' : '남성', 데뷔 2018 /  정식웹툰
'조용석' : '남성' 데뷔 2012   /  정식웹툰 	1984년 5월 5일(40세)
'이은재' :'남성' ,데뷔 2019 /  정식웹툰 	
'돌석' :'남성' ,데뷔 2024 /  정식웹툰 	
'라군':'남성', 데뷔 2019/  정식웹툰 
'채키':'남성', 데뷔 2024/  정식웹툰 
'임리나' :'여성', 데뷔 2020/  정식웹툰
'정종택' :'남성' 데뷔 2019 / 정식웹툰
'한가람' :'여성' 데뷔 2019 / 정식웹툰
'펀치킥' :'남성', 데뷔 2023 / 정식웹툰
'제나' :'여성', 데뷔 2007 / 정식웹툰
'태완':'남성', 데뷔 2021 / 정식웹툰
'박진환':'남성', 데뷔 2019 / 정식웹툰 , 
'부겸':'남성', 데뷔 2019 / 정식웹툰 , 
'배민기':'남성', 데뷔 2020 / 정식웹툰 ,  	 1981년 2월 2일 (43세)
'시바견':'남성',  데뷔 2021 / 정식웹툰
'박만사':'남성',데뷔 2019 / 정식웹툰
'남자의 이야기' :'남성',데뷔 2019 / 정식웹툰
'병장':'남성',데뷔 2018 / 정식웹툰
'히디' :'여성', 데뷔 2020 / 정식웹툰
'명랑' :'남성', 데뷔 2019 / 정식웹툰
'유누니' :'남성',  데뷔 2021 / 정식웹툰
'JP':'남성', 데뷔 2022 / 정식웹툰
'강견' :'남성', 데뷔 2021 / 정식웹툰
'운':'남성', 데뷔 2018   / 정식웹툰 
'윤성' :'남성', 데뷔 2018   / 정식웹툰 
'이난':'남성', 데뷔 2018   / 정식웹툰 
'하일권' :'남성' , 데뮈 2006 / 정식웹툰, 1982년 1월 10일 (42세)
'이대한' :'남성' , 데뮈 2024
'황양' :'남성' , 데뮈 2019 / 정식웹툰, 
'득7이':'남성', 데뮈 2024 / 베스트도전
'이솔' :'여성',  데뮈 2020 /정식웹툰, 
'꼬모소이' :'여성',데뮈 2017 /정식웹툰, 
'켄타':'여성', 데뮈 2017 /정식웹툰, 
'김대영' :'남성', 데뮈 2012 /정식웹툰, 
'이동건':'남성', 데뮈 2011 /정식웹툰, 
'승우':'남성', 데뮈 2020 /정식웹툰, 
'수박양' : '여성', 데뮈 2020 /정식웹툰, 
'스튜디오MW' :'미정', 데뮈 2023/정식웹툰, 
'지페리':'남성'  데뮈 2022 /정식웹툰, 
'임형' : '여성' 데뮈 2023 /정식웹툰,

In [11]:
import pandas as pd
import numpy as np

# 데이터 초기화
data0 = [
    ['김태경', '남성', 2019, '정식웹툰'], ['정연', '남성', 2019, '정식웹툰'],['자까', '여성', 2016, '정식웹툰'], ['쌉초', '여성', 2024, '정식웹툰'], ['감자', '여성', 2024, '정식웹툰'], ['진돌', '남성', 2020, '정식웹툰'], ['구나', '여성???', 2024, '정식웹툰'], ['고추참치', '여성', 2023, '정식웹툰'], ['상금', '여성', 2023, '정식웹툰'], ['잇선', '남성', 2015, '정식웹툰'], ['이담', '여성', 2021, '정식웹툰'],['박씨', '남성', 2024, '정식웹툰'], ['오성대', '남성', 2005, '정식웹툰'], ['구아진', '여성', 2008, '정식웹툰'],
    ['스프링', '여성', 2020, '정식웹툰'], ['모죠', '여성', 2019, '정식웹툰'], ['지발', '여성', 2023, '정식웹툰'], ['최다킬', '남성', 2023, '정식웹툰'], ['범배', '여성', 2024, '정식웹툰'],['손하기', '여성', 2012, '정식웹툰'], ['허새보', '남성', 2023, '베스트도전'], ['포스스튜디오', '미정', 2022, '정식웹툰'],  ['박태준', '남성', 2014, '정식웹툰'], ['모랑지', '여성', 2015, '정식웹툰'], ['혀노', '남성', 2012, '정식웹툰'], ['HO9', '남성', 2018, '정식웹툰'],
    ['조용석', '남성', 2012, '정식웹툰'], ['이은재', '남성', 2019, '정식웹툰'], ['돌석', '남성', 2024, '정식웹툰'], ['라군', '남성', 2019, '정식웹툰'],['채키', '남성', 2024, '정식웹툰'], ['임리나', '여성', 2020, '정식웹툰'], ['정종택', '남성', 2019, '정식웹툰'], ['한가람', '여성', 2019, '정식웹툰'], ['펀치킥', '남성', 2023, '정식웹툰'],  ['제나', '여성', 2007, '정식웹툰'], ['태완', '남성', 2021, '정식웹툰'], ['박진환', '남성', 2019, '정식웹툰'], ['부겸', '남성', 2019, '정식웹툰'], ['배민기', '남성', 2020, '정식웹툰'],['시바견', '남성', 2021, '정식웹툰'], ['박만사', '남성', 2019, '정식웹툰'], ['남자의 이야기', '남성', 2019, '정식웹툰'], ['병장', '남성', 2018, '정식웹툰'], ['히디', '여성', 2020, '정식웹툰'], ['명랑', '남성', 2019, '정식웹툰'], ['유누니', '남성', 2021, '정식웹툰'], ['JP', '남성', 2022, '정식웹툰'], ['강견', '남성', 2021, '정식웹툰'], ['운', '남성', 2018, '정식웹툰'],['윤성', '남성', 2018, '정식웹툰'], ['이난', '남성', 2018, '정식웹툰'], ['하일권', '남성', 2006, '정식웹툰'], ['이대한', '남성', 2024, '정식웹툰'], ['황양', '남성', 2019, '정식웹툰'],
    ['득7이', '남성', 2024, '베스트도전'], ['이솔', '여성', 2020, '정식웹툰'], ['꼬모소이', '여성', 2017, '정식웹툰'], ['켄타', '여성', 2017, '정식웹툰'],['김대영', '남성', 2012, '정식웹툰'], ['이동건', '남성', 2011, '정식웹툰'], ['승우', '남성', 2020, '정식웹툰'], ['수박양', '여성', 2020, '정식웹툰'], ['스튜디오MW', '미정', 2023, '정식웹툰'], ['지페리', '남성', 2022, '정식웹툰'],['임형', '여성', 2023, '정식웹툰']
]

# DataFrame 생성
df00 = pd.DataFrame(data0, columns=['작가명', '성별', '데뷔년도', '웹툰단계'])
df00

       작가명  성별  데뷔년도  웹툰단계
0      김태경  남성  2019  정식웹툰
1       정연  남성  2019  정식웹툰
2       자까  여성  2016  정식웹툰
3       쌉초  여성  2024  정식웹툰
4       감자  여성  2024  정식웹툰
..     ...  ..   ...   ...
61      승우  남성  2020  정식웹툰
62     수박양  여성  2020  정식웹툰
63  스튜디오MW  미정  2023  정식웹툰
64     지페리  남성  2022  정식웹툰
65      임형  여성  2023  정식웹툰

[66 rows x 4 columns]

In [17]:
# df= pd.merge(df, df00, left_on ='작가명', right_on ='작가명')

In [5]:
## 컬럼 추가 : 해당 작품이 언제 업로드 되는지? (목요웹툰 등)
 
df = pd.read_csv('웹툰분석_네이버웹툰_작가홈_데이터.csv',index_col=0)
df['만화명'].unique()

array(['1등급 싸움과외', '캐슬2:만인지상', '육아일기', '쌉초의 난', '유부 감자', '진돌히디만화',
       '어린이집 다니는구나', '개집사', '시바, 만만치 않다', '흔한햄', '똑 닮은 딸', '내 여자친구는',
       '기기괴괴2', '미래의 골동품 가게', '수상한 다이어트 클럽', '마루는 강쥐', '무직백수 계백순', '성검전설',
       '기자매', '에밀리의 저택', '성북구 비둘기 이헌서', '마도전생기', '외모지상주의', '소녀의 세계',
       '별이삼샵', '별난식당', '윈드브레이커', '펜홀더', '낫오버', '탑코너', '골레이로', '킬러 배드로',
       '김부장 & 촉법소년', '참교육', '백XX', '엘릭시드', '퀘스트지상주의', '절대회귀', '환생천마',
       '무사만리행', '위닝샷!', '서울 자가에 대기업 다니는 김 부장 이야기', '이발소 밑 게임가게', '귀촌리',
       '우리들의 사정', '연우의 순정', '추억이 찾아오는 가게', '우리는 후라이족', '북경신보', '조조코믹스',
       '시월드가 내게 집착한다', '아홉수 우리들', '신입사원 김철수', '99강화나무몽둥이', '나 혼자 탑에서 농사'],
      dtype=object)

In [6]:
import pandas as pd

# 웹툰 데이터 및 연재 요일
data = [
    ('1등급 싸움과외', '수'),
    ('캐슬2:만인지상', '수'),
    ('육아일기', '목, 일'),
    ('쌉초의 난', '수, 토'),
    ('유부 감자', '화, 금'),
    ('진돌히디만화', '수'),
    ('어린이집 다니는구나', '월, 수'),
    ('개집사', '화, 금'),
    ('시바, 만만치 않다', '수'),
    ('흔한햄', '목, 토'),
    ('똑 닮은 딸', '월'),
    ('내 여자친구는', '수'),
    ('기기괴괴2', '일'),
    ('미래의 골동품 가게', '수'),
    ('수상한 다이어트 클럽', '월'),
    ('마루는 강쥐', '화'),
    ('무직백수 계백순', '수, 일'),
    ('성검전설', '화'),
    ('기자매', '목'),
    ('에밀리의 저택', '목'),
    ('성북구 비둘기 이헌서', '금'),
    ('마도전생기', '토'),
    ('외모지상주의', '금'),
    ('소녀의 세계', '완결'),
    ('별이삼샵', '일'),
    ('별난식당', '월'),
    ('윈드브레이커', '월'),
    ('펜홀더', '금'),
    ('낫오버', '수'),
    ('탑코너', '토'),
    ('골레이로', '목'),
    ('킬러 배드로', '토'),
    ('김부장 & 촉법소년', '목'),
    ('참교육', '월'),
    ('백XX', '수'),
    ('엘릭시드', '수'),
    ('퀘스트지상주의', '월'),
    ('절대회귀', '화'),
    ('환생천마', '월'),
    ('무사만리행', '목'),
    ('위닝샷!', '일'),
    ('서울 자가에 대기업 다니는 김 부장 이야기', '화'),
    ('이발소 밑 게임가게', '일'),
    ('귀촌리', '월'),
    ('우리들의 사정', '수'),
    ('연우의 순정', '완결'),
    ('추억이 찾아오는 가게', '목'),
    ('우리는 후라이족', '금'),
    ('북경신보', '완결'),
    ('조조코믹스', '수, 토'),
    ('시월드가 내게 집착한다', '일'),
    ('아홉수 우리들', '토'),
    ('신입사원 김철수', '화'),
    ('99강화나무몽둥이', '토'),
    ('나 혼자 탑에서 농사', '금')
]

# 요일 매핑
days = ['월', '화', '수', '목', '금', '토', '일']

# 데이터를 DataFrame으로 변환 및 연재 요일에 따른 이진 값 할당
dfdfdf = pd.DataFrame(data, columns=['작품명', '연재 요일'])
for day in days:
    dfdfdf[day] = dfdfdf['연재 요일'].apply(lambda x: 1 if day in x else 0)

# 결과 확인
dfdfdf.drop(columns='연재 요일', inplace=True)  # 연재 요일 컬럼 제거
dfdfdf['연재여부'] =''
dfdfdf['연재여부'][dfdfdf['작품명'] == '연우의 순정'] = 0 # 완결된 상태
dfdfdf['연재여부'][dfdfdf['작품명'] == '소녀의 세계'] = 0
dfdfdf['연재여부'][dfdfdf['연재여부']!=0] =1

/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/1369918558.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdfdf['연재여부'][dfdfdf['작품명'] == '연우의 순정'] = 0 # 완결된 상태
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/1369918558.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdfdf['연재여부'][dfdfdf['작품명'] == '소녀의 세계'] = 0
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/1369918558.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdfdf['연재여부'][dfdfdf['연재여부']!=0] =1

In [7]:
dfdfdf.columns = ['만화명', '월', '화', '수', '목', '금', '토', '일', '연재여부']
df = pd.merge(  df,dfdfdf, left_on = '만화명', right_on ='만화명')

In [141]:
df

,작가명,작가 관심수,게시글 날짜,게시글 내용,이미지 여부,댓글수,반응수,best_reaction,good_reaction,warm_reaction,...,데뷔년도,웹툰단계,월,화,수,목,금,토,일,연재여부
0,김태경,10917.0,2024.10.08,"1등급 싸움과외 36화, 미리보기 39화 나왔습니다. 이번 주도 재밌게 봐주세요!",yes,5.0,43.0,9.0,32.0,1.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
1,김태경,10917.0,2024.10.02,"1등급 싸움과외 35화, 미리보기 38화 나왔습니다. 재밌게 봐주세요!",yes,5.0,44.0,7.0,35.0,1.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
2,김태경,10917.0,2024.09.26,0,0,0.0,0.0,0.0,0.0,0.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
3,김태경,10917.0,2024.09.24,"1등급 싸움과외 34화, 미리보기 37화 나왔습니다. 이번 주도 즐겁게 봐주세요!",yes,13.0,48.0,10.0,36.0,1.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
4,김태경,10917.0,2024.09.17,"1등급 싸움과외 33화, 미리보기 36화 나왔습니다. 도윤이 에피소드가 마무리되었네...",yes,14.0,49.0,6.0,41.0,1.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,임형,9309.0,2024.05.21,도자기로된 컵라면 용기를 사서 컵라면을 넣어 먹었습니다. 앞으로 제 밥그릇은 이겁니...,yes,27.0,149.0,57.0,62.0,3.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1
879,임형,9309.0,2024.05.18,마계일기- 번아웃,yes,21.0,171.0,37.0,89.0,5.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1
880,임형,9309.0,2024.05.17,야금야금 전에 올렸던 그림 올려보아요! 전 작가홈에 올렸을때 바탕화면으로 사용가능하...,yes,24.0,262.0,35.0,210.0,1.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1
881,임형,9309.0,2024.05.17,여러분 안녕하세요! 기존에 작가홈이 연결된 아이디를 변경하면서 작가홈이 싹 밀렸네요...,yes,7.0,172.0,23.0,136.0,2.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1
882,임형,9309.0,2024.05.17,0,0,0.0,0.0,0.0,0.0,0.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1

In [38]:
# df.to_csv('웹툰분석_네이버웹툰_작가홈_데이터.csv')

In [35]:
import pandas as pd
import numpy as np
 
df = pd.read_csv('웹툰분석_네이버웹툰_작가홈_데이터.csv',index_col=0)

In [9]:
df.columns

Index(['작가명', '작가 관심수', '게시글 날짜', '게시글 내용', '이미지 여부', '댓글수', '반응수',
       'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction',
       'expect_reaction', 'sad_reaction', '작가유형', '장르', '만화명', '성별', '데뷔년도',
       '웹툰단계', '월', '화', '수', '목', '금', '토', '일', '연재여부'],
      dtype='object')

In [40]:
df['작가유형'].value_counts()

작가유형
글&그림    475
글       228
그림      180
Name: count, dtype: int64

In [60]:
df['이미지 여부'].value_counts()

이미지 여부
yes    701
0      124
no      58
Name: count, dtype: int64

In [61]:
df[['작가 관심수',   '댓글수', '반응수', 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction',
       'expect_reaction', 'sad_reaction']].corr()

,작가 관심수,댓글수,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
작가 관심수,1.000000,0.403727,0.509348,0.441258,0.441974,0.241788,0.259766,0.370963,0.259254
댓글수,0.403727,1.000000,0.633375,0.622544,0.601178,0.126250,0.477122,0.624783,0.412186
반응수,0.509348,0.633375,1.000000,0.896619,0.974182,0.506305,0.632571,0.874243,0.378493
best_reaction,0.441258,0.622544,0.896619,1.000000,0.806150,0.524113,0.703208,0.795112,0.298431
good_reaction,0.441974,0.601178,0.974182,0.806150,1.000000,0.440393,0.534771,0.849353,0.246237
warm_reaction,0.241788,0.126250,0.506305,0.524113,0.440393,1.000000,0.391482,0.207615,0.128148
surp_reaction,0.259766,0.477122,0.632571,0.703208,0.534771,0.391482,1.000000,0.614636,0.296274
expect_reaction,0.370963,0.624783,0.874243,0.795112,0.849353,0.207615,0.614636,1.000000,0.278694
sad_reaction,0.259254,0.412186,0.378493,0.298431,0.246237,0.128148,0.296274,0.278694,1.000000

### 추가 수집 & 컬럼 추가 (수기로 모두 완료!)
#### 컬럼 추가 
- 작가에 관한 컬럼 추가 (성별,나이, 입단(?) 일 등등) -- 이건 완료 (성별, 데뷔, 연재요일, '웹툰단계(정식이냐 or 베스트도전이냐) )

#### 태깅
- 게시글 내용 태깅(???)  - 컬럼 하나 만들기

- 이미지 태깅 (어떤 이미지인지) < 작품 그림 (캐릭터 등) / 작가 일상 사진 / 기타 (휴재공지, 이벤트 등 )> -- 딱 이 둘로만 나누자. 
- 중간중간에 관심작가 수 upup태깅,

In [ ]:
'''

df[df['작가명'] =='김태경'] 
2024.10.08 / 작품 그림 (여성 캐릭터)
2024.10.02 /  작품 그림 (여성 캐릭터)
2024.09.26 / 10000 명 돌파
2024.09.24 /  작품 그림 (여성 캐릭터)
2024.09.17 /  작품 그림 (남성 캐릭터)
2024.09.10 /  작품 그림 (여성 캐릭터)
2024.09.03 /  작품 그림 (여성 캐릭터)
2024.08.27/  작품 그림 (캐릭터들)
2024.08.20/  작품 그림 (동물 캐릭터)
2024.08.13 /  작품 그림 (캐릭터들)
2024.08.06 /  작품 그림 (캐릭터들)
2024.08.06 / 5000 명 돌파
2024.07.30 / 작품 그림 (여성 캐릭터)
2024.07.24/ 작품 그림 (여성 캐릭터)
2024.06.18 / 작품 그림 (캐릭터들)
2024.04.23 / 작품 그림 (여성 캐릭터)
2024.04.10 / 작품 그림 (여성 캐릭터)
2024.03.31 / 작품 그림 (여성 캐릭터)
2024.03.26 / 작품 그림 (여성 캐릭터)
2024.03.19 / 작품 그림 (여성 캐릭터)
2024.03.12 / 작품 그림 (여성 캐릭터)
2024.02.27 / 작품 그림 (여성 캐릭터)
2024.02.20 / 작품 그림 (여성 캐릭터)
2024.02.13 / 작품 그림 (여성 캐릭터)

len(df[df['작가명'] =='정연'] )
2024.10.22 / 작품 그림 (남성 캐릭터)
2024.10.08 / 작품 캐릭터 설명(세력 및 관계구도) 이미지
2024.07.09 /20000 명 돌파
2024.07.08 / 누적 리액션 10000개 달성
2024.04.17/ 작품 캐릭터 설명(세력 및 관계구도) 이미지
2024.01.16 / 작품 그림 (남성 캐릭터) / 이벤트 발표
2024.01.16 / 작품 그림 (캐릭터들) / 이벤트 발표
2023.12.19 / 작품 그림 (캐릭터들) / 이벤트 발표

'''


df[df['작가명'] =='쌉초']  ## 얘는 몇명 돌파! 이런거 작가가 게시글 지웠나부당 ㅜㅜ

In [194]:
'작가명' : '김태경'
2024.10.08 / 작품 그림 
2024.10.02 /  작품 그림 
2024.09.26 / 10000 
2024.09.24 /  작품 그림  
2024.09.17 /  작품 그림  
2024.09.10 /  작품 그림 
2024.09.03 /  작품 그림 
2024.08.27/  작품 그림 
2024.08.20/  작품 그림 
2024.08.13 /  작품 그림 
2024.08.06 /  작품 그림 
2024.08.06 / 5000 
2024.07.30 / 작품 그림 
2024.07.24/ 작품 그림 
2024.06.18 / 작품 그림  
2024.04.23 / 작품 그림  
2024.04.10 / 작품 그림  
2024.03.31 / 작품 그림 
2024.03.26 / 작품 그림  
2024.03.19 / 작품 그림 
2024.03.12 / 작품 그림 
2024.02.27 / 작품 그림  
2024.02.20 / 작품 그림 
2024.02.13 / 작품 그림 
 
'작가명' : '정연'
2024.10.22 / 작품 그림 
2024.10.08 / 작품 그림 
2024.07.09 /20000  
2024.04.17/ 작품 그림 
2024.01.16 / 작품 그림 
2024.01.16 /작품 그림 
2023.12.19 /작품 그림 

'작가명' : '자까' 
2024.09.19 / 70000 
2024.08.26 / 작품 그림 
2024.08.19 / 일상 사진
2024.08.07 / 60000  
2024.07.13 / 작품 그림 
2024.06.08 / 50000 
2024.05.04 / 작품 그림 
2023.12.31 / 작품 그림 
2023.11.22 / 기타 
2023.11.07 / 작품 그림 
2023.10.11 / 일상 사진



############################
'작가명' : '쌉초' ## 얘는 몇명 돌파! 이런거 작가가 게시글 지웠나부당 ㅜㅜ
2024.09.13 / 작품 그림 
2024.10.18 / 작품 그림 
2024.10.13 / 작품 그림 
2024.09.28 / 작품 그림 
2024.09.28 / 작품 그림 
2024.09.18  / 작품 그림 
2024.09.14 / 작품 그림  
2024.09.12 / 일상 사진
2024.09.01 / 일상 사진
2024.08.30 / 일상 사진
2024.08.24 / 작품 그림  
2024.08.24 / 작품 그림  
2024.08.22 / 작품 그림  
2024.08.21 / 작품 그림 
2024.08.20 / 작품 그림 
2024.08.14 / 일상 사진
2024.08.02 / 작품 그림 
2024.07.23 / 작품 그림 
2024.07.18 / 작품 그림 
2024.07.12 / 작품 그림 
2024.07.03 / 작품 그림 
2024.07.03 / 일상 사진
2024.06.26 / 작품 그림 
2024.06.25 / 일상 사진
2024.06.25 / 기타
2024.06.21 / 작품 그림 
2024.05.25 / 일상 사진
2024.05.22 / 작품 그림 
2024.05.05 / 작품 그림 
2024.04.23 / 작품 그림
2024.04.23 / 작품 그림
2024.04.16 / 일상 사진
2024.04.11 / 작품 그림
2024.04.09 / 일상 사진
2024.03.31 / 기타
2024.03.29 / 작품 그림
2024.03.27 / 일상 사진
2024.03.26 / 일상 사진 
2024.03.14 / 작품 그림
2024.02.14 / 작품 그림
2024.02.09 / 작품 그림
2024.01.06 / 작품 그림
2023.12.24 / 작품 그림
 2023.10.24/ 작품 그림
 2023.10.22/ 작품 그림




'작가명' : '감자'
2024.09.03 / 기타
2024.08.19 / 작품 그림
2024.08.12 / 작품 그림
2024.07.20 / 일상 사진
2024.07.19 / 5000 
2024.06.21 / 기타
2024.04.14 / 일상 사진
2024.04.10 / 일상 사진
2024.04.01 / 작품 그림
2024.03.28 / 작품 그림
2024.03.06 / 작품 그림
2024.03.05 / 작품 그림
2024.03.04 /  작품 그림

'작가명' : '진돌'
2024.09.28 / 20000 
2024.09.24 / 일상 사진
2024.08.27 / 기타 
2024.07.30 / 기타 
2024.06.12 /  일상 사진
2024.05.22 /  일상 사진
2024.05.08 /  일상 사진
2024.04.17/  일상 사진
2024.04.10/  일상 사진
2024.04.08/  일상 사진
2024.04.01 / 기타
2024.03.28/ 일상 사진
2024.03.27 / 일상 사진
2024.03.20  / 일상 사진
2024.02.29 / 작품 그림
2024.02.27 / 일상 사진
2024.02.16 / 일상 사진
2024.01.29 / 작품 그림
2023.11.08 / 일상 사진
2023.10.02 / 일상 사진
2023.10.02/ 일상 사진
2023.09.29 / 일상 사진
2023.09.21/ 일상 사진
2023.09.15/ 일상 사진
2023.09.14/ 일상 사진
2023.09.14/ 일상 사진


'작가명' : '히디'
2024.10.23 / 작품 그림
2024.09.24 / 일상 사진
2024.09.20 / 일상 사진
2024.09.18 / 일상 사진
2024.09.13 / 일상 사진
2024.09.11 / 일상 사진
2024.06.12/ 10000 
2024.06.12 / 일상 사진
2024.05.21 / 일상 사진
2024.05.08 / 일상 사진
2024.04.23 / 일상 사진
2024.04.10 / 일상 사진
2024.04.01 / 작품 그림
2024.03.26  / 일상 사진
2024.03.20 / 작품 그림
2024.03.20/ 작품 그림
 

'작가명' :  '구나'
2024.09.23 / 기타
2024.08.20 / 기타
2024.08.18 / 일상 사진
2024.08.15 / 작품 그림 
2024.08.14 / 일상 사진
2024.08.11 / 10000 
2024.08.03 / 작품 그림
2024.06.23 / 작품 그림
2024.05.26 / 작품 그림
2024.05.08 / 작품 그림
2024.05.05 / 일상 사진
2024.04.29 / 일상 사진
2024.03.31 / 기타
2024.03.27 / 일상 사진
2024.03.01 / 작품 그림
2024.02.27 / 일상 사진
2024.02.14 / 기타
2024.02.06 / 일상 사진
2024.01.30 / 작품 그림
2023.12.31/ 작품 그림
 2023.12.25/ 일상 사진
 2023.11.27 /작품 그림
 2023.11.20/ 일상 사진
 2023.11.14/ 일상 사진
 2023.11.05 / 일상 사진
 2023.10.23 / 일상 사진


##########################################
##########################################
'작가명' :  '박씨'
2024.07.26 / 1000 
2024.06.12 / 기타 
2024.05.29 / 작품 그림
2024.05.14 / 작품 그림
2024.05.07 / 작품 그림

'작가명' : '오성대' 
2024.09.29 / 작품 그림 
2024.09.16 / 작품 그림 
2024.08.24 / 작품 그림
2024.08.24 / 작품 그림
2024.08.20 / 5000 
2024.05.10 / 작품 그림 
2024.04.21 / 작품 그림 
2024.04.09/ 일상 사진 
2024.03.31 / 작품 그림 
2024.03.09 / 작품 그림 
2024.02.16/ 작품 그림 
2023.10.04 / 일상 사진 
2023.09.27 / 일상 사진 

'작가명' : '구아진'  
2024.10.22 / 작품 그림
2024.09.26 / 작품 그림
2024.09.07 / 일상 사진 
2024.08.28 / 작품 그림
2024.08.08 / 5000 
2024.08.05 / 작품 그림 
2024.06.06 / 기타 
2024.04.16 / 작품 그림 
2024.03.19 / 작품 그림 
2024.02.29 / 기타 
2024.02.09 / 기타 
2024.02.08 / 작품 그림

'작가명' : '스프링'  
2024.06.25 / 1000 
2024.03.31 / 일상 사진 

'작가명' :'모죠'  
2024.09.17 / 작품 그림
2024.08.19 / 70000 
2024.08.13 / 기타 
2024.04.23 / 60000 
2024.04.22 / 기타 
2024.02.14 / 기타 
2024.02.08 / 작품 그림 

'작가명' :  '지발' 
 2024.09.26 / 기타 
 2024.09.26 / 일상 사진
 2024.09.07 / 일상 사진
 2024.08.22 / 작품 그림 
 2024.07.23 / 작품 그림 
 2024.07.18 / 작품 그림
 2024.07.15 / 작품 그림
 2024.07.05 / 작품 그림  
2024.07.04 / 작품 그림 
2024.07.04 / 작품 그림 
2024.07.03 / 작품 그림 
2024.06.20 / 작품 그림
2024.06.20/ 작품 그림
2024.06.19/ 작품 그림
2024.06.19/ 작품 그림 
2024.06.02 / 작품 그림
2024.05.22 / 작품 그림 
2024.05.07 / 기타 
2024.04.24 / 작품 그림
2024.02.19 / 작품 그림
2024.02.11 / 작품 그림 
2023.12.25 / 작품 그림 

'작가명' : '최다킬' 
 2024.08.05 / 작품 그림
 2024.04.28 / 작품 그림
 2024.04.25 / 1000 

'작가명' :'범배'
2024.09.25 / 작품 그림
2024.08.21 / 작품 그림
2024.05.29 / 작품 그림
2024.05.01  / 작품 그림
2024.04.21 / 1000 
2024.04.10 / 작품 그림 
2024.04.04 / 작품 그림 

'작가명' : '손하기'
2024.08.25 / 10000 
2024.07.18 / 작품 그림 
2024.05.16 / 작품 그림 
2024.05.16 / 5000 
2024.05.01 / 작품 그림
2023.11.30 / 작품 그림

'작가명' : '허새보'  
2024.09.14 / 일상 사진
2024.09.10 / 일상 사진 
2024.09.02 / 작품 그림
2024.08.14 / 일상 사진
2024.08.06 / 일상 사진 
2024.07.28  / 일상 사진 
2024.07.24 / 일상 사진 
2024.07.24 / 일상 사진 
2024.07.17 / 일상 사진 
2024.07.10 / 일상 사진
2024.06.28 / 1000 
2024.06.10  / 일상 사진
2024.06.09 / 일상 사진
2024.06.06 / 기타 
2024.05.23 / 일상 사진
2024.05.07 / 일상 사진 
2024.02.01 / 일상 사진 
2024.02.01 / 일상 사진 
2023.12.22 / 일상 사진 
2023.12.20  / 일상 사진 
2023.12.02 / 일상 사진 
2023.11.17 / 기타 
2023.11.10 / 일상 사진 
2023.10.15 / 일상 사진 
2023.10.09  / 일상 사진 

'작가명' : '포스스튜디오' 
 2024.04.10 / 작품 그림 
 2024.04.02/ 작품 그림
 2024.04.02 /  작품 그림
 2024.04.01/ 기타 
 2023.10.20/  작품 그림
 2023.10.18 / 작품 그림
 2023.10.18 / 작품 그림
 2023.10.13 / 작품 그림
 2023.10.11 / 일상 사진
 2023.10.11 / 일상 사진
 2023.10.10 / 작품 그림
 2023.10.06 / 작품 그림
 2023.10.06  / 작품 그림
 2023.10.06 / 작품 그림
 2023.10.06 / 작품 그림

  
'작가명' : '박태준'
2024.07.24 / 50000
2024.08.02 / 일상 사진
 

'작가명' :  '모랑지'
2024.09.25 / 기타 
2024.09.19 / 20000
2024.04.01 / 기타 
2023.12.21 / 작품 그림
2023.09.27 / 기타 

################################

'작가명' :  '고추참치'
2024.10.08 / 작품 그림
2024.09.03 / 5000 
2024.08.06 / 작품 그림
2023.11.29 / 기타
2023.09.21 / 작품 그림
2023.09.21 / 작품 그림


'작가명' : '상금' 
2024.08.19 / 기타
2024.07.25 / 1000 
2024.07.14 / 일상 사진 
2024.07.02 / 일상 사진 
2023.09.14 / 작품 그림


###########

'작가명' : '잇선'
2024.10.17 /기타 
2024.10.04 / 작품 그림 
2024.10.01 / 작품 그림 
2024.09.26 / 작품 그림 
2024.09.23 / 기타
2024.07.10 / 기타
2024.06.23 / 기타
2024.06.19 / 기타
2024.06.13 / 작품 그림 
2024.06.04 / 기타
2024.05.25 / 작품 그림 
2024.05.19 / 기타 
2024.05.13 / 기타 
2024.05.09 / 5000 
2024.05.07 / 작품 그림 
2024.05.01 / 작품 그림 
2024.05.01 / 일상 사진
2024.04.25 / 작품 그림
2024.04.17 / 작품 그림
2024.04.06 / 작품 그림
2024.04.04 /  작품 그림
2024.04.01 / 기타
2024.03.26 / 작품 그림
2024.03.20 / 작품 그림
2024.03.13 / 작품 그림
2024.03.11 / 작품 그림
2024.03.04 / 작품 그림
2024.03.03 / 작품 그림
2024.03.01  / 작품 그림
2024.02.26  / 작품 그림
2024.02.25  / 작품 그림
2024.02.25  / 작품 그림
2024.02.21 / 작품 그림 
2024.02.02 / 작품 그림 
2024.01.25  / 작품 그림 
2024.01.15   / 작품 그림 
2024.01.08 / 작품 그림 

'작가명' :  '이담'
2024.07.30 / 30000 
2024.07.21 / 기타 
2024.06.09 / 기타 
2024.05.19 / 작품 그림
2024.05.17 / 기타 
2024.05.17  / 기타 
2024.02.09 / 작품 그림
2023.10.26 /  작품 그림
2023.09.13 /  작품 그림



'작가명' : '혀노'
2024.09.24 / 작품 그림
2024.09.17 / 작품 그림
2024.09.11 / 기타 
2024.09.06 / 기타 
2024.08.10 / 작품 그림
2024.07.28 / 30000
2024.05.25 / 작품 그림
2024.05.13 / 작품 그림
2024.05.07 / 작품 그림
2024.04.12 / 20000
2024.04.01 / 작품 그림
2024.03.16 / 작품 그림
2024.02.16 / 작품 그림
2024.02.12 / 작품 그림
2024.01.20 / 기타


'작가명' : 'HO9'
2024.08.06 / 5000


'작가명' : '조용석'
2024.06.26 / 작품 그림
2024.01.05 / 작품 그림
2023.11.09 / 작품 그림
2023.10.16 / 작품 그림
2023.10.06 / 작품 그림
2023.09.17  / 작품 그림
2023.09.17 / 일상 사진
2023.09.14  / 작품 그림




'작가명' : '이은재'
2024.09.05 / 작품 그림
2024.09.02/ 10000
2024.08.01 / 작품 그림
2024.07.18 / 기타 
2024.07.17 / 작품 그림
2024.07.07 / 작품 그림
2024.07.07 / 작품 그림
2024.06.15 / 기타 
2024.06.13 / 작품 그림
2024.06.07 / 기타 
2024.05.31 / 기타 
2024.05.24 / 작품 그림
2024.05.02 / 작품 그림
2024.04.13 / 일상 사진
2024.03.21 /  일상 사진
2024.03.09/  일상 사진
2024.02.15 / 일상 사진
2024.02.02  / 작품 그림
2024.01.12 / 일상 사진
2024.01.01 / 작품 그림
2023.12.25 / 작품 그림
2023.12.24 / 작품 그림
2023.12.22 / 작품 그림
2023.12.14 / 작품 그림
2023.12.12 / 작품 그림
2023.12.08 / 작품 그림
2023.12.04  / 작품 그림
2023.11.17 / 작품 그림
2023.11.09 /  작품 그림
2023.10.06/ 작품 그림 
2023.09.28 / 작품 그림 
2023.09.21 / 작품 그림 
2023.09.21 / 작품 그림
2023.09.20 /  작품 그림

'작가명' : '돌석'
2024.10.01 / 작품 그림
2024.09.17  / 작품 그림
2024.08.20  / 작품 그림
2024.08.13/ 작품 그림 
2024.08.10 / 1000
2024.08.06  / 작품 그림 
2024.07.30 / 작품 그림 
2024.07.23 / 작품 그림 
2024.07.09 / 일상 사진
2024.07.09 / 작품 그림
2024.07.02 / 작품 그림
2024.06.26 / 작품 그림
2024.06.25 / 작품 그림

'작가명' : '라군'
2024.05.20 / 작품 그림
2024.01.26 / 작품 그림
2023.12.28 / 작품 그림
2023.12.03 / 작품 그림
2023.09.29 / 기타

'작가명' :  '윤성' 
2024.05.25 / 1000
2024.01.25/ 작품 그림
2023.10.08 / 일상 사진
2023.10.02 / 일상 사진




'작가명' : '채키'   ###### 다시 들어가서 봐보기 10월 초까지 수집한듯!!
2024.09.15 / 일상 사진 
2024.08.28 / 작품 그림
2024.07.10 / 일상 사진 
2024.06.26 / 작품 그림
2024.06.19 / 일상 사진 
2024.05.17 / 일상 사진 
2024.05.08/ 일상 사진 

'작가명' : '이난'
2024.10.29 / 작품 그림
2024.09.22 / 일상 사진
2024.08.30 / 기타 
2024.08.29 / 일상 사진
2024.08.21 / 일상 사진
2024.07.19 / 기타 
2024.06.27 / 일상 사진
2024.06.08 / 일상 사진
2024.06.07 / 기타 
2024.05.29 / 작품 그림
2024.05.23 / 일상 사진
2024.05.22 / 작품 그림
2024.05.05 / 작품 그림
2024.02.17 / 기타
2023.12.15 / 작품 그림
2023.11.30 / 기타
2023.11.18 / 작품 그림 
2023.10.20 /  기타
2023.10.15 /일상 사진
2023.09.29 /  기타
2023.09.25  /일상 사진
2023.09.16 /일상 사진

'작가명' : '임리나'
2024.10.05 / 20000  
2024.09.17 / 작품 그림 
2024.09.14  / 작품 그림 
2024.08.17 / 일상 사진
2024.02.20 / 작품 그림 
2023.10.28  / 작품 그림 
2023.09.13  / 작품 그림 

'작가명' : '병장'   
2024.08.05 /  작품 그림
2024.08.04 / 5000
2024.07.13 /  작품 그림
2024.05.07/  작품 그림
2024.05.05/  작품 그림
2024.02.29 / 일상 사진 
2023.12.26 /  작품 그림
2023.11.29 /  일상 사진 
2023.11.23 /  작품 그림
2023.11.20/  작품 그림
2023.11.14 /  작품 그림
2023.10.31/  작품 그림
2023.10.26 /  작품 그림
2023.10.24  /  작품 그림
2023.10.19 /  작품 그림
2023.10.10 /  작품 그림
2023.10.09 /  작품 그림
2023.10.03/  작품 그림
2023.10.03/  작품 그림
2023.09.30/  작품 그림
2023.09.29/  작품 그림
2023.09.26  /  일상 사진 
2023.09.25/  작품 그림
023.09.25 /  일상 사진 

'작가명' : '정종택'  
2024.07.08 / 작품 그림
2024.07.05 /기타
2024.06.20 / 기타 
2024.05.07 / 5000
2024.04.02 / 작품 그림
2023.12.21/ 작품 그림
2023.11.15  / 작품 그림
2023.11.14 / 작품 그림
2023.11.14 / 작품 그림
2023.09.27 / 작품 그림
2023.09.27 / 작품 그림
2023.09.26/ 작품 그림
2023.09.26 / 작품 그림
2023.09.26  / 작품 그림


'작가명' :'박만사'   ### 거의 매일 한개씩 올리시다니...일단 Keep..
2024.09.27 / 50000
2024.09.15 / 작품 그림
2024.09.10 / 작품 그림
2024.07.31 / 40000
2024.07.19 /  작품 그림
2024.05.02 /  작품 그림
2024.04.03 /   작품 그림
2024.04.01  /   작품 그림
2024.03.31/   작품 그림
2024.03.31/   작품 그림
2024.03.30 / 작품 그림
2024.03.29 / 작품 그림
2024.03.28 / 작품 그림
2024.03.27 / 작품 그림
2024.03.27 / 기타 
2024.03.26/ 작품 그림
2024.03.24/ 작품 그림
2024.03.23 / 기타 
2024.03.22/ 작품 그림
2024.03.21/ 작품 그림
2024.03.20/ 작품 그림
2024.03.19/ 작품 그림
2024.03.19/ 작품 그림
2024.03.18/ 작품 그림
2024.03.17/ 작품 그림
2024.03.16/ 작품 그림
2024.03.15/ 작품 그림
2024.03.14/ 작품 그림
2024.03.13/ 작품 그림
2024.03.12/ 작품 그림
2024.03.11/ 작품 그림
2024.03.09/ 작품 그림
2024.03.09/기타
2024.03.08 / 기타 
2024.03.08 / 작품 그림
2024.03.06 /작품 그림
2024.03.06/작품 그림
2024.03.05/작품 그림
2024.03.04/작품 그림
2024.03.03/작품 그림
2024.03.02/작품 그림
2024.03.01/작품 그림
2024.02.29/작품 그림
2024.02.28/작품 그림
2024.02.27/작품 그림 
2024.02.25 / 기타 
2024.02.25/작품 그림 
2024.02.24/작품 그림
2024.02.23/작품 그림
2024.02.22 / 작품 그림
########3 ########3 ########3 
2024.02.21/ 작품 그림
2024.02.20/ 작품 그림
2024.02.19/ 작품 그림
2024.02.18/ 작품 그림
2024.02.18 / 기타 
2024.02.17/ 작품 그림
2024.02.16 / 작품 그림
2024.02.15 / 기타 
2024.02.14 / 작품 그림
2024.02.13/ 작품 그림
2024.02.12/ 작품 그림
2024.02.10/ 작품 그림
2024.02.10/ 작품 그림 
2024.02.09 / 기타 
2024.02.08/ 작품 그림
2024.02.07 / 작품 그림
2024.02.05 / 작품 그림
2024.02.05 / 기타 
2024.02.04 / 작품 그림
2024.02.04 / 작품 그림
2024.02.03 / 기타 
2024.02.02  / 작품 그림
2024.02.01/ 작품 그림
2024.01.31/ 작품 그림
2024.01.30/ 작품 그림
2024.01.28/ 작품 그림
2024.01.27/ 작품 그림
2024.01.27/ 작품 그림
2024.01.26/ 작품 그림
2024.01.25/ 작품 그림
2024.01.24/ 작품 그림
2024.01.23 / 기타 
2024.01.22/ 기타 
2024.01.22 / 작품 그림 
2024.01.21/ 작품 그림
2024.01.20/ 작품 그림
2024.01.19/ 작품 그림
2024.01.17/ 작품 그림
2024.01.17/ 작품 그림
2024.01.16 / 기타 
2024.01.15/ 작품 그림
2024.01.14/ 작품 그림
2024.01.13/ 작품 그림
2024.01.12/ 작품 그림
2024.01.11/ 작품 그림
2024.01.10/ 작품 그림
2024.01.09 / 기타 
2024.01.07 / 기타 
2024.01.07 / 작품 그림
2024.01.06 / 기타 
2024.01.05/ 작품 그림
2024.01.04/ 작품 그림
2024.01.03/ 작품 그림
2024.01.02/ 작품 그림




'작가명' :  '남자의 이야기'
 2024.10.24 / 작품 그림 
 2024.09.19/ 작품 그림 
 2024.09.05/ 작품 그림 
 2024.08.03/ 작품 그림 
 2024.07.16/ 작품 그림 
 2024.03.29 / 기타 
 2024.03.29/ 작품 그림 
2024.02.26/ 작품 그림 
2024.01.19/ 작품 그림 
2024.01.17/ 작품 그림 
2024.01.06/ 작품 그림 
2024.01.04/ 작품 그림 
2023.12.29/ 작품 그림 
2023.12.28/ 작품 그림 
2023.12.22/ 작품 그림 
2023.12.20/ 작품 그림 
2023.12.16/ 작품 그림 
2023.12.06/ 작품 그림 
2023.11.29/ 작품 그림 
2023.11.17/ 작품 그림 
2023.11.16/ 작품 그림 
2023.11.11/ 작품 그림 
2023.11.08/ 작품 그림 
2023.10.27/ 작품 그림 
2023.10.25/ 작품 그림 
2023.10.20/ 작품 그림 
2023.10.18/ 작품 그림 
2023.10.13/ 작품 그림 
2023.10.11/ 작품 그림 
2023.09.27/ 작품 그림 
2023.09.22/ 작품 그림 
2023.09.20/ 작품 그림 

'작가명' : '한가람'       
2024.04.09 / 10000




'작가명' : '펀치킥'
2024.09.28 / 작품 그림  
2024.09.25 / 5000
2024.09.10 / 작품 그림
2024.05.04 / 작품 그림
2024.05.01 / 작품 그림
2024.02.28 /작품 그림
2024.02.07 / 작품 그림
2024.01.31 / 작품 그림
2024.01.21 / 작품 그림
2024.01.19 / 작품 그림
2023.12.26  / 작품 그림
2023.12.21/ 작품 그림
2023.12.19/ 작품 그림
2023.11.28/ 작품 그림
2023.11.21/ 작품 그림
2023.11.15/ 작품 그림
2023.11.07/ 작품 그림
2023.11.01/ 작품 그림
2023.10.24/ 작품 그림



'작가명' : '제나'   
2024.09.10 / 기타 
2024.07.26 / 기타 
2024.07.26 / 기타 
2024.07.25 / 작품 그림 
2024.07.25/ 작품 그림 
2024.07.25/ 작품 그림 
2024.07.25/ 작품 그림 
2024.06.27/ 작품 그림 
2024.05.28 / 10000
2023.11.29 /기타 
2023.11.24/기타 
2023.10.31 / 작품 그림 
2023.09.27 / 기타 
2023.09.27/ 작품 그림 

'작가명' : '태완'    
2024.08.06 / 5000

'작가명' : '유누니'    
2024.04.07 / 5000

'작가명' : '박진환'    
2024.10.08 / 작품 그림  
2024.10.08 / 10000
2024.09.16 / 작품 그림  
2024.08.04 / 5000
2023.11.13 /  작품 그림 
2023.09.26 /  작품 그림 

'작가명' : 'JP'   
2024.10.17 / 10000
2024.09.26 / 기타 
2024.09.17 / 5000
2024.08.12 / 1000

'작가명' :  '부겸'  
2024.08.12 / 1000

'작가명' :  '배민기'
2024.10.02 / 일상 사진
2024.09.27  / 작품 그림
2024.09.19/ 작품 그림
2024.06.24/ 작품 그림
024.01.30/ 일상 사진
2024.01.11 / 기타 
2023.11.09 / 기타 
2023.11.08 / 일상 사진
2023.09.28/ 작품 그림
2023.09.21/ 작품 그림
2023.09.19/ 작품 그림
2023.09.18 / 기타 




'작가명' :  '운'
2024.10.16 / 기타 
2024.08.31  / 작품 그림
2024.06.24 / 기타 
2024.04.13 / 기타 
2024.02.15 / 일상 사진
2024.01.11 / 기타 
2023.12.28 / 작품 사진 
2023.12.02 / 일상 사진
2023.11.09 / 기타 
2023.10.04 / 일상 사진

'작가명' :  '시바견'
2024.07.01 / 작품 그림
2024.06.16 / 일상 사진
2024.06.16 / 일상 사진
2024.06.02 / 일상 사진
2024.05.27 / 일상 사진
2024.05.22 / 일상 사진
2024.05.20 / 작품 그림
2024.05.05 / 작품 그림
2024.05.05  / 일상 사진
2024.04.22 / 일상 사진
2024.04.16 / 작품 그림
2024.04.16/ 일상 사진
2024.04.01 / 일상 사진
2024.04.01 / 일상 사진
2024.03.27 / 일상 사진
2024.03.20 / 일상 사진
 
2024.03.19 / 일상 사진
2024.03.18 / 일상 사진
2024.03.10 / 작품 그림
2024.03.10 / 일상 사진
2024.03.10 / 일상 사진
2024.02.26 / 일상 사진
2024.02.26/ 일상 사진
2024.02.25 / 작품 그림
2024.02.25/ 일상 사진
2024.02.25 / 일상 사진
2024.02.12 / 일상 사진
2024.02.11 / 일상 사진
2024.02.11/ 일상 사진
2024.02.03 / 일상 사진
2024.01.30 / 작품 그림
2024.01.10 /  작품 그림
2023.12.21 / 일상 사진
2023.12.21/  작품 그림
2023.12.20/ 일상 사진
# 작품 그림 / 일상 사진 / 기타 

'작가명' :  '강견'
2024.10.05 / 기타 
2024.09.17 / 일상 사진 
2024.09.14 / 작품 그림
2024.08.31/ 작품 그림
2024.08.17 / 일상 사진 
2024.06.26 / 기타 
2024.06.15 / 일상 사진 
2024.05.22 / 작품 그림
2024.04.06 / 일상 사진  
2024.04.01 / 기타
2024.03.17 / 기타  
2024.03.09 / 일상 사진
2024.02.20 / 일상 사진
2024.02.10 / 작품 그림
2023.12.24 / 일상 사진
2023.12.02 / 일상 사진
2023.11.28 / 기타 


 
# 작품 그림 / 일상 사진 / 기타 
'작가명' :  '명랑' ## 이분도 크롤링 다시 해야할듯 . 
2024.11.01 / 일상 사진
2024.10.03 / 작품 그림
2024.08.09 / 5000
2024.06.26 / 일상 사진
2024.06.13 / 일상 사진
2024.05.26 / 일상 사진
2024.05.26 / 작품 그림
2024.05.08 / 일상 사진
2024.05.01 / 일상 사진
2024.04.08 / 기타 
2024.04.06 / 작품 그림 
2024.04.01 / 작품 그림 
2024.03.22 / 일상 사진
2024.03.06 / 기타 
2024.03.05 / 작품 그림 
2024.03.03 / 일상 사진
2024.02.22 / 일상 사진
2024.02.22 / 일상 사진
2024.02.17 / 기타 
2024.02.11 / 기타 
2024.02.09 / 일상 사진
2024.01.10 /  일상 사진
2024.01.03/ 작품 그림 
2023.12.30/ 일상 사진
2023.12.28 / 작품 그림 
2023.12.25/ 일상 사진
2023.12.07 / 작품 그림 
2023.11.30/ 작품 그림 
2023.11.22/ 일상 사진
2023.11.16 / 일상 사진
2023.11.08 / 일상 사진
2023.10.25 / 일상 사진
2023.10.20 / 일상 사진
2023.10.17/ 작품 그림
2023.10.12 / 작품 그림
2023.10.06 / 일상 사진
2023.10.05 / 작품 그림
2023.09.28 / 작품 그림
2023.09.27/ 작품 그림
2023.09.21 / 작품 그림
2023.09.21 / 일상 사진
2023.09.17 / 일상 사진
2023.09.15 / 작품 그림 
2023.09.15/ 일상 사진


'작가명' : '하일권'
 
2024.10.27 / 작품 그림
2024.10.20 / 작품 그림
2024.10.13/ 작품 그림
2024.10.06/ 작품 그림
2024.09.21/ 작품 그림
2024.09.15 / 작품 그림
2024.09.08 / 작품 그림
2024.08.24/ 작품 그림
2024.08.18 / 10000
2024.08.17/ 작품 그림
2024.07.28/ 작품 그림
2024.07.14 / 작품 그림
2024.06.30/ 작품 그림
2024.06.23 / 작품 그림
2024.06.09 / 작품 그림
2024.05.25 / 작품 그림
2024.05.18 / 작품 그림
2024.05.12/ 작품 그림
2024.05.05 / 작품 그림
2024.04.27 / 작품 그림
2024.04.20 / 작품 그림
2024.04.13 / 작품 그림
2024.04.06 / 작품 그림
2024.03.23 / 작품 그림
2024.03.16 / 작품 그림
2024.03.09 / 작품 그림
2024.03.03 / 작품 그림
2024.02.24/ 작품 그림
2024.02.17 / 작품 그림
2024.01.05 / 일상 사진
2023.09.18/ 작품 그림

'작가명' :  '이대한' 
 
2024.09.16 / 작품 그림
2024.08.11 / 작품 그림
2024.05.20 / 작품 그림
2024.04.26 / 1000

'작가명' :  '황양'

2024.11.02 / 작품 그림
2024.10.04 / 일상 사진
2024.09.26/ 일상 사진
2024.07.21 / 작품 그림
2024.07.15 / 기타 
 
2024.07.08 / 작품 그림
2024.06.27 / 작품 그림
2024.05.31 / 기타 
2024.05.13 / 기타 
2024.05.03  /1000
2024.04.18 /  작품 그림
2024.04.01 / 일상 사진
2024.03.17 / 기타 
2024.03.05/ 기타 

'작가명' :  '득7이'
2024.08.07/ 1000
2024.08.02 / 작품 그림
2024.07.25 / 기타 
2024.06.11 / 작품 그림

'작가명' :  '이솔' 
2024.11.01 / 작품 그림
2024.09.20 / 기타 
2024.09.12  /기타 
2024.09.07 / 5000
2024.09.02 / 일상 사진
2024.08.20 / 작품 그림
2024.07.10 / 1000
2024.07.09 / 작품 그림
2024.07.08 / 작품 그림

'작가명' :  '꼬모소이'
2024.09.12 / 기타 
2024.08.14 / 일상 사진
2024.07.10 / 작품 그림
2024.06.20 / 1000


'작가명' :  '명랑'  
2024.11.01 / 일상 사진
2024.10.03 / 작품 그림
2024.08.09 / 5000
2024.06.26 / 일상 사진
2024.06.13 / 일상 사진
2024.05.26 / 일상 사진
2024.05.26 / 작품 그림
2024.05.08 / 일상 사진
2024.05.01 / 일상 사진
2024.04.08 / 기타 
2024.04.06 / 작품 그림 
2024.04.01 / 작품 그림 
2024.03.22 / 일상 사진
2024.03.06 / 기타 
2024.03.05 / 작품 그림 
2024.03.03 / 일상 사진
2024.02.22 / 일상 사진
2024.02.22 / 일상 사진
2024.02.17 / 기타 
2024.02.11 / 기타 
2024.02.09 / 일상 사진
2024.01.10 /  일상 사진
2024.01.03/ 작품 그림 
2023.12.30/ 일상 사진
2023.12.28 / 작품 그림 
2023.12.25/ 일상 사진
2023.12.07 / 작품 그림 
2023.11.30/ 작품 그림 
2023.11.22/ 일상 사진
2023.11.16 / 일상 사진
2023.11.08 / 일상 사진
2023.10.25 / 일상 사진
2023.10.20 / 일상 사진
2023.10.17/ 작품 그림
2023.10.12 / 작품 그림
2023.10.06 / 일상 사진
2023.10.05 / 작품 그림
2023.09.28 / 작품 그림
2023.09.27/ 작품 그림
2023.09.21 / 작품 그림
2023.09.21 / 일상 사진
2023.09.17 / 일상 사진
2023.09.15 / 작품 그림 
2023.09.15/ 일상 사진

###################################################


'작가명' : '하일권'
 
2024.10.27 / 작품 그림
2024.10.20 / 작품 그림
2024.10.13/ 작품 그림
2024.10.06/ 작품 그림
2024.09.21/ 작품 그림
2024.09.15 / 작품 그림
2024.09.08 / 작품 그림
2024.08.24/ 작품 그림
2024.08.18 / 10000
2024.08.17/ 작품 그림
2024.07.28/ 작품 그림
2024.07.14 / 작품 그림
2024.06.30/ 작품 그림
2024.06.23 / 작품 그림
2024.06.09 / 작품 그림
2024.05.25 / 작품 그림
2024.05.18 / 작품 그림
2024.05.12/ 작품 그림
2024.05.05 / 작품 그림
2024.04.27 / 작품 그림
2024.04.20 / 작품 그림
2024.04.13 / 작품 그림
2024.04.06 / 작품 그림
2024.03.23 / 작품 그림
2024.03.16 / 작품 그림
2024.03.09 / 작품 그림
2024.03.03 / 작품 그림
2024.02.24/ 작품 그림
2024.02.17 / 작품 그림
2024.01.05 / 일상 사진
2023.09.18/ 작품 그림

'작가명' :  '이대한' 
 
2024.09.16 / 작품 그림
2024.08.11 / 작품 그림
2024.05.20 / 작품 그림
2024.04.26 / 1000 

'작가명' :  '황양'

2024.11.02 / 작품 그림
2024.10.04 / 일상 사진
2024.09.26/ 일상 사진
2024.07.21 / 작품 그림
2024.07.15 / 기타 
 
2024.07.08 / 작품 그림
2024.06.27 / 작품 그림
2024.05.31 / 기타 
2024.05.13 / 기타 
2024.05.03  /1000
2024.04.18 /  작품 그림
2024.04.01 / 일상 사진
2024.03.17 / 기타 
2024.03.05/ 기타 

'작가명' :  '득7이'
2024.08.07/ 1000
2024.08.02 / 작품 그림
2024.07.25 / 기타 
2024.06.11 / 작품 그림

'작가명' :  '이솔' 
2024.11.01 / 작품 그림
2024.09.20 / 기타 
2024.09.12  /기타 
2024.09.07 / 5000
2024.09.02 / 일상 사진
2024.08.20 / 작품 그림
2024.07.10 / 1000
2024.07.09 / 작품 그림
2024.07.08 / 작품 그림

'작가명' :  '꼬모소이'
2024.09.12 / 기타 
2024.08.14 / 일상 사진
2024.07.10 / 작품 그림
2024.06.20 / 1000  




'작가명' :  '켄타'
2024.09.13 / 작품 그림
2024.07.19 / 작품 그림
2024.04.01 / 작품 그림
2023.12.30 / 작품 그림
2023.12.22 / 작품 그림
2023.11.19 / 작품 그림
2023.11.10 / 작품 그림

'작가명' : '김대영'  
2024.10.29 / 1000
2024.08.03 / 일상 사진
2023.10.23 / 일상 사진

'작가명' :  '이동건'  
2024.09.03 / 작품 그림
2024.08.22 / 40000
2024.08.15 / 기타 
2024.05.17 / 기타 
2024.05.17/ 기타 
2024.05.14 / 작품 그림
2024.05.09 / 기타 
2024.03.01 /  작품 그림
2024.02.08 / 작품 그림
2023.12.29 / 작품 그림
2023.12.16 / 작품 그림
2023.10.06 / 작품 그림
2023.10.04 / 작품 그림
2023.10.02 / 일상 사진 
2023.09.29 / 기타 
2023.09.22 / 일상 사진 
2023.09.20  / 일상 사진 
2023.09.18 / 작품 그림
2023.09.18 / 작품 그림
2023.09.15  / 작품 그림
2023.09.13  / 일상 사진 
2023.09.13/ 일상 사진 


'작가명' :  '승우'  
 
2024.09.28 / 기타 
2024.07.15 / 20000
2024.05.23 / 기타 
2024.03.31 / 기타 
2024.02.21/ 기타 
2023.11.14 / 기타 
2023.10.04 / 작품 그림

'작가명' :  '수박양'  
2024.10.08 / 20000
2024.05.09 / 일상 사진
2024.04.01 / 작품 그림
2024.02.16 / 작품 그림 
2024.01.06 / 작품 그림
2023.12.29  / 작품 그림
2023.10.05 / 일상 사진
2023.09.16  / 작품 그림

'작가명' :  '스튜디오MW'   
2024.10.05 / 작품 그림
2024.10.05 / 작품 그림
2024.10.04 / 작품 그림
2024.10.02 / 작품 그림
2024.09.30 / 5000
2024.09.15 / 기타
2024.09.14 / 기타
2024.09.13 / 기타
2024.09.12 / 기타
2024.08.11 / 작품 그림
2024.08.10 / 작품 그림
2024.07.31 / 1000
2024.07.28 / 작품 그림
2024.07.27 / 기타 
2024.06.01 / 작품 그림
2024.05.31/ 작품 그림
2024.04.07/ 작품 그림
2024.04.01/ 작품 그림
2024.03.21/ 작품 그림
2024.03.13/ 작품 그림
2024.03.02/ 작품 그림
2024.03.01/ 작품 그림
2024.02.28/ 작품 그림
2024.02.26 /  작품 그림
2024.02.08/ 작품 그림


'작가명' :  '지페리'  
2024.10.25 / 작품 그림
2024.09.13/ 작품 그림
2024.08.23/ 작품 그림
2024.07.12 / 일상 사진
2024.07.05/ 작품 그림
2024.06.07  / 일상 사진
2024.05.26 / 20000
2024.05.24 / 작품 그림
2024.05.17/ 작품 그림
2024.04.26/ 작품 그림
2024.04.19/ 작품 그림
2024.04.05/ 작품 그림
2024.03.31 / 기타 
2024.03.30/ 작품 그림
2024.03.23 / 작품 그림
2024.03.15/ 작품 그림
2024.03.10/ 작품 그림
2024.03.08/ 작품 그림
2024.03.01/ 일상 사진
2024.02.29/ 작품 그림
2024.02.23/ 작품 그림
2024.02.19/ 작품 그림
2024.02.09/ 작품 그림
2024.01.20/ 작품 그림
2024.01.06/ 작품 그림
2023.12.30/ 작품 그림
2023.12.23/ 작품 그림
2023.12.16/ 작품 그림
2023.12.08/ 작품 그림
2023.11.15/ 작품 그림
2023.11.08/ 작품 그림
2023.11.01/ 작품 그림
2023.10.30/ 작품 그림
2023.10.15/ 작품 그림
2023.10.14/ 작품 그림
2023.10.08/ 작품 그림
2023.10.07 / 기타 
2023.10.06/ 작품 그림
2023.10.06 / 일상 사진
2023.10.06 / 작품 그림
2023.09.30 / 기타 
2023.09.29 / 작품 그림
2023.09.28/ 작품 그림
2023.09.25/ 작품 그림
2023.09.23 / 기타 
2023.09.22/ 작품 그림
2023.09.15/ 작품 그림
2023.09.14/ 작품 그림
2023.09.14/ 작품 그림
2023.09.13/ 작품 그림 


'작가명' : '임형'   
2024.11.01 / 10000
2024.10.18 / 일상 사진
2024.09.27/ 작품 그림
2024.09.16/ 작품 그림
2024.09.01 / 작품 그림
2024.08.26 / 일상 사진
2024.08.18 / 작품 그림
2024.08.16 / 5000
2024.08.16   / 일상 사진
2024.08.15 / 일상 사진
2024.08.10/ 작품 그림
2024.08.07   / 일상 사진
2024.08.03 / 작품 그림
2024.07.23 / 작품 그림
2024.07.10 / 일상 사진
2024.07.06/ 작품 그림
2024.06.29/ 작품 그림
2024.06.18 /  일상 사진
2024.06.15 / 작품 그림
2024.06.13/ 작품 그림
2024.06.13 /  일상 사진
 2024.06.11 / 기타 
 2024.06.07/  일상 사진
 2024.06.01/  일상 사진
 2024.05.24/ 작품 그림
 2024.05.24/ 작품 그림
 2024.05.22 / 1000
 2024.05.21 /  일상 사진
 2024.05.18/ 작품 그림
 2024.05.17/ 작품 그림
 2024.05.17/  일상 사진 ---'작가명', '게시일', '게시글 내용' 컬럼을 가진 pandas 데이터 프레임이 생성

SyntaxError: invalid syntax (1057779430.py, line 2)

## let's start to make df

In [37]:
import pandas as pd

# 데이터 정의
data_ck = {
    '작가명': ['채키'] * 7 + ['이난'] * 22 + ['임리나'] * 7 + ['병장'] * 24 + ['정종택'] * 14,
    '게시일': [
        # 채키
        '2024.09.15', '2024.08.28', '2024.07.10', '2024.06.26', '2024.06.19', 
        '2024.05.17', '2024.05.08', 
        # 이난 
        '2024.10.29', '2024.09.22', '2024.08.30', '2024.08.29', '2024.08.21', 
        '2024.07.19', '2024.06.27', '2024.06.08','2024.06.07', '2024.05.29',
        '2024.05.23', '2024.05.22', '2024.05.05','2024.02.17', '2023.12.15', 
        '2023.11.30', '2023.11.18', '2023.10.20',  '2023.10.15', '2023.09.29',
        '2023.09.25', '2023.09.16', 
        # 임리나
        '2024.10.05','2024.09.17', '2024.09.14', '2024.08.17', '2024.02.20', 
        '2023.10.28', '2023.09.13', 
        # 병장
        '2024.08.05', '2024.08.04', '2024.07.13', '2024.05.07', '2024.05.05', 
        '2024.02.29', '2023.12.26', '2023.11.29', '2023.11.23','2023.11.20', 
        '2023.11.14', '2023.10.31', '2023.10.26', '2023.10.24', '2023.10.19', 
        '2023.10.10', '2023.10.09', '2023.10.03', '2023.10.03', '2023.09.30', 
        '2023.09.29', '2023.09.26', '2023.09.25', '2023.09.25',
        # 정종택
        '2024.07.08', '2024.07.05', '2024.06.20', '2024.05.07', '2024.04.02', 
        '2023.12.21', '2023.11.15', '2023.11.14', '2023.11.14', '2023.09.27', 
        '2023.09.27', '2023.09.26', '2023.09.26', '2023.09.26'
    ],
    '게시글 내용': [
         # 채키
        '일상 사진', '작품 그림', '일상 사진', '작품 그림', '일상 사진', 
        '일상 사진', '일상 사진', 
        # 이난
        '작품 그림', '일상 사진', '기타','일상 사진', '일상 사진', 
        '기타', '일상 사진', '일상 사진',  '기타', '작품 그림', 
        '일상 사진', '작품 그림','작품 그림', '기타', '작품 그림',
        '기타', '작품 그림', '기타', '일상 사진', '기타', 
        '일상 사진', '일상 사진',
        # 임리나
         '20000','작품 그림', '작품 그림',  '일상 사진', '작품 그림', 
         '작품 그림', '작품 그림', 
         # 병장
        '작품 그림', '5000', '작품 그림', '작품 그림', '작품 그림',
        '일상 사진', '작품 그림', '일상 사진', '작품 그림', '작품 그림',

        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림', 
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '일상 사진', '작품 그림', '일상 사진','작품 그림', 

        # 정종택
        '기타', '기타', '5000', '작품 그림', '작품 그림', 
        '작품 그림', '작품 그림', '작품 그림', '작품 그림','작품 그림', 
        '작품 그림', '작품 그림', '작품 그림', '작품 그림'
    ]
}
# 데이터 정의
data_gs = {
    '작가명': ['감자'] * 13 + ['진돌'] * 26,
    '게시일': [ '2024.09.03', '2024.08.19', '2024.08.12', '2024.07.20','2024.07.19', 
              '2024.06.21', '2024.04.14', '2024.04.10', '2024.04.01', '2024.03.28', 
              '2024.03.06', '2024.03.05', '2024.03.04', 
              
              '2024.09.28', '2024.09.24', '2024.08.27','2024.07.30', '2024.06.12', 
              '2024.05.22', '2024.05.08','2024.04.17', '2024.04.10', '2024.04.08', 

              '2024.04.01', '2024.03.28', '2024.03.27', '2024.03.20', '2024.02.29', 
              '2024.02.27', '2024.02.16', '2024.01.29', '2023.11.08', '2023.10.02', 

              '2023.10.02', '2023.09.29', '2023.09.21', '2023.09.15', '2023.09.14', 
              '2023.09.14'
    ],
    '게시글 내용': [ '기타', '작품 그림', '작품 그림', '일상 사진', '5000', 
                  '기타',  '일상 사진', '일상 사진', '작품 그림', '작품 그림', 
                  '작품 그림', '작품 그림', '작품 그림', 
                  
                  '20000', '일상 사진', '기타',  '기타', '일상 사진', 
                  '일상 사진', '일상 사진',  '일상 사진',  '일상 사진', '일상 사진',
                   
                   '기타', '일상 사진',  '일상 사진', '일상 사진', '작품 그림',
                    '일상 사진',   '일상 사진',  '작품 그림', '일상 사진', '일상 사진', 
                   
                    '일상 사진', '일상 사진',  '일상 사진', '일상 사진', '일상 사진', '일상 사진'
    ]
}



 
# 데이터 정의
data_lee = {
    '작가명': ['이은재'] * 34 + ['돌석'] * 13 + ['라군'] * 5 + ['윤성'] * 4,
    '게시일': [
        '2024.09.05', '2024.09.02', '2024.08.01', '2024.07.18', '2024.07.17',  
        '2024.07.07', '2024.07.07', '2024.06.15', '2024.06.13', '2024.06.07', 
        
        '2024.05.31', '2024.05.24', '2024.05.02', '2024.04.13', '2024.03.21', 
        '2024.03.09', '2024.02.15', '2024.02.02', '2024.01.12', '2024.01.01', 
        
        '2023.12.25', '2023.12.24', '2023.12.22', '2023.12.14', '2023.12.12', 
        '2023.12.08', '2023.12.04', '2023.11.17', '2023.11.09', '2023.10.06',
        
        '2023.09.28', '2023.09.21', '2023.09.21', '2023.09.20', 
        
        # 돌석
        '2024.10.01', '2024.09.17', '2024.08.20', '2024.08.13', '2024.08.10', '2024.08.06', 
        '2024.07.30', '2024.07.23', '2024.07.09', '2024.07.09', '2024.07.02', 
        '2024.06.26', '2024.06.25', 
        
        # 라군
        '2024.05.20', '2024.01.26', '2023.12.28', '2023.12.03', '2023.09.29', 
        
        # 윤성
        '2024.05.25', '2024.01.25', '2023.10.08', '2023.10.02'
    ],
    '게시글 내용': [
        '작품 그림', '10000', '작품 그림', '기타', '작품 그림',   
        '작품 그림', '작품 그림', '기타', '작품 그림', '기타',  
        
        '기타', '작품 그림', '작품 그림', '일상 사진', '일상 사진',
        '일상 사진', '일상 사진', '작품 그림', '일상 사진', '작품 그림',
        
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림', 
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        
        '작품 그림', '작품 그림', '작품 그림',  '작품 그림', 
        # 돌석
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '1000', 
        '작품 그림', '작품 그림', '작품 그림', '일상 사진', '작품 그림',
        '작품 그림', '작품 그림',  '작품 그림', 
      
       # 라군
        '작품 그림',  '작품 그림', '작품 그림', '작품 그림',  '기타',
        # 윤성
         '1000', '작품 그림', '일상 사진', '일상 사진'
    ]
}
 
 
 
# 데이터 리스트 # '작가명' : '김태경'
hdf = [
    {"게시일": "2024.10.08", "게시글 내용": "작품 그림"}, {"게시일": "2024.10.02", "게시글 내용": "작품 그림"},{"게시일": "2024.09.26", "게시글 내용": "10000"}, {"게시일": "2024.09.24", "게시글 내용": "작품 그림"}, {"게시일": "2024.09.17", "게시글 내용": "작품 그림"},{"게시일": "2024.09.10", "게시글 내용": "작품 그림"}, {"게시일": "2024.09.03", "게시글 내용": "작품 그림"}, {"게시일": "2024.08.27", "게시글 내용": "작품 그림"}, {"게시일": "2024.08.20", "게시글 내용": "작품 그림"},  {"게시일": "2024.08.13", "게시글 내용": "작품 그림"},{"게시일": "2024.08.06", "게시글 내용": "작품 그림"},  {"게시일": "2024.08.06", "게시글 내용": "5000"},{"게시일": "2024.07.30", "게시글 내용": "작품 그림"},  {"게시일": "2024.07.24", "게시글 내용": "작품 그림"},  {"게시일": "2024.06.18", "게시글 내용": "작품 그림"}, {"게시일": "2024.04.23", "게시글 내용": "작품 그림"}, {"게시일": "2024.04.10", "게시글 내용": "작품 그림"}, {"게시일": "2024.03.31", "게시글 내용": "작품 그림"}, {"게시일": "2024.03.26", "게시글 내용": "작품 그림"}, {"게시일": "2024.03.19", "게시글 내용": "작품 그림"},{"게시일": "2024.03.12", "게시글 내용": "작품 그림"},{"게시일": "2024.02.27", "게시글 내용": "작품 그림"}, {"게시일": "2024.02.20", "게시글 내용": "작품 그림"}, {"게시일": "2024.02.13", "게시글 내용": "작품 그림"},
]
hdf = pd.DataFrame(hdf)
hdf['작가명'] =  '김태경'

# 데이터 정의
data_is = {
    '작가명': ['잇선'] * 37 + ['이담'] * 9,
    '게시일': ['2024.10.17', '2024.10.04', '2024.10.01', '2024.09.26', '2024.09.23', 
             '2024.07.10', '2024.06.23', '2024.06.19', '2024.06.13', '2024.06.04',

             '2024.05.25', '2024.05.19', '2024.05.13', '2024.05.09', '2024.05.07', 
             '2024.05.01', '2024.05.01', '2024.04.25', '2024.04.17', '2024.04.06',

             '2024.04.04', '2024.04.01', '2024.03.26', '2024.03.20', '2024.03.13', 
             '2024.03.11', '2024.03.04', '2024.03.03', '2024.03.01', '2024.02.26',

             '2024.02.25', '2024.02.25', '2024.02.21', '2024.02.02', '2024.01.25', 
              '2024.01.15','2024.01.08', 

              '2024.07.30', '2024.07.21', '2024.06.09',   '2024.05.19', '2024.05.17', 
              '2024.05.17', '2024.02.09', '2023.10.26', '2023.09.13'],
              
    '게시글 내용': ['기타', '작품 그림', '작품 그림', '작품 그림', '기타', 
                 '기타', '기타', '기타', '작품 그림', '기타', 
                 '작품 그림',  '기타', '기타', '5000', '작품 그림', 
                 '작품 그림', '일상 사진', '작품 그림', '작품 그림', '작품 그림', 
                 '작품 그림',  '작품 그림', '기타','작품 그림','작품 그림', 
                 '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림', 
                 '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
                 '작품 그림', '작품 그림', 
                   
                   '30000', '기타', '기타', '작품 그림', '기타', 
                   '기타', '작품 그림', '작품 그림', '작품 그림']
}

 
 
data_gi = {
    '작가명':  ['히디'] * 16 + ['구나'] * 26,
    '게시일': [  '2024.10.23', '2024.09.24', '2024.09.20', '2024.09.18',  '2024.09.13', 
               '2024.09.11', '2024.06.12', '2024.06.12',  '2024.05.21', '2024.05.08',
               '2024.04.23', '2024.04.10',  '2024.04.01', '2024.03.26', '2024.03.20', 
               '2024.03.20',    
       
        # 구나
        '2024.09.23', '2024.08.20', '2024.08.18', '2024.08.15',  '2024.08.14', '2024.08.11', '2024.08.03', '2024.06.23', '2024.05.26', '2024.05.08', '2024.05.05', '2024.04.29',  '2024.03.31', '2024.03.27', '2024.03.01', '2024.02.27',  '2024.02.14', '2024.02.06', '2024.01.30', '2023.12.31', '2023.12.25', '2023.11.27', '2023.11.20', '2023.11.14',  '2023.11.05', '2023.10.23'
    ],
    '게시글 내용': [  '작품 그림', '일상 사진', '일상 사진', '일상 사진',  '일상 사진', '일상 사진', '10000', '일상 사진',  '일상 사진', '일상 사진', '일상 사진', '일상 사진',  '작품 그림', '일상 사진', '작품 그림', '작품 그림',
  '기타', '기타', '일상 사진', '작품 그림', '일상 사진', '10000', '작품 그림', '작품 그림',  '작품 그림', '작품 그림', '일상 사진', '일상 사진',  '기타', '일상 사진', '작품 그림', '일상 사진',  '기타', '일상 사진', '작품 그림', '작품 그림',  '일상 사진', '일상 사진', '일상 사진', '일상 사진', '일상 사진', '일상 사진'
    ]
}

 
   

 
######## ######## ######## ######## ######## ######## ######## ########
 

# 데이터를 딕셔너리 형태로 정의합니다.
data_mr = {
    '작가명': ['명랑'] * 44,  # '명랑' 작가명 반복
    '게시일': [
        '2024.11.01', '2024.10.03', '2024.08.09', '2024.06.26', '2024.06.13',
        '2024.05.26', '2024.05.26', '2024.05.08', '2024.05.01', '2024.04.08',

        '2024.04.06', '2024.04.01', '2024.03.22', '2024.03.06', '2024.03.05',
        '2024.03.03', '2024.02.22', '2024.02.22', '2024.02.17', '2024.02.11',
        
        '2024.02.09', '2024.01.10', '2024.01.03', '2023.12.30', '2023.12.28',
        '2023.12.25', '2023.12.07', '2023.11.30', '2023.11.22', '2023.11.16',

        '2023.11.08', '2023.10.25', '2023.10.20', '2023.10.17', '2023.10.12',
        '2023.10.06', '2023.10.05', '2023.09.28', '2023.09.27', '2023.09.21',
        '2023.09.21', '2023.09.17', '2023.09.15', '2023.09.15'
    ],
    '게시글 내용': [
        '일상 사진', '작품 그림', '5000', '일상 사진', '일상 사진',
        '일상 사진', '작품 그림', '일상 사진', '일상 사진', '기타',

        '작품 그림', '작품 그림', '일상 사진', '기타', '작품 그림',
        '일상 사진', '일상 사진', '일상 사진', '기타', '기타',

        '일상 사진', '일상 사진', '작품 그림', '일상 사진', '작품 그림',
        '일상 사진', '작품 그림', '작품 그림','일상 사진', '일상 사진',

        '일상 사진', '일상 사진',  '일상 사진', '작품 그림','작품 그림', 
        '일상 사진', '작품 그림', '작품 그림', '작품 그림', '작품 그림',

        '작품 그림', '일상 사진',  '작품 그림', '일상 사진'
    ]
}
 



# 데이터 정의
data_lim = {
    '작가명': ['임형'] * 31,  # 작가명이 반복됨
    '게시일': [
        '2024-11-01', '2024-10-18', '2024-09-27', '2024-09-16', '2024-09-01',
        '2024-08-26', '2024-08-18', '2024-08-16', '2024-08-16', '2024-08-15',

        '2024-08-10', '2024-08-07', '2024-08-03', '2024-07-23', '2024-07-10',
        '2024-07-06', '2024-06-29', '2024-06-18', '2024-06-15', '2024-06-13',

        '2024-06-13', '2024-06-11', '2024-06-07', '2024-06-01', '2024-05-24',
        '2024-05-24', '2024-05-22', '2024-05-21', '2024-05-18', '2024-05-17',
        '2024-05-17'
    ],
    '게시글 내용': [
        '10000', '일상 사진', '작품 그림', '작품 그림', '작품 그림',
        '일상 사진', '작품 그림', '5000', '일상 사진', '일상 사진',

        '작품 그림', '일상 사진', '작품 그림', '작품 그림', '일상 사진',
        '작품 그림', '작품 그림', '일상 사진', '작품 그림', '작품 그림',

        '일상 사진', '기타', '일상 사진', '일상 사진','작품 그림',
         '작품 그림', '1000', '일상 사진', '작품 그림','작품 그림',
         '일상 사진'
    ]
}
 
# 작가 정연 데이터
data_jungyeon = [ {"작가명": "정연", "게시일": "2024.10.22", "게시글 내용": "작품 그림"}, {"작가명": "정연", "게시일": "2024.10.08", "게시글 내용": "작품 그림"}, {"작가명": "정연", "게시일": "2024.07.09", "게시글 내용": "20000"}, {"작가명": "정연", "게시일": "2024.04.17", "게시글 내용": "작품 그림"}, {"작가명": "정연", "게시일": "2024.01.16", "게시글 내용": "작품 그림"}, {"작가명": "정연", "게시일": "2024.01.16", "게시글 내용": "작품 그림"}, {"작가명": "정연", "게시일": "2023.12.19", "게시글 내용": "작품 그림"},
]

# 작가 자까 데이터
data_jakka = [
    {"작가명": "자까", "게시일": "2024.09.19", "게시글 내용": "70000"}, {"작가명": "자까", "게시일": "2024.08.26", "게시글 내용": "작품 그림"}, {"작가명": "자까", "게시일": "2024.08.19", "게시글 내용": "일상 사진"}, {"작가명": "자까", "게시일": "2024.08.07", "게시글 내용": "60000"}, {"작가명": "자까", "게시일": "2024.07.13", "게시글 내용": "작품 그림"}, {"작가명": "자까", "게시일": "2024.06.08", "게시글 내용": "50000"}, {"작가명": "자까", "게시일": "2024.05.04", "게시글 내용": "작품 그림"}, {"작가명": "자까", "게시일": "2023.12.31", "게시글 내용": "작품 그림"}, {"작가명": "자까", "게시일": "2023.11.22", "게시글 내용": "기타"},{"작가명": "자까", "게시일": "2023.11.07", "게시글 내용": "작품 그림"}, {"작가명": "자까", "게시일": "2023.10.11", "게시글 내용": "일상 사진 얘네들도!"},
]

# 두 작가의 데이터를 결합
data_combined = data_jungyeon + data_jakka
 

# 작가 쌉초 데이터
data_sappcho = [ {"작가명": "쌉초", "게시일": "2024.09.13", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.10.18", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.10.13", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.09.28", "게시글 내용": "작품 그림"},  {"작가명": "쌉초", "게시일": "2024.09.28", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.09.18", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.09.14", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.09.12", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.09.01", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.08.30", "게시글 내용": "일상 사진"},{"작가명": "쌉초", "게시일": "2024.08.24", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.08.24", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.08.22", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.08.21", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.08.20", "게시글 내용": "작품 그림"},{"작가명": "쌉초", "게시일": "2024.08.14", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.08.02", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.07.23", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.07.18", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.07.12", "게시글 내용": "작품 그림"},{"작가명": "쌉초", "게시일": "2024.07.03", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.07.03", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.06.26", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.06.25", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.06.25", "게시글 내용": "기타"}, {"작가명": "쌉초", "게시일": "2024.06.21", "게시글 내용": "작품 그림"},  {"작가명": "쌉초", "게시일": "2024.05.25", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.05.22", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.05.05", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.04.23", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.04.23", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.04.16", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.04.11", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.04.09", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.03.31", "게시글 내용": "기타"},{"작가명": "쌉초", "게시일": "2024.03.29", "게시글 내용": "작품 그림"},{"작가명": "쌉초", "게시일": "2024.03.27", "게시글 내용": "일상 사진"},{"작가명": "쌉초", "게시일": "2024.03.26", "게시글 내용": "일상 사진"}, {"작가명": "쌉초", "게시일": "2024.03.14", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.02.14", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.02.09", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2024.01.06", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2023.12.24", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2023.10.24", "게시글 내용": "작품 그림"}, {"작가명": "쌉초", "게시일": "2023.10.22", "게시글 내용": "작품 그림"},
]
 
data_sss = {
    '작가명': ['박씨', '박씨', '박씨', '박씨', '오성대', '오성대', '오성대', '오성대', '오성대', '오성대', '오성대', '오성대', '구아진', '구아진', '구아진', '구아진', '구아진', '구아진', '구아진', '구아진', '구아진', '구아진',  '스프링', '스프링', '모죠', '모죠', '모죠', '모죠', '모죠', '모죠', '지발', '지발', '지발', '지발', '지발', '지발', 
               '최다킬', '범배', '손하기', '허새보', '포스스튜디오', '박태준', '모랑지'],
    '게시일': ['2024.07.26', '2024.06.12', '2024.05.29', '2024.05.14', '2024.09.29', '2024.09.16', '2024.08.24',   '2024.08.24', '2024.08.20', '2024.05.10', '2024.04.21', '2024.04.09', '2024.10.22', '2024.09.26', '2024.09.07',  '2024.08.28', '2024.08.08', '2024.08.05', '2024.06.06', '2024.04.16', '2024.03.19', '2024.02.29',  '2024.06.25', '2024.03.31', '2024.09.17', '2024.08.19', '2024.08.13', '2024.04.23', '2024.04.22', '2024.02.14',  '2024.09.26', '2024.09.26', '2024.09.07', '2024.08.22', '2024.07.23', '2024.07.18', 
               '2024.08.05', '2024.08.21', '2024.08.25', '2024.09.14', '2024.04.10', '2024.07.24', '2024.09.25'],
    '게시물_내용': ['1000', '기타', '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림', '5000', '작품 그림', '일상 사진', '일상 사진', '작품 그림', '작품 그림', '일상 사진', '작품 그림', '5000', '작품 그림', '기타', '작품 그림', '작품 그림', '기타', '1000', '일상 사진', '작품 그림', '70000', '기타', '60000', 
                   '기타', '기타', '작품 그림', '일상 사진', '일상 사진', '작품 그림', '작품 그림', '작품 그림',  '작품 그림', '작품 그림', '작품 그림', '일상 사진', '작품 그림', '작품 그림', '20000']
}



# 데이터 정의
data_abc = {
    '작가명': ['고추참치', '고추참치', '고추참치', '고추참치', '고추참치', '고추참치',
             '상금', '상금', '상금', '상금', '상금'],
    '게시일': ['2024.10.08', '2024.09.03', '2024.08.06', '2023.11.29', '2023.09.21', '2023.09.21',
              '2024.08.19', '2024.07.25', '2024.07.14', '2024.07.02', '2023.09.14'],
    '게시글 내용': ['작품 그림', '5000', '작품 그림', '기타', '작품 그림', '작품 그림',
                 '기타', '1000', '일상 사진', '일상 사진', '작품 그림']
}
 



 
# 데이터 정의
data_jo = {
    '작가명': ['혀노'] * 15 + ['HO9'] * 1 + ['조용석'] * 8,
    '게시일': ['2024.09.24', '2024.09.17', '2024.09.11', '2024.09.06', '2024.08.10', '2024.07.28', '2024.05.25', '2024.05.13', '2024.05.07', '2024.04.12','2024.04.01', '2024.03.16', '2024.02.16', '2024.02.12', '2024.01.20','2024.08.06', '2024.06.26', '2024.01.05', '2023.11.09', '2023.10.16', '2023.10.06', '2023.09.17', '2023.09.17', '2023.09.14'],
    '게시글 내용': ['작품 그림', '작품 그림', '기타', '기타', '작품 그림','30000', '작품 그림', '작품 그림', '작품 그림', '20000',
                 '작품 그림', '작품 그림', '작품 그림', '작품 그림', '기타', '5000', '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림', '일상 사진', '작품 그림']
}
 


# 데이터 리스트 생성
data_pks = [
    ["박만사", "2024.09.27", "50000"],
    ["박만사", "2024.09.15", "작품 그림"],
    ["박만사", "2024.09.10", "작품 그림"],
    ["박만사", "2024.07.31", "40000"],
    ["박만사", "2024.07.19", "작품 그림"],
    ["박만사", "2024.05.02", "작품 그림"],
    ["박만사", "2024.04.03", "작품 그림"],
    ["박만사", "2024.04.01", "작품 그림"],
    ["박만사", "2024.03.31", "작품 그림"],
    ["박만사", "2024.03.31", "작품 그림"],
    ["박만사", "2024.03.30", "작품 그림"],
    ["박만사", "2024.03.29", "작품 그림"],
    ["박만사", "2024.03.28", "작품 그림"],
    ["박만사", "2024.03.27", "작품 그림"],
    ["박만사", "2024.03.27", "기타"],
    ["박만사", "2024.03.26", "작품 그림"],
    ["박만사", "2024.03.24", "작품 그림"],
    ["박만사", "2024.03.23", "기타"],
    ["박만사", "2024.03.22", "작품 그림"],
    ["박만사", "2024.03.21", "작품 그림"],
    ["박만사", "2024.03.20", "작품 그림"],
    ["박만사", "2024.03.19", "작품 그림"],
    ["박만사", "2024.03.19", "작품 그림"],
    ["박만사", "2024.03.18", "작품 그림"],
    ["박만사", "2024.03.17", "작품 그림"],
    ["박만사", "2024.03.16", "작품 그림"],
    ["박만사", "2024.03.15", "작품 그림"],
    ["박만사", "2024.03.14", "작품 그림"],
    ["박만사", "2024.03.13", "작품 그림"],
    ["박만사", "2024.03.12", "작품 그림"],
    ["박만사", "2024.03.11", "작품 그림"],
    ["박만사", "2024.03.09", "작품 그림"],
    ["박만사", "2024.03.09", "기타"],
    ["박만사", "2024.03.08", "기타"],
    ["박만사", "2024.03.08", "작품 그림"],
    ["박만사", "2024.03.06", "작품 그림"],
    ["박만사", "2024.03.06", "작품 그림"],
    ["박만사", "2024.03.05", "작품 그림"],
    ["박만사", "2024.03.04", "작품 그림"],
    ["박만사", "2024.03.03", "작품 그림"],
    ["박만사", "2024.03.02", "작품 그림"],
    ["박만사", "2024.03.01", "작품 그림"],
    ["박만사", "2024.02.29", "작품 그림"],
    ["박만사", "2024.02.28", "작품 그림"],
    ["박만사", "2024.02.27", "작품 그림"],
    ["박만사", "2024.02.25", "기타"],
    ["박만사", "2024.02.25", "작품 그림"],
    ["박만사", "2024.02.24", "작품 그림"],
    ["박만사", "2024.02.23", "작품 그림"],
    ["박만사", "2024.02.22", "작품 그림"]
]

# 데이터 프레임 생성
data_pks = pd.DataFrame(data_pks, columns=['작가명', '게시일', '게시글 내용'])


 
# 데이터 리스트 생성
data_nam = [
    ["남자의 이야기", "2024.10.24", "작품 그림"],
    ["남자의 이야기", "2024.09.19", "작품 그림"],
    ["남자의 이야기", "2024.09.05", "작품 그림"],
    ["남자의 이야기", "2024.08.03", "작품 그림"],
    ["남자의 이야기", "2024.07.16", "작품 그림"],
    ["남자의 이야기", "2024.03.29", "기타"],
    ["남자의 이야기", "2024.03.29", "작품 그림"],
    ["남자의 이야기", "2024.02.26", "작품 그림"],
    ["남자의 이야기", "2024.01.19", "작품 그림"],
    ["남자의 이야기", "2024.01.17", "작품 그림"],
    ["남자의 이야기", "2024.01.06", "작품 그림"],
    ["남자의 이야기", "2024.01.04", "작품 그림"],
    ["남자의 이야기", "2023.12.29", "작품 그림"],
    ["남자의 이야기", "2023.12.28", "작품 그림"],
    ["남자의 이야기", "2023.12.22", "작품 그림"],
    ["남자의 이야기", "2023.12.20", "작품 그림"],
    ["남자의 이야기", "2023.12.16", "작품 그림"],
    ["남자의 이야기", "2023.12.06", "작품 그림"],
    ["남자의 이야기", "2023.11.29", "작품 그림"],
    ["남자의 이야기", "2023.11.17", "작품 그림"],
    ["남자의 이야기", "2023.11.16", "작품 그림"],
    ["남자의 이야기", "2023.11.11", "작품 그림"],
    ["남자의 이야기", "2023.11.08", "작품 그림"],
    ["남자의 이야기", "2023.10.27", "작품 그림"],
    ["남자의 이야기", "2023.10.25", "작품 그림"],
    ["남자의 이야기", "2023.10.20", "작품 그림"],
    ["남자의 이야기", "2023.10.18", "작품 그림"],
    ["남자의 이야기", "2023.10.13", "작품 그림"],
    ["남자의 이야기", "2023.10.11", "작품 그림"],
    ["남자의 이야기", "2023.09.27", "작품 그림"],
    ["남자의 이야기", "2023.09.22", "작품 그림"],
    ["남자의 이야기", "2023.09.20", "작품 그림"],
    
    ["한가람", "2024.04.09", "10000"],
    
    ["펀치킥", "2024.09.28", "작품 그림"],
    ["펀치킥", "2024.09.25", "5000"],
    ["펀치킥", "2024.09.10", "작품 그림"],
    ["펀치킥", "2024.05.04", "작품 그림"],
    ["펀치킥", "2024.05.01", "작품 그림"],
    ["펀치킥", "2024.02.28", "작품 그림"],
    ["펀치킥", "2024.02.07", "작품 그림"],
    ["펀치킥", "2024.01.31", "작품 그림"],
    ["펀치킥", "2024.01.21", "작품 그림"],
    ["펀치킥", "2024.01.19", "작품 그림"],
    ["펀치킥", "2023.12.26", "작품 그림"],
    ["펀치킥", "2023.12.21", "작품 그림"],
    ["펀치킥", "2023.12.19", "작품 그림"],
    ["펀치킥", "2023.11.28", "작품 그림"],
    ["펀치킥", "2023.11.21", "작품 그림"],
    ["펀치킥", "2023.11.15", "작품 그림"],
    ["펀치킥", "2023.11.07", "작품 그림"],
    ["펀치킥", "2023.11.01", "작품 그림"],
    ["펀치킥", "2023.10.24", "작품 그림"]
]

# 데이터 프레임 생성
data_nam = pd.DataFrame(data_nam, columns=['작가명', '게시일', '게시글 내용'])
 
# 데이터 리스트 생성
data_jna = [
    ["제나", "2024.09.10", "기타"],
    ["제나", "2024.07.26", "기타"],
    ["제나", "2024.07.26", "기타"],
    ["제나", "2024.07.25", "작품 그림"],
    ["제나", "2024.07.25", "작품 그림"],
    ["제나", "2024.07.25", "작품 그림"],
    ["제나", "2024.07.25", "작품 그림"],
    ["제나", "2024.06.27", "작품 그림"],
    ["제나", "2024.05.28", "10000"],
    ["제나", "2023.11.29", "기타"],
    ["제나", "2023.11.24", "기타"],
    ["제나", "2023.10.31", "작품 그림"],
    ["제나", "2023.09.27", "기타"],
    ["제나", "2023.09.27", "작품 그림"],
    
    ["태완", "2024.08.06", "5000"],
    
    ["유누니", "2024.04.07", "5000"],
    
    ["박진환", "2024.10.08", "작품 그림"],
    ["박진환", "2024.10.08", "10000"],
    ["박진환", "2024.09.16", "작품 그림"],
    ["박진환", "2024.08.04", "5000"],
    ["박진환", "2023.11.13", "작품 그림"],
    ["박진환", "2023.09.26", "작품 그림"],
    
    ["JP", "2024.10.17", "10000"],
    ["JP", "2024.09.26", "기타"],
    ["JP", "2024.09.17", "5000"],
    ["JP", "2024.08.12", "1000"],
    
    ["부겸", "2024.08.12", "1000"],
    
    ["배민기", "2024.10.02", "일상 사진"],
    ["배민기", "2024.09.27", "작품 그림"],
    ["배민기", "2024.09.19", "작품 그림"],
    ["배민기", "2024.06.24", "작품 그림"],
    ["배민기", "2024.01.30", "일상 사진"],
    ["배민기", "2024.01.11", "기타"],
    ["배민기", "2023.11.09", "기타"],
    ["배민기", "2023.11.08", "일상 사진"],
    ["배민기", "2023.09.28", "작품 그림"],
    ["배민기", "2023.09.21", "작품 그림"],
    ["배민기", "2023.09.19", "작품 그림"],
    ["배민기", "2023.09.18", "기타"]
]

# 데이터 프레임 생성
data_jna = pd.DataFrame(data_jna, columns=['작가명', '게시일', '게시글 내용'])

# 데이터 리스트 생성
data_si = [
    ["운", "2024.10.16", "기타"],  ["운", "2024.08.31", "작품 그림"], ["운", "2024.06.24", "기타"], ["운", "2024.04.13", "기타"],["운", "2024.02.15", "일상 사진"], ["운", "2024.01.11", "기타"], ["운", "2023.12.28", "작품 사진"], ["운", "2023.12.02", "일상 사진"], ["운", "2023.11.09", "기타"], ["운", "2023.10.04", "일상 사진"],
    
    ["시바견", "2024.07.01", "작품 그림"], ["시바견", "2024.06.16", "일상 사진"],["시바견", "2024.06.16", "일상 사진"], ["시바견", "2024.06.02", "일상 사진"], ["시바견", "2024.05.27", "일상 사진"], ["시바견", "2024.05.22", "일상 사진"], ["시바견", "2024.05.20", "작품 그림"],["시바견", "2024.05.05", "작품 그림"], ["시바견", "2024.05.05", "일상 사진"],
    ["시바견", "2024.04.22", "일상 사진"], ["시바견", "2024.04.16", "작품 그림"], ["시바견", "2024.04.16", "일상 사진"], ["시바견", "2024.04.01", "일상 사진"], ["시바견", "2024.04.01", "일상 사진"], ["시바견", "2024.03.27", "일상 사진"], ["시바견", "2024.03.20", "일상 사진"], ["시바견", "2024.03.19", "일상 사진"], ["시바견", "2024.03.18", "일상 사진"], ["시바견", "2024.03.10", "작품 그림"], ["시바견", "2024.03.10", "일상 사진"], ["시바견", "2024.03.10", "일상 사진"], ["시바견", "2024.02.26", "일상 사진"],["시바견", "2024.02.26", "일상 사진"], ["시바견", "2024.02.25", "작품 그림"], ["시바견", "2024.02.25", "일상 사진"], ["시바견", "2024.02.25", "일상 사진"], ["시바견", "2024.02.12", "일상 사진"],["시바견", "2024.02.11", "일상 사진"], ["시바견", "2024.02.11", "일상 사진"], ["시바견", "2024.02.03", "일상 사진"], ["시바견", "2024.01.30", "작품 그림"], ["시바견", "2024.01.10", "작품 그림"],["시바견", "2023.12.21", "일상 사진"], ["시바견", "2023.12.21", "작품 그림"],["시바견", "2023.12.20", "일상 사진"],
    
    ["강견", "2024.10.05", "기타"], ["강견", "2024.09.17", "일상 사진"], ["강견", "2024.09.14", "작품 그림"],  ["강견", "2024.08.31", "작품 그림"],["강견", "2024.08.17", "일상 사진"], ["강견", "2024.06.26", "기타"],["강견", "2024.06.15", "일상 사진"], ["강견", "2024.05.22", "작품 그림"],["강견", "2024.04.06", "일상 사진"],
    ["강견", "2024.04.01", "기타"], ["강견", "2024.03.17", "기타"], ["강견", "2024.03.09", "일상 사진"], ["강견", "2024.02.20", "일상 사진"], ["강견", "2024.02.10", "작품 그림"],["강견", "2023.12.24", "일상 사진"], ["강견", "2023.12.02", "일상 사진"],["강견", "2023.11.28", "기타"],
]

# 데이터 프레임 생성
data_si = pd.DataFrame(data_si, columns=['작가명', '게시일', '게시글 내용'])
 
 
# 하일권 작가의 데이터
data_hailgwon = {
    '작가명': ['하일권'] * 31,  # '하일권' 작가명 반복
    '게시일': [
        '2024.10.27', '2024.10.20', '2024.10.13', '2024.10.06', '2024.09.21',
        '2024.09.15', '2024.09.08', '2024.08.24', '2024.08.18', '2024.08.17',
        '2024.07.28', '2024.07.14', '2024.06.30', '2024.06.23', '2024.06.09',
        '2024.05.25', '2024.05.18', '2024.05.12', '2024.05.05', '2024.04.27',
        '2024.04.20', '2024.04.13', '2024.04.06', '2024.03.23', '2024.03.16',
        '2024.03.09', '2024.03.03', '2024.02.24', '2024.02.17', '2024.01.05',
        '2023.09.18'
    ],
    '게시글 내용': [
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '10000', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림',   '일상 사진',
        '작품 그림'
    ]
}

 
# 이대한 작가의 데이터
data_idaean = {
    '작가명': ['이대한'] * 4,  # '이대한' 작가명 반복
    '게시일': [
        '2024.09.16', '2024.08.11', '2024.05.20', '2024.04.26'
    ],
    '게시글 내용': [
        '작품 그림', '작품 그림', '작품 그림', '1000'
    ]
}

# 두 데이터프레임을 생성합니다.
df_hailgwon = pd.DataFrame(data_hailgwon)
df_idaean = pd.DataFrame(data_idaean)

# 두 데이터프레임을 합칩니다.
df_combined_2 = pd.concat([df_hailgwon, df_idaean], ignore_index=True)

 
# 황양 작가의 데이터
data_hwangyang = {
    '작가명': ['황양'] * 14,  # '황양' 작가명 반복
    '게시일': [
        '2024.11.02', '2024.10.04', '2024.09.26', '2024.07.21', '2024.07.15',
        '2024.07.08', '2024.06.27', '2024.05.31', '2024.05.13', '2024.05.03',
        '2024.04.18', '2024.04.01', '2024.03.17', '2024.03.05'
    ],
    '게시글 내용': [
        '작품 그림', '일상 사진', '일상 사진', '작품 그림', '기타',
        '작품 그림', '작품 그림', '기타', '기타', '1000',
        '작품 그림', '일상 사진', '기타', '기타'
    ]
}

# 득7이 작가의 데이터
data_deuk7i = {
    '작가명': ['득7이'] * 4,  # '득7이' 작가명 반복
    '게시일': [
        '2024.08.07', '2024.08.02', '2024.07.25', '2024.06.11'
    ],
    '게시글 내용': [
        '1000', '작품 그림', '기타', '작품 그림'
    ]
}

# 이솔 작가의 데이터
data_isol = {
    '작가명': ['이솔'] * 9,  # '이솔' 작가명 반복
    '게시일': [
        '2024.11.01', '2024.09.20', '2024.09.12', '2024.09.07', '2024.09.02',
        '2024.08.20', '2024.07.10', '2024.07.09', '2024.07.08'
    ],
    '게시글 내용': [
        '작품 그림', '기타', '기타', '5000', '일상 사진',
        '작품 그림', '1000', '작품 그림', '작품 그림'
    ]
}





# 꼬모소이 작가의 데이터
data_kkomosoi = {
    '작가명': ['꼬모소이'] * 4,  # '꼬모소이' 작가명 반복
    '게시일': [
        '2024.09.12', '2024.08.14', '2024.07.10', '2024.06.20'
    ],
    '게시글 내용': [
        '기타', '일상 사진', '작품 그림', '1000'
    ]
}

# 각 작가의 데이터프레임을 생성합니다.
df_hwangyang = pd.DataFrame(data_hwangyang)
df_deuk7i = pd.DataFrame(data_deuk7i)
df_isol = pd.DataFrame(data_isol)
df_kkomosoi = pd.DataFrame(data_kkomosoi)

# 모든 데이터프레임을 합칩니다.
df_combined3 = pd.concat([df_hwangyang, df_deuk7i, df_isol, df_kkomosoi], ignore_index=True)
 

# 켄타 작가의 데이터
data_kenta = {
    '작가명': ['켄타'] * 7,  # '켄타' 작가명 반복
    '게시일': [
        '2024.09.13', '2024.07.19', '2024.04.01', '2023.12.30', '2023.12.22',
        '2023.11.19', '2023.11.10'
    ],
    '게시글 내용': [
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림'
    ]
}

# 김대영 작가의 데이터
data_kimdaeyoung = {
    '작가명': ['김대영'] * 3,  # '김대영' 작가명 반복
    '게시일': [
        '2024.10.29', '2024.08.03', '2023.10.23'
    ],
    '게시글 내용': [
        '1000', '일상 사진', '일상 사진'
    ]
}

# 이동건 작가의 데이터
data_leedonggun = {
    '작가명': ['이동건'] * 22,  # '이동건' 작가명 반복
    '게시일': [
        '2024.09.03', '2024.08.22', '2024.08.15', '2024.05.17', '2024.05.17',
        '2024.05.14', '2024.05.09', '2024.03.01', '2024.02.08', '2023.12.29',
        '2023.12.16', '2023.10.06', '2023.10.04', '2023.10.02', '2023.09.29',
        '2023.09.22', '2023.09.20', '2023.09.18', '2023.09.18', '2023.09.15',
        '2023.09.13', '2023.09.13'
    ],
    '게시글 내용': [
        '작품 그림', '40000', '기타', '기타', '기타', '작품 그림', '기타', '작품 그림', '작품 그림', '작품 그림', 
        '작품 그림', '작품 그림',  '작품 그림','일상 사진', '기타', '일상 사진','일상 사진', '작품 그림', '작품 그림', '작품 그림',
         '일상 사진', '일상 사진'
    ]
}

  
# 승우 작가의 데이터
data_seungwoo = {
    '작가명': ['승우'] * 7,  # '승우' 작가명 반복
    '게시일': [
        '2024.09.28', '2024.07.15', '2024.05.23', '2024.03.31', '2024.02.21',
        '2023.11.14', '2023.10.04'
    ],
    '게시글 내용': [
        '기타', '20000', '기타', '기타', '기타', '기타', '작품 그림'
    ]
}

# 수박양 작가의 데이터
data_subakyang = {
    '작가명': ['수박양'] * 8,  # '수박양' 작가명 반복
    '게시일': [
        '2024.10.08', '2024.05.09', '2024.04.01', '2024.02.16', '2024.01.06',
        '2023.12.29', '2023.10.05', '2023.09.16'
    ],
    '게시글 내용': [
        '20000', '일상 사진', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '일상 사진', '작품 그림'
    ]
}

# 스튜디오MW 작가의 데이터
data_studiomw = {
    '작가명': ['스튜디오MW'] * 25,  # '스튜디오MW' 작가명 반복
    '게시일': [
        '2024.10.05', '2024.10.05', '2024.10.04', '2024.10.02', '2024.09.30',
        '2024.09.15', '2024.09.14', '2024.09.13', '2024.09.12', '2024.08.11',
        '2024.08.10', '2024.07.31', '2024.07.28', '2024.07.27', '2024.06.01',
        '2024.05.31', '2024.04.07', '2024.04.01', '2024.03.21', '2024.03.13',
        '2024.03.02', '2024.03.01', '2024.02.28', '2024.02.26', '2024.02.08'
    ],
    '게시글 내용': [
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '5000', '기타', '기타', '기타', '기타', '작품 그림',
        '작품 그림', '1000', '작품 그림', '기타', '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림' 
    ]
}
 

# 각 작가의 데이터프레임을 생성합니다.
df_kenta = pd.DataFrame(data_kenta)
df_kimdaeyoung = pd.DataFrame(data_kimdaeyoung)
df_leedonggun = pd.DataFrame(data_leedonggun)
df_seungwoo = pd.DataFrame(data_seungwoo)
df_subakyang = pd.DataFrame(data_subakyang)
df_studiomw = pd.DataFrame(data_studiomw)

# 모든 데이터프레임을 합칩니다.
df_combined5 = pd.concat([df_kenta, df_kimdaeyoung, df_leedonggun, df_seungwoo, df_subakyang, df_studiomw], ignore_index=True)


# 데이터 정의
data_jpl= {
    '작가명': ['지페리'] * 50,  # 작가명이 반복됨
    '게시일': [
        '2024-10-25', '2024-09-13', '2024-08-23', '2024-07-12', '2024-07-05',
        '2024-06-07', '2024-05-26', '2024-05-24', '2024-05-17', '2024-04-26',
        '2024-04-19', '2024-04-05', '2024-03-31', '2024-03-30', '2024-03-23',
        '2024-03-15', '2024-03-10', '2024-03-08', '2024-03-01', '2024-02-29',
        '2024-02-23', '2024-02-19', '2024-02-09', '2024-01-20', '2024-01-06',
        '2023-12-30', '2023-12-23', '2023-12-16', '2023-12-08', '2023-11-15',
        '2023-11-08', '2023-11-01', '2023-10-30', '2023-10-15', '2023-10-14',
        '2023-10-08', '2023-10-07', '2023-10-06', '2023-10-06', '2023-10-06',
        '2023-09-30', '2023-09-29', '2023-09-28', '2023-09-25', '2023-09-23',
        '2023-09-22', '2023-09-15', '2023-09-14', '2023-09-14', '2023-09-13'
    ],
    '게시글 내용': [
        '작품 그림', '작품 그림', '작품 그림', '일상 사진', '작품 그림',
        '일상 사진', '20000', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '기타', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '일상 사진',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '기타',
        '작품 그림', '일상 사진', '작품 그림', '기타', '작품 그림',
        '작품 그림', '작품 그림', '기타', '작품 그림', '작품 그림',
        '작품 그림', '작품 그림', '작품 그림', '작품 그림', '작품 그림'
    ]
}

In [69]:
## 모두 concat !!

df_detail = pd.DataFrame()
df_detail = pd.concat([pd.DataFrame(data_jpl) ,pd.DataFrame(data_abc), ])
data_sss = pd.DataFrame(data_sss) 
data_sss.columns = ['작가명', '게시일', '게시글 내용']
df_detail = pd.concat([df_detail, data_sss])
df_detail = pd.concat([df_detail, pd.DataFrame(data_sappcho), pd.DataFrame(data_combined) ,hdf ,pd.DataFrame(data_jo) ])
df_detail  = pd.concat([df_detail , data_pks, data_nam,data_jna,data_si]) 
df_detail = pd.concat([df_detail ,df_combined_2 ,df_combined3  ,df_combined5,pd.DataFrame(data_is) ,pd.DataFrame(data_gi) ,pd.DataFrame(data_mr),pd.DataFrame(data_lim),pd.DataFrame(data_gs) ,pd.DataFrame(data_lee),pd.DataFrame(data_ck)])
df_detail.columns = ['작가명', '게시일', '이미지 내용']

df_detail['게시일']= pd.to_datetime(df_detail['게시일'], errors='coerce', format='mixed')
df['게시글 날짜']= pd.to_datetime(df['게시글 날짜'], errors='coerce', format='mixed')

In [72]:
df['작가명'].unique()

array(['김태경', '정연', '자까', '쌉초', '감자', '진돌', '히디', '구나', '고추참치', '상금',
       '잇선', '이담', '박씨', '오성대', '구아진', '스프링', '모죠', '지발', '최다킬', '범배',
       '손하기', '허새보', '포스스튜디오', '박태준', '모랑지', '혀노', 'HO9', '조용석', '이은재',
       '돌석', '라군', '윤성', '채키', '이난', '임리나', '병장', '정종택', '박만사', '남자의 이야기',
       '한가람', '펀치킥', '제나', '태완', '유누니', '박진환', 'JP', '부겸', '배민기', '운',
       '시바견', '강견', '명랑', '하일권', '이대한', '황양', '득7이', '이솔', '꼬모소이', '켄타',
       '김대영', '이동건', '승우', '수박양', '스튜디오MW', '지페리', '임형'], dtype=object)

In [140]:
name = '박만사'
a1 = df[df['작가명'] == name]
a1= a1.reset_index(drop=True)
a1= a1.reset_index()

start_date = a1['게시글 날짜'].min()
end_date = a1['게시글 날짜'].max()

ad1 = df_detail[df_detail['작가명'] == name]

ad1= ad1[(ad1['게시일'] >= start_date) & (ad1['게시일'] <= end_date)]
ad1= ad1.reset_index(drop=True)
ad1= ad1.reset_index()

In [204]:
df_detail['이미지 내용']= df_detail['이미지 내용'].str.replace('작품 사진','작품 그림')
df_detail['이미지 내용']= df_detail['이미지 내용'].str.replace('일상 사진 얘네들도!','일상 사진')
df_detail_yes = df_detail[(df_detail['이미지 내용'] =='기타' ) | (df_detail['이미지 내용'] =='작품 그림' ) | (df_detail['이미지 내용'] =='일상 사진' )]

In [205]:
df_detail_no = df_detail[(df_detail['이미지 내용'] !='기타' )  & (df_detail['이미지 내용'] != '작품 그림' ) & (df_detail['이미지 내용'] !='일상 사진' )]

,작가명,작가 관심수,게시글 날짜,게시글 내용,이미지 여부,댓글수,반응수,best_reaction,good_reaction,warm_reaction,...,데뷔년도,웹툰단계,월,화,수,목,금,토,일,연재여부
0,김태경,10917.0,2024-10-08,"1등급 싸움과외 36화, 미리보기 39화 나왔습니다. 이번 주도 재밌게 봐주세요!",yes,5.0,43.0,9.0,32.0,1.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
1,김태경,10917.0,2024-10-02,"1등급 싸움과외 35화, 미리보기 38화 나왔습니다. 재밌게 봐주세요!",yes,5.0,44.0,7.0,35.0,1.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
3,김태경,10917.0,2024-09-24,"1등급 싸움과외 34화, 미리보기 37화 나왔습니다. 이번 주도 즐겁게 봐주세요!",yes,13.0,48.0,10.0,36.0,1.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
4,김태경,10917.0,2024-09-17,"1등급 싸움과외 33화, 미리보기 36화 나왔습니다. 도윤이 에피소드가 마무리되었네...",yes,14.0,49.0,6.0,41.0,1.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
5,김태경,10917.0,2024-09-10,"1등급 싸움과외 32화, 미리보기 35화 나왔습니다. 재밌게 봐주세요!",yes,7.0,42.0,2.0,35.0,2.0,...,2019,정식웹툰,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,임형,9309.0,2024-05-24,테오와 아기토끼들,yes,23.0,263.0,31.0,222.0,2.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1
878,임형,9309.0,2024-05-21,도자기로된 컵라면 용기를 사서 컵라면을 넣어 먹었습니다. 앞으로 제 밥그릇은 이겁니...,yes,27.0,149.0,57.0,62.0,3.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1
879,임형,9309.0,2024-05-18,마계일기- 번아웃,yes,21.0,171.0,37.0,89.0,5.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1
880,임형,9309.0,2024-05-17,야금야금 전에 올렸던 그림 올려보아요! 전 작가홈에 올렸을때 바탕화면으로 사용가능하...,yes,24.0,262.0,35.0,210.0,1.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1
881,임형,9309.0,2024-05-17,여러분 안녕하세요! 기존에 작가홈이 연결된 아이디를 변경하면서 작가홈이 싹 밀렸네요...,yes,7.0,172.0,23.0,136.0,2.0,...,2023,정식웹툰,0,0,0,0,1,0,0,1

In [224]:
df_no = df[df['게시글 내용'] == '0']
df_no_merge = pd.merge(df_no, df_detail_no, left_on = ['작가명','게시글 날짜'], right_on = ['작가명','게시일'], how = 'left')
df_no_merge

,작가명,작가 관심수,게시글 날짜,게시글 내용,이미지 여부,댓글수,반응수,best_reaction,good_reaction,warm_reaction,...,월,화,수,목,금,토,일,연재여부,게시일,이미지 내용
0,김태경,10917.0,2024-09-26,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,1,2024-09-26,10000
1,정연,25229.0,2024-07-09,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,1,2024-07-09,20000
2,정연,25229.0,2024-07-08,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,1,NaT,NaN
3,자까,73021.0,2024-09-19,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,1,0,0,1,1,2024-09-19,70000
4,자까,73021.0,2024-08-07,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,1,0,0,1,1,2024-08-07,60000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,스튜디오MW,5575.0,2024-07-31,0,0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,1,2024-07-31,1000
74,지페리,24068.0,2024-05-26,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,2024-05-26,20000
75,임형,9309.0,2024-08-16,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,0,1,2024-08-16,5000
76,임형,9309.0,2024-05-22,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,0,1,2024-05-22,1000
77,임형,9309.0,2024-05-17,0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,0,0,1,NaT,NaN

In [238]:
real_df = pd.DataFrame()
df_yes = df[df['게시글 내용'] != '0']
for name in df['작가명'].unique():
 
    a1 = df_yes[df_yes['작가명'] == name]


    start_date = a1['게시글 날짜'].min()
    end_date = a1['게시글 날짜'].max()

    ad1 = df_detail_yes[df_detail_yes['작가명'] == name]

    ad1= ad1[(ad1['게시일'] >= start_date) & (ad1['게시일'] <= end_date)]
    
    a1_ad1 =  pd.merge(a1 , ad1, left_on = '게시글 날짜', right_on = '게시일', how ='left')
    a1_ad1= a1_ad1.drop(['작가명_y', '게시일'],axis=1)
    a1_ad1.columns = ['작가명', '작가 관심수', '게시글 날짜', '게시글 내용', '이미지 여부', '댓글수', '반응수',
        'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction',
        'expect_reaction', 'sad_reaction', '작가유형', '장르', '만화명', '성별', '데뷔년도',
        '웹툰단계', '월', '화', '수', '목', '금', '토', '일', '연재여부', '이미지 내용']
    
    real_df = pd.concat([real_df, a1_ad1])

In [269]:
output = pd.concat([real_df, df_no_merge])
output.drop(['게시일'],axis=1, inplace=True)
output['작가 관심수_변동'] = ''

In [270]:
def make_fluc_columns(name):
 
    ot1 = output[output['작가명'] ==name].sort_values(by='게시글 날짜', ascending=False)
    ot1.reset_index(drop=True, inplace=True)
    ot1['작가 관심수_변동'] = ot1[(ot1['이미지 내용'] !='기타') & (ot1['이미지 내용'] != '일상 사진') & (ot1['이미지 내용'] != '작품 그림')]['이미지 내용']
    return ot1

In [273]:



df1 = pd.DataFrame()

for name in output['작가명'].unique():
    df1 = pd.concat([df1, make_fluc_columns(name)])

In [278]:
df1['이미지 내용'][df1['이미지 여부'] =='no' ] ='이미지_없음' # (df1['이미지 내용'].isnull())

/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/3236781700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['이미지 내용'][df1['이미지 여부'] =='no' ] ='이미지_없음' # (df1['이미지 내용'].isnull())

In [280]:
df1[df1['이미지 내용'].isnull()]['이미지 여부'].value_counts()

이미지 여부
yes    66
0      34
Name: count, dtype: int64

In [14]:
### 완벽하진 않지만 대충 이렇다 치고. 
df1 = pd.concat([df1, df_no]).drop_duplicates()  #['이미지 내용'].value_counts()

df1['이미지 내용']= df1['이미지 내용'].str.replace('작품 사진', '작품 그림')
df1['이미지 내용']= df1['이미지 내용'].str.replace('일상 사진 얘네들도!', '일상 사진')

df1['이미지 내용'].value_counts()  

df1['성별']=df1['성별'].str.replace('???','')
df['성별']=df['성별'].str.replace('???','')

In [15]:
import pandas as pd
  

# 숫자 형태로 요일 추출 (0: 월요일, 6: 일요일)
df1['요일_숫자'] = df1['게시글 날짜'].dt.dayofweek
 

# 예시 데이터프레임 생성
 

# 요일 숫자를 요일 이름으로 변환하는 함수
def convert_weekday(num):
    days = ['mon', 'tue', 'wed', 'thur', 'fri', 'sat', 'sun']
    return days[num]

# 요일 변환 적용
df1['요일_이름'] = df1['요일_숫자'].apply(convert_weekday)
df1.drop(['요일_숫자'],axis=1,inplace=True)

,작가명,작가 관심수,게시글 날짜,게시글 내용,이미지 여부,댓글수,반응수,best_reaction,good_reaction,warm_reaction,...,웹툰단계,월,화,수,목,금,토,일,연재여부,이미지 내용
0,임형,9309.0,2024-09-27,흑흑 여러분 이번 탑농사 휴재라 놀라셨죵! 여러 사정으로 재정비를 한뒤 10월3일에...,yes,50.0,131.0,42.0,70.0,5.0,...,정식웹툰,0,0,0,0,1,0,0,1,작품 그림
1,임형,9309.0,2024-09-16,시원한듯 시원하지 않은 더운 추석이네요 😂 저는 마감중입니다!! 모두 맛있는거 많이...,yes,34.0,136.0,26.0,100.0,2.0,...,정식웹툰,0,0,0,0,1,0,0,1,작품 그림
2,임형,9309.0,2024-09-01,마계일기 - 조련실패 귀여우니 봐준다...,yes,21.0,128.0,17.0,98.0,6.0,...,정식웹툰,0,0,0,0,1,0,0,1,작품 그림
3,임형,9309.0,2024-08-26,나 혼자 탑에서 농사. 아크릴 굿즈!! 크흡...방금 올린 사진이 너무 구리대서더보기,yes,49.0,166.0,20.0,135.0,1.0,...,정식웹툰,0,0,0,0,1,0,0,1,일상 사진
4,임형,9309.0,2024-08-18,마계일기- T발 전 공감능력이 높습니다... 높은가?,yes,27.0,132.0,20.0,94.0,12.0,...,정식웹툰,0,0,0,0,1,0,0,1,작품 그림
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,김대영,955.0,2024-07-22,안녕하세요 북경신보작가 김대영입니다. 8월 5일 월요웹툰에 신작으로 찾아뵙게되었습니...,no,33.0,41.0,20.0,8.0,0.0,...,정식웹툰,0,0,0,0,0,0,0,1,이미지_없는_게시물
770,승우,24130.0,2024-09-20,"🙇‍125화 유료분 휴재 공지 안녕하세요 독자님들, 이번 주 업로드 예정이었던 1...",no,78.0,452.0,61.0,243.0,23.0,...,정식웹툰,0,0,0,0,0,0,1,1,이미지_없는_게시물
778,수박양,20278.0,2024-08-09,안녕하세요. 두달이 안되어 또 휴재 소식을 전하게 되었습니다. 마감중 목이 잘 안 ...,no,81.0,311.0,39.0,76.0,8.0,...,정식웹툰,0,0,0,0,0,1,0,1,이미지_없는_게시물
779,수박양,20278.0,2024-06-21,아홉수 우리들 미리보기는 한 주만 쉬어가겠습니다..기다리신 독자님들 너무 죄송합니다...,no,31.0,162.0,10.0,60.0,28.0,...,정식웹툰,0,0,0,0,0,1,0,1,이미지_없는_게시물
812,스튜디오MW,5575.0,2024-02-06,"안녕하세요 네이버 웹툰 독자 여러분! 문피아 웹툰 스튜디오, 스튜디오MW 입니다😆 ...",no,8.0,48.0,19.0,23.0,2.0,...,정식웹툰,0,1,0,0,0,0,0,1,이미지_없는_게시물

In [19]:
# df1.to_csv('네이버웹툰_데이터_거의최종.csv')

# 분석 시작. 
# "네이버 웹툰 팬덤 분석" (Analysis of Naver Webtoon Fandom)

# df1

In [514]:
import pandas as pd
import numpy as np

# df1 = pd.read_csv('네이버웹툰_데이터_거의최종.csv', index_col=0)

In [515]:
def make_fluc_columns(name):
 
    ot1 = df1[df1['작가명'] ==name].sort_values(by='게시글 날짜', ascending=False)
    ot1.reset_index(drop=True, inplace=True)
    ot1['작가 관심수_변동'] = ot1['이미지 내용'][(ot1['이미지 내용'] !='기타') & (ot1['이미지 내용'] != '일상 사진') & (ot1['이미지 내용'] != '작품 그림') & (ot1['이미지 내용'] !='이미지_없는_게시물')]
    return ot1

In [516]:
df1['작가 관심수_변동'] = ''

In [517]:
df2 = pd.DataFrame()

for name in df1['작가명'].unique():
    df2 = pd.concat([df2, make_fluc_columns(name)])

In [518]:
df0 = pd.DataFrame()

for name in df1['작가명'].unique():

    if name =='히디':
        df0 = pd.concat([df0, df2[df2['작가명'] =='히디'].drop([5, 7], axis=0, errors='ignore')])
    elif name =='조용석' :
        df0 = pd.concat([df0, df2[df2['작가명'] =='조용석'].drop([8, 7], axis=0, errors='ignore')])
    elif name =='박진환' :
        df0 = pd.concat([df0, df2[df2['작가명'] =='박진환'].drop([1, 2], axis=0, errors='ignore')])
    elif name =='명랑' :
        df0 = pd.concat([df0,df2[df2['작가명'] =='명랑'].drop([5, 7], axis=0, errors='ignore')])

    elif name =='임형' :
        df0 = pd.concat([df0,df2[df2['작가명'] =='임형'].drop([ 6, 7, 20, 21, 32, 34, 36  ], axis=0, errors='ignore') ])
    
    else:
        df0 = pd.concat([df0, df2[df2['작가명'] ==name]])

In [ ]:
# df[(df['작가명'] =='정연' )& (df['게시글 내용']=='[2024년 신년 감사 인사 및 앙케트 마감 공지]  안녕하십니까, 독자 여러분.더보기')] # 기타 
 
# df[(df['작가명'] =='잇선')& (df['게시글 내용']=='뇨호호홍 시간이 이렇게나 벌써~~~ (좀 천천히가앗!!!!!!!!!!) 독자님들아~ 감기조심하세용~')] # 작품 그림
 # df[(df['작가명'] == '박씨' )& (df['게시글 내용']=='안녕하세요 박씨입니다. 재밌는 이야기 만들 수 있도록 노력하겠습니다. 감사합니다.')] #  작품 그림
# df[(df['작가명'] == '오성대'  )& (df['게시글 내용']=='만우절특집 일러스트입니다ㅎㅎ')] #  작품 그림
# df[(df['작가명'] == '오성대'  )& (df['게시글 내용']=='기기괴괴 완결 후, 나름 일찌감치 차기작을 준비하려 했습니다. 새로운 프로그램도 배우고 이런저런 스토리도 짜보고 원고로도 만들어 봤는데.. 시간이 지날수록 손에 쥔 생각들만 많아지고 결정이 쉽게 되지가 않더군요.더보기')] # 작품 그림
# df[(df['작가명'] == '구아진' )& (df['게시글 내용']=="미래의 골동품 가게가 '오디오웹툰'으로 만들어집니다!오늘 텀블벅 펀딩 오픈했습니다. 그리고 토백이 인형 및 여러 굿즈상품 리스트가 있으니 한 번 구경해보는 것도 재밌을 것 같습니다. 많은 관심 부탁드립니다~~(해당 토백이미지는 굿즈용 초안이며 실제 완성본과 차이가 있을 수 있습니다.)더보기")]
# df[(df['작가명'] == '모죠' )& (df['게시글 내용']== '첫 포스팅 올리네요😄 모두 새해 복 많이 받으세요!' )] # 작품 그림
# df[(df['작가명'] == '지발' )& (df['게시글 내용']== '<근황 사담>  안녕하세요, 독자 여러분 지발입니다_ _더보기')] # 일상 사진
# df[(df['작가명'] == '지발')& (df['게시글 내용']== '<짜투리 그림>')] # 작품 그림
# df[(df['작가명'] == '최다킬')& (df['게시글 내용']==  '안 녕하세요. 성검전설 작가 최 다킬입니다.더보기')] # 작품 그림
# df[(df['작가명'] == '이은재')& (df['게시글 내용']== '인기투표 결승')] # 작품 그림
# df[(df['작가명'] == '이은재')& (df['게시글 내용']== '연희고 인기투표')]  # 작품 그림
# df[(df['작가명'] == '이은재')& (df['게시글 내용']== '다른학교 인기투표')]  # 작품 그림
# df[(df['작가명'] == '채키')& (df['게시글 내용']== '대만 연재 시작하였습니다🙈')] 작품 그림


'''
lststst = []

for name in df['작가명'].unique():
    if  len(df[df['작가명'] ==name])  != len(df2[df2['작가명'] ==name]):
        lststst.append(name) 
'''



# df[(df['작가명'] =='정연' )& (df['게시글 내용']=='[2024년 신년 감사 인사 및 앙케트 마감 공지]  안녕하십니까, 독자 여러분.더보기')]
# df[(df['작가명'] =='쌉초' )& (df['게시글 내용']=='좋은주말보내세욥~!💕')]
# df[(df['작가명'] =='잇선')& (df['게시글 내용']=='뇨호호홍 시간이 이렇게나 벌써~~~ (좀 천천히가앗!!!!!!!!!!) 독자님들아~ 감기조심하세용~')]
# df[(df['작가명'] =='이담')& (df['게시글 내용']=='안녕하세요~! 지난주 연합뉴스와 <똑 닮은 딸> 인터뷰를 했습니다.  https://n.news.naver.com/mnews/article/001/0014806322?sid=103  대면 인터뷰는 난생 처음이었는데요, 정말 즐겁고 알찬 시간이었습니다! 두 시간가량 중언부언한 것 같은데, 김경윤 기자님께서 멋진 필력으로 압축시켜 주셔서 크게 감탄했습니다. 기자님의 통찰력이 돋보이는 멋진 질문이 질문지에 많았는데, 드러나지 않아 아쉬울 정도네요!  작가홈에 링크 걸면 잘 접속 되나요? 😍더보기')]
# df[(df['작가명'] =='이담')& (df['게시글 내용']=='안녕하세요~! 이담입니다. 반딱반딱한 보정이 얹어진 수정고와 작가의 말이 업데이트 되지 않은 상태로 복귀 회차가 올라가서, 혹시 바로 보신 분들은 <똑 닮은 딸> 재감상 부탁드립니다!  업데이트 되자마자 봐주신 감사한 열독자님들께 죄송스러운 일이 생겼네요 💦💦💦💦 의도치 않은 스포일러, 못본 척 해주시길 바랍니다🤣')]
# df[(df['작가명'] == '박씨' )& (df['게시글 내용']=='안녕하세요 박씨입니다. 재밌는 이야기 만들 수 있도록 노력하겠습니다. 감사합니다.')]
# df[(df['작가명'] == '오성대'  )& (df['게시글 내용']=='만우절특집 일러스트입니다ㅎㅎ')]
# df[(df['작가명'] == '오성대'  )& (df['게시글 내용']=='기기괴괴 완결 후, 나름 일찌감치 차기작을 준비하려 했습니다. 새로운 프로그램도 배우고 이런저런 스토리도 짜보고 원고로도 만들어 봤는데.. 시간이 지날수록 손에 쥔 생각들만 많아지고 결정이 쉽게 되지가 않더군요.더보기')]
# df[(df['작가명'] == '구아진' )& (df['게시글 내용']=="미래의 골동품 가게가 '오디오웹툰'으로 만들어집니다!오늘 텀블벅 펀딩 오픈했습니다. 그리고 토백이 인형 및 여러 굿즈상품 리스트가 있으니 한 번 구경해보는 것도 재밌을 것 같습니다. 많은 관심 부탁드립니다~~(해당 토백이미지는 굿즈용 초안이며 실제 완성본과 차이가 있을 수 있습니다.)더보기")]
# df[(df['작가명'] == '모죠' )& (df['게시글 내용']== '첫 포스팅 올리네요😄 모두 새해 복 많이 받으세요!' )]
# df[(df['작가명'] == '지발' )& (df['게시글 내용']== '<근황 사담>  안녕하세요, 독자 여러분 지발입니다_ _더보기')]
# df[(df['작가명'] == '지발')& (df['게시글 내용']== '<짜투리 그림>')]
# df[(df['작가명'] == '최다킬')& (df['게시글 내용']==  '안 녕하세요. 성검전설 작가 최 다킬입니다.더보기')]
# df[(df['작가명'] == '이은재')& (df['게시글 내용']== '인기투표 결승')]
# df[(df['작가명'] == '이은재')& (df['게시글 내용']== '연희고 인기투표')]
# df[(df['작가명'] == '이은재')& (df['게시글 내용']== '다른학교 인기투표')]
# df[(df['작가명'] == '채키')& (df['게시글 내용']== '대만 연재 시작하였습니다🙈')]




----------
# df2[df2['작가명'] =='히디'].drop([5, 7], axis=0, errors='ignore')
# df2[df2['작가명'] =='조용석'].drop([8, 7], axis=0, errors='ignore')
# df2[df2['작가명'] =='박진환'].drop([1, 2], axis=0, errors='ignore')
# df2[df2['작가명'] =='명랑'].drop([5, 7], axis=0, errors='ignore')
# df2[df2['작가명'] =='임형'].drop([ 6, 7, 20, 21, 32, 34, 36  ], axis=0, errors='ignore')

In [519]:
imsi = df[(df['작가명'] =='정연' )& (df['게시글 내용']=='[2024년 신년 감사 인사 및 앙케트 마감 공지]  안녕하십니까, 독자 여러분.더보기')]
imsi['이미지 내용'] ='기타'
df0 = pd.concat([df0, imsi])

imsi = df[(df['작가명'] =='잇선')& (df['게시글 내용']=='뇨호호홍 시간이 이렇게나 벌써~~~ (좀 천천히가앗!!!!!!!!!!) 독자님들아~ 감기조심하세용~')]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])

imsi = df[(df['작가명'] == '오성대'  )& (df['게시글 내용']=='만우절특집 일러스트입니다ㅎㅎ')]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])

imsi = df[(df['작가명'] == '오성대'  )& (df['게시글 내용']=='기기괴괴 완결 후, 나름 일찌감치 차기작을 준비하려 했습니다. 새로운 프로그램도 배우고 이런저런 스토리도 짜보고 원고로도 만들어 봤는데.. 시간이 지날수록 손에 쥔 생각들만 많아지고 결정이 쉽게 되지가 않더군요.더보기')] 
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])
 
imsi = df[(df['작가명'] == '구아진' )& (df['게시글 내용']=="미래의 골동품 가게가 '오디오웹툰'으로 만들어집니다!오늘 텀블벅 펀딩 오픈했습니다. 그리고 토백이 인형 및 여러 굿즈상품 리스트가 있으니 한 번 구경해보는 것도 재밌을 것 같습니다. 많은 관심 부탁드립니다~~(해당 토백이미지는 굿즈용 초안이며 실제 완성본과 차이가 있을 수 있습니다.)더보기")]
imsi['이미지 내용'] = '기타'
df0 = pd.concat([df0, imsi])

imsi = df[(df['작가명'] == '모죠' )& (df['게시글 내용']== '첫 포스팅 올리네요😄 모두 새해 복 많이 받으세요!' )]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])


imsi = df[(df['작가명'] == '지발' )& (df['게시글 내용']== '<근황 사담>  안녕하세요, 독자 여러분 지발입니다_ _더보기')]
imsi['이미지 내용'] ='일상 사진'
df0 = pd.concat([df0, imsi])

imsi = df[(df['작가명'] == '지발')& (df['게시글 내용']== '<짜투리 그림>')]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])

imsi =df[(df['작가명'] == '최다킬')& (df['게시글 내용']==  '안 녕하세요. 성검전설 작가 최 다킬입니다.더보기')]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])

imsi =df[(df['작가명'] == '이은재')& (df['게시글 내용']== '인기투표 결승')]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])

imsi =df[(df['작가명'] == '이은재')& (df['게시글 내용']== '연희고 인기투표')]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])

imsi =df[(df['작가명'] == '이은재')& (df['게시글 내용']== '다른학교 인기투표')]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])

imsi =df[(df['작가명'] == '채키')& (df['게시글 내용']== '대만 연재 시작하였습니다🙈')]
imsi['이미지 내용'] ='작품 그림'
df0 = pd.concat([df0, imsi])

/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='기타'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] = '기타'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='일상 사진'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/366498450.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] ='작품 그림'

In [524]:
#'박태준','범배', '손하기',  '허새보', '포스스튜디오' ,  '모랑지'   , 
# '시바견' ---<<다시 찾아서 비교 (일상사진 vs 작품그림) 


df0= df0[df0['작가명'] !='박태준'] 
df0= df0[df0['작가명'] !='범배'] 
df0= df0[df0['작가명'] !='손하기'] 
df0= df0[df0['작가명'] !='허새보'] 
df0= df0[df0['작가명'] !='포스스튜디오'] 
df0= df0[df0['작가명'] !='모랑지'] 
df0= df0[df0['작가명'] !='시바견']  


imsi =df[df['작가명'] =='박태준']
imsi['이미지 내용'] =['이미지_없는_게시물', '작품 그림','이미지_없는_게시물']
 
df0 = pd.concat([df0, imsi]) 

imsi =df[df['작가명'] =='범배']
imsi['이미지 내용'] =['이미지_없는_게시물','이미지_없는_게시물', '작품 그림','작품 그림','작품 그림','작품 그림','이미지_없는_게시물', '작품 그림','작품 그림','이미지_없는_게시물']
 
df0 = pd.concat([df0, imsi]) 

imsi = df[df['작가명'] =='손하기']
imsi['이미지 내용'] = ['10000','작품 그림','작품 그림','5000', '작품 그림', '작품 그림']
df0 = pd.concat([df0, imsi]) 

 # 62 : 6, 44, 8, 3, 1, 0
imsi = df[df['작가명'] =='허새보']
imsi['이미지 내용'] = ['일상 사진','일상 사진','일상 사진','일상 사진','일상 사진', '작품 그림','일상 사진','일상 사진','일상 사진','일상 사진']
df0 = pd.concat([df0, imsi]) 

imsi = df[df['작가명'] == '포스스튜디오' ] 
imsi['이미지 내용'] = ['5000', '작품 그림','작품 그림', '작품 그림','작품 그림', '작품 그림','작품 그림', '작품 그림','작품 그림','작품 그림']
df0 = pd.concat([df0, imsi]) 

imsi = df[df['작가명'] =='모랑지'] 
imsi['이미지 내용'] = ['기타' , '20000','기타' ,'이미지_없는_게시물','작품 그림','기타']
df0 = pd.concat([df0, imsi]) 



imsi = df[df['작가명'] =='시바견']
imsi['이미지 내용'] = ['이미지_없는_게시물','이미지_없는_게시물','이미지_없는_게시물','이미지_없는_게시물']+ ['작품 그림', '일상 사진','일상 사진','일상 사진','일상 사진', '일상 사진','작품 그림','작품 그림','일상 사진','이미지_없는_게시물','일상 사진', '작품 그림','일상 사진','일상 사진', '일상 사진','일상 사진','일상 사진', '일상 사진','일상 사진','작품 그림','일상 사진','일상 사진','일상 사진',
 '일상 사진', '작품 그림','일상 사진', '일상 사진', '일상 사진','일상 사진','일상 사진', '일상 사진','작품 그림','작품 그림','일상 사진','작품 그림','일상 사진']
df0 = pd.concat([df0, imsi])

/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/517748096.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] =['이미지_없는_게시물', '작품 그림','이미지_없는_게시물']
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/517748096.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] =['이미지_없는_게시물','이미지_없는_게시물', '작품 그림','작품 그림','작품 그림','작품 그림','이미지_없는_게시물', '작품 그림','작품 그림','이미지_없는_게시물']
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/517748096.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] = ['10000','작품 그림','작품 그림','5000', '작품 그림', '작품 그림']
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/517748096.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] = ['일상 사진','일상 사진','일상 사진','일상 사진','일상 사진', '작품 그림','일상 사진','일상 사진','일상 사진','일상 사진']
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/517748096.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] = ['5000', '작품 그림','작품 그림', '작품 그림','작품 그림', '작품 그림','작품 그림', '작품 그림','작품 그림','작품 그림']
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/517748096.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi['이미지 내용'] = ['기타' , '20000','기타' ,'이미지_없는_게시물','작품 그림','기타']

In [551]:
def make_fluc_columns(name):
 
    ot1 = df0[df0['작가명'] ==name].sort_values(by='게시글 날짜', ascending=False)
    ot1.reset_index(drop=True, inplace=True)
    ot1['작가 관심수_변동'] = ot1['이미지 내용'][(ot1['이미지 내용'] !='기타') & (ot1['이미지 내용'] != '일상 사진') & (ot1['이미지 내용'] != '작품 그림') & (ot1['이미지 내용'] !='이미지_없는_게시물')]
    return ot1
 

df0['작가 관심수_변동'] = ''
df3 = pd.DataFrame()

for name in df1['작가명'].unique():
    df3 = pd.concat([df3, make_fluc_columns(name)])

In [554]:
# df3.to_csv('네이버웹툰_데이터_거의최종1.csv')

## df0

In [622]:
df0 = pd.read_csv('네이버웹툰_데이터_거의최종1.csv',index_col=0)

- 결측값 채우기

In [556]:
df0.isnull().sum()

작가명                  0
작가 관심수               0
게시글 날짜               0
게시글 내용               0
이미지 여부               0
댓글수                  0
반응수                  0
best_reaction      188
good_reaction      178
warm_reaction      177
surp_reaction      177
expect_reaction    176
sad_reaction       175
작가유형                 0
장르                   0
만화명                  0
성별                   0
데뷔년도                 0
웹툰단계                 0
월                    0
화                    0
수                    0
목                    0
금                    0
토                    0
일                    0
연재여부                 0
이미지 내용               0
작가 관심수_변동          808
dtype: int64

In [623]:
# date_max = df0[df0['작가명'] =='임형']['게시글 날짜'].max()
 
df0['작가 관심수_변동'][df0.index ==0] =df0[df0.index ==0]['작가 관심수']

/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/3637731311.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0['작가 관심수_변동'][df0.index ==0] =df0[df0.index ==0]['작가 관심수']
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/3637731311.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0['작가 관심수_변동'][df0.index ==0] =df0[df0.index ==0]['작가 관심수']

In [624]:
## '작가 관심수_변동' - 선형 보간법으로 채움

df3 = pd.DataFrame()
for author in df0['작가명'].unique():
    imsi_df = df0[(df0['작가명'] == author)]
  
    imsi_df['작가 관심수_변동'] = imsi_df['작가 관심수_변동'].interpolate(method='linear')
    df3 = pd.concat( [df3 ,imsi_df])

/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/1440102960.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imsi_df['작가 관심수_변동'] = imsi_df['작가 관심수_변동'].interpolate(method='linear')

In [652]:
df3['best_reaction'][df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]= df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['반응수']- (df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['good_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'warm_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['surp_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'expect_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'sad_reaction'])

/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/3490553535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['best_reaction'][df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]= df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['반응수']- (df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['good_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'warm_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['surp_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'expect_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'sad_reaction'])
/var/folders/32/kf__h26s36l08d_ty7fh2xjr0000gn/T/ipykernel_1306/3490553535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['best_reaction'][df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]= df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['반응수']- (df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['good_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'warm_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1]['surp_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'expect_reaction']+df3[df3[['best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction']].isnull().sum(axis=1) == 1][ 'sad_reaction'])

In [653]:
df3.isnull().sum()

작가명                  0
작가 관심수               0
게시글 날짜               0
게시글 내용               0
이미지 여부               0
댓글수                  0
반응수                  0
best_reaction      178
good_reaction      178
warm_reaction      177
surp_reaction      177
expect_reaction    176
sad_reaction       175
작가유형                 0
장르                   0
만화명                  0
성별                   0
데뷔년도                 0
웹툰단계                 0
월                    0
화                    0
수                    0
목                    0
금                    0
토                    0
일                    0
연재여부                 0
이미지 내용               0
작가 관심수_변동            0
dtype: int64

In [ ]:
# df3.isnull().sum()
'''
best_reaction      178
good_reaction      178
warm_reaction      177
surp_reaction      177
expect_reaction    176
sad_reaction       175
'''

In [615]:
df3.columns

Index(['작가명', '작가 관심수', '게시글 날짜', '게시글 내용', '이미지 여부', '댓글수', '반응수',
       'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction',
       'expect_reaction', 'sad_reaction', '작가유형', '장르', '만화명', '성별', '데뷔년도',
       '웹툰단계', '월', '화', '수', '목', '금', '토', '일', '연재여부', '이미지 내용',
       '작가 관심수_변동'],
      dtype='object')

## 여기서부터 채워 넣어야함..

In [ ]:
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction', 채우기

In [681]:
df3[df3.best_reaction.isnull()]['작가명'].nunique()

30

In [655]:
df3[df3.best_reaction.isnull()]['작가명'].unique()

array(['스튜디오MW', '하일권', '명랑', '강견', '운', '배민기', 'JP', '박진환', '제나', '펀치킥',
       '정종택', '윤성', '라군', '이은재', '조용석', '혀노', '모랑지', '박태준', '포스스튜디오',
       '범배', '최다킬', '지발', '모죠', '스프링', '구아진', '오성대', '박씨', '이담', '히디',
       '정연'], dtype=object)

In [609]:
df3.columns

Index(['작가명', '작가 관심수', '게시글 날짜', '게시글 내용', '이미지 여부', '댓글수', '반응수',
       'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction',
       'expect_reaction', 'sad_reaction', '작가유형', '장르', '만화명', '성별', '데뷔년도',
       '웹툰단계', '월', '화', '수', '목', '금', '토', '일', '연재여부', '이미지 내용',
       '작가 관심수_변동'],
      dtype='object')

In [ ]:
'스튜디오MW', '하일권', '명랑', '강견', '운', '배민기', 'JP', '박진환', '제나', '펀치킥',
       '정종택', '윤성', '라군', '이은재', '조용석', '혀노', '모랑지', '박태준', '포스스튜디오',
       '범배', '최다킬', '지발', '모죠', '스프링', '구아진', '오성대', '박씨', '이담', '히디',
       '정연'

In [728]:
# df3[(df3['작가명'] =='스튜디오MW')  & (df3.best_reaction.isnull())][[ '게시글 날짜', '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
# 2024-10-04   18    8,8,2,0,2,0

# 대체할 값 설정
replace_values = {
    "반응수": 18,
    "best_reaction": 8,
    "good_reaction": 8,
    "warm_reaction": 2,
    "surp_reaction": 0,
    "expect_reaction": 2,
    "sad_reaction": 0,
}

# 조건에 맞는 행에 대체 값 적용
df3.loc[(df3["게시글 날짜"] == "2024-10-04") & (df3["작가명"] == "스튜디오MW") , replace_values.keys()] = list(replace_values.values())

In [729]:
# df3[(df3['작가명'] =='하일권')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
  
# 2024-05-12   75    20, 50, 2, 1, 1, 0
replace_values = {
    "반응수": 75,
    "best_reaction": 20,
    "good_reaction": 50,
    "warm_reaction": 2,
    "surp_reaction": 1,
    "expect_reaction": 1,
    "sad_reaction": 0,
}
df3.loc[(df3["게시글 날짜"] == "2024-05-12") & (df3["작가명"] == "하일권") , replace_values.keys()] = list(replace_values.values())

In [742]:
# df3[(df3['작가명'] =='JP')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
# 2024-10-08  115   70, 20, 2, 2, 8, 3
# 2024-10-07  71    41, 13, 5, 0, 0, 12
# 2024.09.29  87    52, 31, 1, 0, 2, 1
# 2024.09.29  50    12, 32, 0, 0, 5, 1
# 2024-09-28  115   40, 68, 3, 0, 2, 2
# 2024-09-27   45   22, 19, 3, 0, 0, 1
# 2024-09-26   46   12, 32, 0, 1, 0, 1
# 2024-09-25   28   7, 20, 0, 0, 0, 1
# 2024-09-25   39   21, 17, 1, 0, 0, 0
# 2024-09-24   53   12, 26, 1, 0, 14, 0
 
replace_values = {
    (0,"2024-10-08"): [ 115, 70, 20, 2, 2, 8, 3],
    (1,"2024-10-07"): [ 71, 41, 13, 5, 0, 0, 12],
    (2,"2024-09-29"):  [87, 52, 31, 1, 0, 2, 1],
     (3,"2024-09-29"):  [50  ,12, 32, 0, 0, 5, 1],
    (4,"2024-09-28"): [ 115, 40, 68, 3, 0, 2, 2],
    (5,"2024-09-27"): [  45, 22, 19, 3, 0, 0, 1],
    (6,"2024-09-26"): [  46, 12, 32, 0, 1, 0, 1],
    (7,"2024-09-25"): [  28, 7, 20, 0, 0, 0, 1],
     (8,"2024-09-25"): [ 39 ,  21, 17, 1, 0, 0, 0],
    (9,"2024-09-24"): [  53, 12, 26, 1, 0, 14, 0],
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] == 'JP') , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] =='JP')][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-08,115.0,70.0,20.0,2.0,2.0,8.0,3.0
1,2024-10-07,71.0,41.0,13.0,5.0,0.0,0.0,12.0
2,2024-09-29,87.0,52.0,31.0,1.0,0.0,2.0,1.0
3,2024-09-29,50.0,12.0,32.0,0.0,0.0,5.0,1.0
4,2024-09-28,115.0,40.0,68.0,3.0,0.0,2.0,2.0
5,2024-09-27,45.0,22.0,19.0,3.0,0.0,0.0,1.0
6,2024-09-26,46.0,12.0,32.0,0.0,1.0,0.0,1.0
7,2024-09-25,28.0,7.0,20.0,0.0,0.0,0.0,1.0
8,2024-09-25,39.0,21.0,17.0,1.0,0.0,0.0,0.0
9,2024-09-24,53.0,12.0,26.0,1.0,0.0,14.0,0.0

In [744]:
df3[(df3['작가명'] =='배민기')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-02,40.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-09-27,39.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-09-19,48.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-06-24,33.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-30,82.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-01-11,50.0,NaN,NaN,NaN,NaN,NaN,NaN
6,2023-11-09,51.0,NaN,NaN,NaN,NaN,NaN,NaN
7,2023-11-08,73.0,NaN,NaN,NaN,NaN,NaN,NaN
8,2023-09-28,94.0,NaN,NaN,NaN,NaN,NaN,NaN
9,2023-09-21,76.0,NaN,NaN,NaN,NaN,NaN,NaN

In [745]:
# df3[(df3['작가명'] =='배민기')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 

# https://comic.naver.com/community/u/ms10000rh?lastPage=SearchResult
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
 
#   2024-10-02	52	 27, 22, 0, 0, 3 ,0  
#	2024-09-27	43   30, 13, 0, 0, 0 ,0 	 
#	2024-09-19	52   35, 12, 1, 0, 4, 0
#	2024-06-24	34   23, 9, 1, 0, 1, 0 
#	2024-01-30  87   56, 18, 1, 4, 8, 0
#	2024-01-11	51   37, 10, 1, 3, 0, 0
#	2023-11-09	51   15, 23, 1, 5, 6, 2
#	2023-11-08	75   52, 14, 1, 2, 6, 0
#	2023-09-28	94   63, 10, 1, 2, 2, 16
#	2023-09-21	76   51, 10, 0, 3, 12, 0

 
author_name = '배민기'
replace_values = {
    (0,"2024-10-02"): [ 52, 27, 22, 0, 0, 3 ,0 ],
    (1,"2024-09-27"): [ 43, 30, 13, 0, 0, 0 ,0 ],
    (2,"2024-09-19"):  [52, 35, 12, 1, 0, 4, 0],
     (3,"2024-06-24"):  [34, 23, 9, 1, 0, 1, 0 ],
    (4,"2024-01-30"): [ 87, 56, 18, 1, 4, 8, 0],
    (5,"2024-01-11"): [ 51, 37, 10, 1, 3, 0, 0],
    (6,"2023-11-09"): [51, 15, 23, 1, 5, 6, 2],
    (7,"2023-11-08"): [ 75, 52, 14, 1, 2, 6, 0],
     (8,"2023-09-28"): [ 94, 63, 10, 1, 2, 2, 16],
    (9,"2023-09-21"): [ 76, 51, 10, 0, 3, 12, 0],
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-02,52.0,27.0,22.0,0.0,0.0,3.0,0.0
1,2024-09-27,43.0,30.0,13.0,0.0,0.0,0.0,0.0
2,2024-09-19,52.0,35.0,12.0,1.0,0.0,4.0,0.0
3,2024-06-24,34.0,23.0,9.0,1.0,0.0,1.0,0.0
4,2024-01-30,87.0,56.0,18.0,1.0,4.0,8.0,0.0
5,2024-01-11,51.0,37.0,10.0,1.0,3.0,0.0,0.0
6,2023-11-09,51.0,15.0,23.0,1.0,5.0,6.0,2.0
7,2023-11-08,75.0,52.0,14.0,1.0,2.0,6.0,0.0
8,2023-09-28,94.0,63.0,10.0,1.0,2.0,2.0,16.0
9,2023-09-21,76.0,51.0,10.0,0.0,3.0,12.0,0.0

In [749]:
df3[(df3['작가명'] =='운')   ][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-18,52.0,32.0,16.0,0.0,0.0,4.0,0.0
1,2024-09-18,32.0,19.0,5.0,0.0,2.0,6.0,0.0
2,2024-08-31,70.0,40.0,21.0,0.0,0.0,8.0,1.0
3,2024-08-18,58.0,30.0,12.0,0.0,2.0,14.0,0.0
4,2024-06-24,27.0,15.0,10.0,0.0,0.0,2.0,0.0
5,2024-04-13,50.0,38.0,10.0,0.0,2.0,0.0,0.0
6,2024-02-15,583.0,43.0,30.0,0.0,1.0,8.0,1.0
7,2024-01-11,33.0,23.0,6.0,1.0,2.0,1.0,0.0
8,2023-12-28,65.0,43.0,16.0,1.0,1.0,3.0,1.0
9,2023-12-02,41.0,26.0,5.0,1.0,2.0,5.0,2.0

In [750]:
# df3[(df3['작가명'] =='운')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#  2024-09-18	52 ,  32, 16, 0,0,4,0
#  2024-09-18	32  , 19, 5, 0, 2, 6, 0
#  2024-08-31	70  , 40, 21, 0, 0, 8, 1
#  2024-08-18	58  , 30, 12, 0, 2, 14, 0
#  2024-06-24	27 , 15, 10, 0, 0, 2, 0
#  2024-04-13	50  , 38, 10, 0, 2, 0, 0
#  2024-02-15	83 , 43, 30, 0, 1, 8, 1


# https://comic.naver.com/community/u/writerun?lastPage=SearchResult

author_name = '운'
replace_values = {
    (0,"2024-09-18"): [ 52 ,  32, 16, 0,0,4,0 ],
    (1,"2024-09-18"): [ 32  , 19, 5, 0, 2, 6, 0 ],
    (2,"2024-08-31"):  [70  , 40, 21, 0, 0, 8, 1 ],
     (3,"2024-08-18"):  [58  , 30, 12, 0, 2, 14, 0 ],
    (4,"2024-06-24"): [ 27 , 15, 10, 0, 0, 2, 0],
    (5,"2024-04-13"): [ 50  , 38, 10, 0, 2, 0, 0],
    (6,"2024-02-15"): [583 , 43, 30, 0, 1, 8, 1],
    
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-18,52.0,32.0,16.0,0.0,0.0,4.0,0.0
1,2024-09-18,32.0,19.0,5.0,0.0,2.0,6.0,0.0
2,2024-08-31,70.0,40.0,21.0,0.0,0.0,8.0,1.0
3,2024-08-18,58.0,30.0,12.0,0.0,2.0,14.0,0.0
4,2024-06-24,27.0,15.0,10.0,0.0,0.0,2.0,0.0
5,2024-04-13,50.0,38.0,10.0,0.0,2.0,0.0,0.0
6,2024-02-15,583.0,43.0,30.0,0.0,1.0,8.0,1.0
7,2024-01-11,33.0,23.0,6.0,1.0,2.0,1.0,0.0
8,2023-12-28,65.0,43.0,16.0,1.0,1.0,3.0,1.0
9,2023-12-02,41.0,26.0,5.0,1.0,2.0,5.0,2.0

In [751]:
# df3[(df3['작가명'] == '강견')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-10-05	222 , 155, 20, 5, 0, 0, 42
#	2024-09-17	58 , 34, 21, 1, 1, 1, 0
#	2024-09-14	52 , 42, 10, 0, 0, 0, 0
#	2024-09-01	33,	20, 13, 0, 0, 0, 0
#	2024-08-31	58  , 35, 22, 1, 0,0,0
#	2024-08-18	37 , 11, 17, 5, 0, 4, 0
#	2024-08-17	96 ,0, 1, 0, 0, 0, 95
#	2024-08-04	39 , 14, 17, 1, 0, 1, 6
#	2024-08-03	35 , 23, 5, 7, 0, 0, 0
#	2024-07-19	77 ,  54, 18, 4, 0, 1, 0

# https://comic.naver.com/community/u/Kangkyeon1231?lastPage=SearchResult


author_name = '강견'
replace_values = {
    (0,"2024-10-05"): [ 222 , 155, 20, 5, 0, 0, 42 ],
    (1,"2024-09-17"): [58 , 34, 21, 1, 1, 1, 0 ],
    (2,"2024-09-14"):  [52 , 42, 10, 0, 0, 0, 0 ],
     (3,"2024-09-01"):  [33,	20, 13, 0, 0, 0, 0 ],
    (4,"2024-08-31"): [ 58  , 35, 22, 1, 0,0,0],
    (5,"2024-08-18"): [ 37 , 11, 17, 5, 0, 4, 0],
    (6,"2024-08-17"): [96 ,0, 1, 0, 0, 0, 95],
     (7,"2024-08-04"): [ 39 , 14, 17, 1, 0, 1, 6],
    (8,"2024-08-03"): [ 35 , 23, 5, 7, 0, 0, 0],
    (9,"2024-07-19"): [77 ,  54, 18, 4, 0, 1, 0],
    
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-05,222.0,155.0,20.0,5.0,0.0,0.0,42.0
1,2024-09-17,58.0,34.0,21.0,1.0,1.0,1.0,0.0
2,2024-09-14,52.0,42.0,10.0,0.0,0.0,0.0,0.0
3,2024-09-01,33.0,20.0,13.0,0.0,0.0,0.0,0.0
4,2024-08-31,58.0,35.0,22.0,1.0,0.0,0.0,0.0
5,2024-08-18,37.0,11.0,17.0,5.0,0.0,4.0,0.0
6,2024-08-17,96.0,0.0,1.0,0.0,0.0,0.0,95.0
7,2024-08-04,39.0,14.0,17.0,1.0,0.0,1.0,6.0
8,2024-08-03,35.0,23.0,5.0,7.0,0.0,0.0,0.0
9,2024-07-19,77.0,54.0,18.0,4.0,0.0,1.0,0.0

In [752]:
df3[(df3['작가명'] =='명랑')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-10-03	49 , 27, 19, 0, 1, 2, 0
#	2024-06-26	113 ,  50, 57, 4, 0, 2, 0
#	2024-06-13	65,	33, 26, 4, 0, 1, 1
#	2024-05-26	56,	19, 32, 0, 2, 3, 0
#	2024-05-26	54,	22, 22, 3, 1, 6, 0
#	2024-05-08	62,	19, 39, 1, 1, 2, 0
#	2024-05-01	53,	18, 31, 1, 1, 2, 0
#	2024-04-08	192,123, 61, 4, 1, 3, 0
#	2024-04-06	63,	32, 27, 1, 1, 2, 0

# https://comic.naver.com/community/u/myoungrang?lastPage=SearchResult


author_name = '명랑'
replace_values = {
    (0,"2024-10-03"): [ 49 , 27, 19, 0, 1, 2, 0],
    (2,"2024-06-26"): [113 ,  50, 57, 4, 0, 2, 0 ],
    (3,"2024-06-13"):  [65,	33, 26, 4, 0, 1, 1],
     (4,"2024-05-26"):  [56,	19, 32, 0, 2, 3, 0 ],
    (5,"2024-05-26"): [ 54,	22, 22, 3, 1, 6, 0],
    (6,"2024-05-08"): [ 62,	19, 39, 1, 1, 2, 0],
    (7,"2024-05-01"): [53,	18, 31, 1, 1, 2, 0],
     (8,"2024-04-08"): [ 192,123, 61, 4, 1, 3, 0],
    (9,"2024-04-06"): [ 63,	32, 27, 1, 1, 2, 0],
    
    
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-03,49.0,27.0,19.0,0.0,1.0,2.0,0.0
1,2024-08-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024-06-26,113.0,50.0,57.0,4.0,0.0,2.0,0.0
3,2024-06-13,65.0,33.0,26.0,4.0,0.0,1.0,1.0
4,2024-05-26,56.0,19.0,32.0,0.0,2.0,3.0,0.0
5,2024-05-26,54.0,22.0,22.0,3.0,1.0,6.0,0.0
6,2024-05-08,62.0,19.0,39.0,1.0,1.0,2.0,0.0
7,2024-05-01,53.0,18.0,31.0,1.0,1.0,2.0,0.0
8,2024-04-08,192.0,123.0,61.0,4.0,1.0,3.0,0.0
9,2024-04-06,63.0,32.0,27.0,1.0,1.0,2.0,0.0

In [753]:
# df3[(df3['작가명'] =='박진환')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',

#   2024-10-08	114 ,   78, 31, 3, 0, 2, 0
#	2024-09-16	98  ,  55, 37, 3, 0, 3, 0
#	2023-11-13	79  ,  56, 15, 3, 4, 1, 0
#	2023-09-26	202 ,  121, 63, 2, 1, 16, 0

# https://comic.naver.com/community/u/_pbotc?lastPage=SearchResult


author_name = '박진환'
replace_values = {
    (0,"2024-10-08"): [ 114 ,   78, 31, 3, 0, 2, 0],
    (2,"2024-09-16"): [98  ,  55, 37, 3, 0, 3, 0 ],
    (4,"2023-11-13"):  [79  ,  56, 15, 3, 4, 1, 0],
     (5,"2023-09-26"):  [202 ,  121, 63, 2, 1, 16, 0 ], 
    
    
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-08,114.0,78.0,31.0,3.0,0.0,2.0,0.0
1,2024-10-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024-09-16,98.0,55.0,37.0,3.0,0.0,3.0,0.0
3,2024-08-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2023-11-13,79.0,56.0,15.0,3.0,4.0,1.0,0.0
5,2023-09-26,202.0,121.0,63.0,2.0,1.0,16.0,0.0

In [754]:
# df3[(df3['작가명'] ==  '펀치킥')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-09-28	59 , 20, 39, 0, 0, 0, 0
#	2024-09-10	66 ,  9, 55, 0, 1, 1, 0
#	2024-05-04	73 ,  9, 59, 0, 1, 4, 0
#	2024-05-01	64 , 8, 49, 0, 3, 4, 0
#	2024-02-28	64 ,	19, 41, 2, 2, 0, 0
#	2024-02-07	105,	20, 74, 8, 1, 2, 0
#	2024-01-31	147, 23, 122, 0, 2, 0, 0
#	2024-01-21	70 ,	10, 55, 4, 1, 0, 0
#	2024-01-19	88 , 28, 58, 1, 1, 0, 0

# https://comic.naver.com/community/u/_chky1?lastPage=SearchResult

author_name = '펀치킥'
replace_values = {
    (0,"2024-09-28"): [ 59 , 20, 39, 0, 0, 0, 0 ],
    (2,"2024-09-10"):  [66 ,  9, 55, 0, 1, 1, 0 ],
     (3,"2024-05-04"):  [73 ,  9, 59, 0, 1, 4, 0 ],
    (4,"2024-05-01"): [ 64 , 8, 49, 0, 3, 4, 0],
    (5,"2024-02-28"): [ 64 ,	19, 41, 2, 2, 0, 0],
    (6,"2024-02-07"): [105,	20, 74, 8, 1, 2, 0],
     (7,"2024-01-31"): [ 147, 23, 122, 0, 2, 0, 0],
    (8,"2024-01-21"): [70 ,	10, 55, 4, 1, 0, 0],
    (9,"2024-01-19"): [88 , 28, 58, 1, 1, 0, 0],
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-28,59.0,20.0,39.0,0.0,0.0,0.0,0.0
1,2024-09-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024-09-10,66.0,9.0,55.0,0.0,1.0,1.0,0.0
3,2024-05-04,73.0,9.0,59.0,0.0,1.0,4.0,0.0
4,2024-05-01,64.0,8.0,49.0,0.0,3.0,4.0,0.0
5,2024-02-28,64.0,19.0,41.0,2.0,2.0,0.0,0.0
6,2024-02-07,105.0,20.0,74.0,8.0,1.0,2.0,0.0
7,2024-01-31,147.0,23.0,122.0,0.0,2.0,0.0,0.0
8,2024-01-21,70.0,10.0,55.0,4.0,1.0,0.0,0.0
9,2024-01-19,88.0,28.0,58.0,1.0,1.0,0.0,0.0

In [755]:
# df3[(df3['작가명'] ==   '정종택')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
  
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',

#   2024-07-08	45 , 14, 25, 3, 1, 1, 1
#	2024-07-05	49 ,10, 36, 1, 1, 1, 0
#	2024-06-20	41 , 23, 15, 1, 2, 0, 0
#	2024-04-02	159,  33, 118, 3, 1, 4, 0
#	2023-12-21	88,	58, 22, 1, 3, 4, 0
#	2023-11-15	106,  55, 33, 3, 3, 12, 0
#	2023-11-14	155 , 48, 96, 5, 3, 3, 0
#	2023-11-14	72 , 33, 31, 2, 2, 3, 1
#	2023-09-27	1991, 58, 93, 4, 19, 14, 3

# https://comic.naver.com/community/u/cymhteak?lastPage=SearchResult

author_name = '정종택'
replace_values = {
    (0,"2024-07-08"): [ 45 , 14, 25, 3, 1, 1, 1 ],
    (1,"2024-07-05"):  [49 ,10, 36, 1, 1, 1, 0 ],
     (2,"2024-06-20"):  [41 , 23, 15, 1, 2, 0, 0 ],
    (4,"2024-04-02"): [ 159,  33, 118, 3, 1, 4, 0],
    (5,"2023-12-21"): [ 88,	58, 22, 1, 3, 4, 0],
    (6,"2023-11-15"): [106,  55, 33, 3, 3, 12, 0],
     (7,"2023-11-14"): [ 155 , 48, 96, 5, 3, 3, 0],
    (8,"2023-11-14"): [72 , 33, 31, 2, 2, 3, 1],
    (9,"2023-09-27"): [1991, 58, 93, 4, 19, 14, 3],
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-07-08,45.0,14.0,25.0,3.0,1.0,1.0,1.0
1,2024-07-05,49.0,10.0,36.0,1.0,1.0,1.0,0.0
2,2024-06-20,41.0,23.0,15.0,1.0,2.0,0.0,0.0
3,2024-05-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024-04-02,159.0,33.0,118.0,3.0,1.0,4.0,0.0
5,2023-12-21,88.0,58.0,22.0,1.0,3.0,4.0,0.0
6,2023-11-15,106.0,55.0,33.0,3.0,3.0,12.0,0.0
7,2023-11-14,155.0,48.0,96.0,5.0,3.0,3.0,0.0
8,2023-11-14,72.0,33.0,31.0,2.0,2.0,3.0,1.0
9,2023-09-27,1991.0,58.0,93.0,4.0,19.0,14.0,3.0

In [756]:

# df3[(df3['작가명'] ==  '윤성')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',

#	2024-01-25	32,	5, 26, 0, 1, 0, 0
#	2023-10-08	52,	40, 5, 2, 1, 3, 1
#	2023-10-02	81,	34, 38, 2, 5, 1, 1


# https://comic.naver.com/community/u/_ybou2?lastPage=SearchResult

author_name =  '윤성'
replace_values = {
    (1,"2024-01-25"): [ 32,	5, 26, 0, 1, 0, 0 ],
    (2,"2023-10-08"):  [52,	40, 5, 2, 1, 3, 1],
     (3,"2023-10-02"):  [81,34, 38, 2, 5, 1, 1], 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-05-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-01-25,32.0,5.0,26.0,0.0,1.0,0.0,0.0
2,2023-10-08,52.0,40.0,5.0,2.0,1.0,3.0,1.0
3,2023-10-02,81.0,34.0,38.0,2.0,5.0,1.0,1.0

In [757]:
# df3[(df3['작가명'] == '라군')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
# 2024-01-26	24,	4, 17, 0, 1, 2, 0

author_name = '라군'
replace_values = {
    (1,"2024-01-26"): [ 24,	4, 17, 0, 1, 2, 0 ] 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-05-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-01-26,24.0,4.0,17.0,0.0,1.0,2.0,0.0
2,2023-12-28,34.0,9.0,21.0,2.0,1.0,0.0,1.0
3,2023-12-03,37.0,22.0,14.0,0.0,1.0,0.0,0.0
4,2023-09-29,82.0,33.0,40.0,4.0,1.0,1.0,3.0

In [758]:
# df3[(df3['작가명'] ==  '이은재')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-09-21 00:00:00	45, 14, 26, 0,0,5,0
#	2024-09-21 00:00:00	35,	6, 27, 0, 0, 2, 0
#	2024-09-21 00:00:00	37,  9, 26, 0, 0, 2, 0
#	2024-09-05	147 ,66, 38, 10, 1, 2, 30
#	2024-08-01	124 , 61, 42, 8, 11, 2, 0
#	2024-07-30	209 , 129, 76, 2, 0, 1, 1
#	2024-07-27	200 , 162, 31, 2, 2, 3, 0
#	2024-07-18	156 , 67,78,0,2,8,1
#	2024-07-17	207  , 190, 104, 1, 2, 10, 0

# https://comic.naver.com/community/u/_mbour?lastPage=SearchResult

author_name =  '이은재'
replace_values = {
    (0,"2024-09-21 00:00:00"): [ 45, 14, 26, 0,0,5,0 ],
     (1,"2024-09-21 00:00:00"):  [35,	6, 27, 0, 0, 2, 0 ],
    (2,"2024-09-21 00:00:00"):  [37,  9, 26, 0, 0, 2, 0],
     (3,"2024-09-05"):  [147 ,66, 38, 10, 1, 2, 30 ],
    (5,"2024-08-01"): [ 124 , 61, 42, 8, 11, 2, 0],
    (6,"2024-07-30"): [209 , 129, 76, 2, 0, 1, 1],
     (7,"2024-07-27"): [200 , 162, 31, 2, 2, 3, 0],
    (8,"2024-07-18"): [156 , 67,78,0,2,8,1],
    (9,"2024-07-17"): [	207  , 190, 104, 1, 2, 10, 0],
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-21 00:00:00,45.0,14.0,26.0,0.0,0.0,5.0,0.0
1,2024-09-21 00:00:00,35.0,6.0,27.0,0.0,0.0,2.0,0.0
2,2024-09-21 00:00:00,37.0,9.0,26.0,0.0,0.0,2.0,0.0
3,2024-09-05,147.0,66.0,38.0,10.0,1.0,2.0,30.0
4,2024-09-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2024-08-01,124.0,61.0,42.0,8.0,11.0,2.0,0.0
6,2024-07-30,209.0,129.0,76.0,2.0,0.0,1.0,1.0
7,2024-07-27,200.0,162.0,31.0,2.0,2.0,3.0,0.0
8,2024-07-18,156.0,67.0,78.0,0.0,2.0,8.0,1.0
9,2024-07-17,207.0,190.0,104.0,1.0,2.0,10.0,0.0

In [760]:
df3[(df3['작가명'] ==  '조용석')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
  
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',

#   2024-06-26	214 , 102, 86, 0, 7, 15, 4
#	2024-01-05	276  , 91, 169, 6, 3, 6, 1
#	2023-11-09	249  , 159, 68, 4, 5, 13, 0
#	2023-10-16	410 , 274, 96, 7, 4, 20, 9
#	2023-10-06	588 , 368, 166, 7, 11, 26, 10
#	2023-10-06	219 , 133, 35, 8, 6, 6, 31
#	2023-09-17	1010,  494, 468, 15, 7, 22, 4
#	2023-09-17	558  , 398, 63, 18, 31, 46, 2
#	2023-09-14	726 , 514, 113, 41, 14, 32, 12

# https://comic.naver.com/community/u/_bboq6?lastPage=SearchResult

author_name =  '조용석'
replace_values = {
    (0,"2024-06-26"): [214 , 102, 86, 0, 7, 15, 4],
     (1,"2024-01-05"):  [276  , 91, 169, 6, 3, 6, 1 ],
    (2,"2023-11-09"):  [249  , 159, 68, 4, 5, 13, 0],
     (3,"2023-10-16"):  [410 , 274, 96, 7, 4, 20, 9 ],
    (4,"2023-10-06"): [	588 , 368, 166, 7, 11, 26, 10],
    (5,"2023-10-06"): [ 1219 , 133, 35, 8, 6, 6, 31],
    (6,"2023-09-17"): [1010,  494, 468, 15, 7, 22, 4],
     (7,"2023-09-17"): [558  , 398, 63, 18, 31, 46, 2],
    (8,"2023-09-14"): [726 , 514, 113, 41, 14, 32, 12]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-06-26,214.0,102.0,86.0,0.0,7.0,15.0,4.0
1,2024-01-05,276.0,91.0,169.0,6.0,3.0,6.0,1.0
2,2023-11-09,249.0,159.0,68.0,4.0,5.0,13.0,0.0
3,2023-10-16,410.0,274.0,96.0,7.0,4.0,20.0,9.0
4,2023-10-06,588.0,368.0,166.0,7.0,11.0,26.0,10.0
5,2023-10-06,1219.0,133.0,35.0,8.0,6.0,6.0,31.0
6,2023-09-17,1010.0,494.0,468.0,15.0,7.0,22.0,4.0
7,2023-09-17,558.0,398.0,63.0,18.0,31.0,46.0,2.0
8,2023-09-14,726.0,514.0,113.0,41.0,14.0,32.0,12.0

In [761]:
# df3[(df3['작가명'] == '혀노')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-09-24	445 ,  218, 204, 15, 4, 2, 2
#	2024-09-17	1195,  196, 956, 12, 4, 26, 1
#	2024-09-11	333 ,  54, 260, 4, 3, 12, 0
#	2024-09-06	448 , 55, 130, 7, 1, 5, 250
#	2024-08-10	719 , 94, 471, 20, 5, 6, 123
#	2024-05-25	774 , 95, 442, 7, 3, 7, 190
#	2024-05-13	1065,  160, 873, 13, 4, 13, 2
#	2024-05-07	636 , 166, 434, 10, 10, 13, 3

# https://comic.naver.com/community/u/_vokev?lastPage=SearchResult


author_name =  '혀노'
replace_values = {
    (0,"2024-09-24"): [445 ,  218, 204, 15, 4, 2, 2],
     (1,"2024-09-17"):  [ 1195,  196, 956, 12, 4, 26, 1 ],
    (2,"2024-09-11"):  [333 ,  54, 260, 4, 3, 12, 0],
     (3,"2024-09-06"):  [448 , 55, 130, 7, 1, 5, 250 ],
    (4,"2024-08-10"): [	719 , 94, 471, 20, 5, 6, 123],
    (6,"2024-05-25"): [774 , 95, 442, 7, 3, 7, 190],
     (7,"2024-05-13"): [1065,  160, 873, 13, 4, 13, 2],
    (8,"2024-05-07"): [636 , 166, 434, 10, 10, 13, 3]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-24,445.0,218.0,204.0,15.0,4.0,2.0,2.0
1,2024-09-17,1195.0,196.0,956.0,12.0,4.0,26.0,1.0
2,2024-09-11,333.0,54.0,260.0,4.0,3.0,12.0,0.0
3,2024-09-06,448.0,55.0,130.0,7.0,1.0,5.0,250.0
4,2024-08-10,719.0,94.0,471.0,20.0,5.0,6.0,123.0
5,2024-07-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2024-05-25,774.0,95.0,442.0,7.0,3.0,7.0,190.0
7,2024-05-13,1065.0,160.0,873.0,13.0,4.0,13.0,2.0
8,2024-05-07,636.0,166.0,434.0,10.0,10.0,13.0,3.0

In [762]:
# df3[(df3['작가명'] =='모랑지')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#    2024-09-25 00:00:00	156  , 14, 131, 3, 1, 6, 1
#	2024-04-01 00:00:00	    387  , 40, 326, 9, 5, 7, 0
#	2024-01-07 00:00:00	    352 ,  83, 190, 17, 3, 9, 50
#	2023-12-21 00:00:00	    371 ,  69, 279, 16, 2, 5, 0
#	2023-09-27 00:00:00	    719  , 154, 482, 14, 13, 46, 10

#  https://comic.naver.com/community/u/_nboqm?lastPage=SearchResult


author_name = '모랑지'
replace_values = {
    (0,"2024-09-25 00:00:00"): [156  , 14, 131, 3, 1, 6, 1],
    (2,"2024-04-01 00:00:00"):  [387  , 40, 326, 9, 5, 7, 0],
     (3,"2024-01-07 00:00:00"):  [352 ,  83, 190, 17, 3, 9, 50 ],
    (4,"2023-12-21 00:00:00"): [ 371 ,  69, 279, 16, 2, 5, 0],
    (5,"2023-09-27 00:00:00"): [719  , 154, 482, 14, 13, 46, 10]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-25 00:00:00,156.0,14.0,131.0,3.0,1.0,6.0,1.0
1,2024-09-19 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024-04-01 00:00:00,387.0,40.0,326.0,9.0,5.0,7.0,0.0
3,2024-01-07 00:00:00,352.0,83.0,190.0,17.0,3.0,9.0,50.0
4,2023-12-21 00:00:00,371.0,69.0,279.0,16.0,2.0,5.0,0.0
5,2023-09-27 00:00:00,719.0,154.0,482.0,14.0,13.0,46.0,10.0

In [766]:
df3[(df3['작가명'] ==  '범배')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-10-09 00:00:00	90  ,  17, 62, 4, 1, 3, 3
#	2024-09-25 00:00:00	166 ,  29, 123, 4, 2, 8, 0
#	2024-08-21 00:00:00	381 ,  66, 292, 11, 2, 6, 4
#	2024-05-29 00:00:00	255  , 34, 205, 8, 4, 4, 0
#	2024-05-01 00:00:00	312 ,  34, 260, 11, 5, 1, 1
#	2024-04-10 00:00:00	307 ,  25, 268, 7, 5, 2, 0
#	2024-04-04 00:00:00	319 ,  27, 273, 8, 3, 7, 1

# https://comic.naver.com/community/u/lbb?lastPage=SearchResult

author_name = '범배'
replace_values = {
    (1,"2024-10-09 00:00:00"): [90  ,  17, 62, 4, 1, 3, 3],
    (2,"2024-09-25 00:00:00"):  [166 ,  29, 123, 4, 2, 8, 0],
     (3,"2024-08-21 00:00:00"):  [381 ,  66, 292, 11, 2, 6, 4],
    (4,"2024-05-29 00:00:00"): [ 255  , 34, 205, 8, 4, 4, 0],
    (5,"2024-05-01 00:00:00"): [312 ,  34, 260, 11, 5, 1, 1],
     (7,"2024-04-10 00:00:00"): [307 ,  25, 268, 7, 5, 2, 0],
    (8,"2024-04-04 00:00:00"): [319 ,  27, 273, 8, 3, 7, 1]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-12 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-10-09 00:00:00,90.0,17.0,62.0,4.0,1.0,3.0,3.0
2,2024-09-25 00:00:00,166.0,29.0,123.0,4.0,2.0,8.0,0.0
3,2024-08-21 00:00:00,381.0,66.0,292.0,11.0,2.0,6.0,4.0
4,2024-05-29 00:00:00,255.0,34.0,205.0,8.0,4.0,4.0,0.0
5,2024-05-01 00:00:00,312.0,34.0,260.0,11.0,5.0,1.0,1.0
6,2024-04-21 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2024-04-10 00:00:00,307.0,25.0,268.0,7.0,5.0,2.0,0.0
8,2024-04-04 00:00:00,319.0,27.0,273.0,8.0,3.0,7.0,1.0
9,2024-03-29 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [767]:
df3[(df3['작가명'] ==  '포스스튜디오')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
  
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',


#   2024-04-10 00:00:00	89, 24, 60, 2, 1, 2, 0
#	2024-04-02 00:00:00	36 ,9, 21, 1, 3, 2, 0
#	2024-04-02 00:00:00	25  , 9, 12, 1, 1, 2, 0
#	2024-04-01 00:00:00	68 , 13, 48, 3, 1, 3, 0
#	2023-10-20 00:00:00	90, 14, 71, 3, 1, 1, 0
#	2023-10-18 00:00:00	61,	12, 44, 2, 1, 1, 1
#	2023-10-18 00:00:00	63,	7, 51, 2, 1, 2, 0
#	2023-10-13 00:00:00	94,	14, 71, 5, 1, 2, 1
#	2023-10-11 00:00:00	101,  48, 37, 13, 2, 0, 1

# https://comic.naver.com/community/u/_0jhat?lastPage=SearchResult

author_name = '포스스튜디오'
replace_values = {
    (1,"2024-04-10 00:00:00"): [89, 24, 60, 2, 1, 2, 0],
    (2,"2024-04-02 00:00:00"):  [36 ,9, 21, 1, 3, 2, 0],
     (3,"2024-04-02 00:00:00"):  [25  , 9, 12, 1, 1, 2, 0],
    (4,"2024-04-01 00:00:00"): [ 68 , 13, 48, 3, 1, 3, 0],
    (5,"2023-10-20 00:00:00"): [90, 14, 71, 3, 1, 1, 0],
       (6,"2023-10-18 00:00:00"): [61,	12, 44, 2, 1, 1, 1],
     (7,"2023-10-18 00:00:00"): [63,	7, 51, 2, 1, 2, 0],
    (8,"2023-10-13 00:00:00"): [94,	14, 71, 5, 1, 2, 1],
    (9,"2023-10-11 00:00:00"): [101,  48, 37, 13, 2, 0, 1]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-04-10 00:00:00,89.0,24.0,60.0,2.0,1.0,2.0,0.0
2,2024-04-02 00:00:00,36.0,9.0,21.0,1.0,3.0,2.0,0.0
3,2024-04-02 00:00:00,25.0,9.0,12.0,1.0,1.0,2.0,0.0
4,2024-04-01 00:00:00,68.0,13.0,48.0,3.0,1.0,3.0,0.0
5,2023-10-20 00:00:00,90.0,14.0,71.0,3.0,1.0,1.0,0.0
6,2023-10-18 00:00:00,61.0,12.0,44.0,2.0,1.0,1.0,1.0
7,2023-10-18 00:00:00,63.0,7.0,51.0,2.0,1.0,2.0,0.0
8,2023-10-13 00:00:00,94.0,14.0,71.0,5.0,1.0,2.0,1.0
9,2023-10-11 00:00:00,101.0,48.0,37.0,13.0,2.0,0.0,1.0

In [768]:

df3[(df3['작가명'] =='최다킬')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',

#    2024-08-12	51 ,15, 13, 0, 0, 1, 22
#	2024-08-05	53,	14, 23, 3, 8, 1, 4
#	2024-04-28 00:00:00	152 , 103, 19, 7, 2, 2, 19
# https://comic.naver.com/community/u/dakil?lastPage=SearchResult

author_name = '최다킬'
replace_values = {
      (0,"2024-08-12"):  [51 ,15, 13, 0, 0, 1, 22],
    (1,"2024-08-05"): [53,	14, 23, 3, 8, 1, 4],
    (2,"2024-04-28 00:00:00"):  [152 , 103, 19, 7, 2, 2, 19]
   
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-08-12,51.0,15.0,13.0,0.0,0.0,1.0,22.0
1,2024-08-05,53.0,14.0,23.0,3.0,8.0,1.0,4.0
2,2024-04-28 00:00:00,152.0,103.0,19.0,7.0,2.0,2.0,19.0

In [805]:
# df3[(df3['작가명'] == '지발')] = df3[(df3['작가명'] == '지발')].drop([1, 2], axis=0) 
# df3[(df3['작가명'] == '지발')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 ## 겹치는게 있는듯 (9.26)
#	2024-09-26	149,  54, 91, 2, 0, 1, 1 # 기타 
#	2024-09-26	250, 168, 69, 6, 2, 2, 3 # 일상 사진
#	2024-09-07	286  , 61, 209, 4, 3, 8, 1
#	2024-08-22	349 , 61, 267, 4, 2, 13, 2
#	2024-07-23	249 ,  30, 203, 2, 4, 8, 2
#	2024-07-18	304 , 101, 191, 2, 4, 5, 1
#	2024-07-15 00:00:00	198 , 52, 137, 2, 1, 5, 1
#	2024-07-05 00:00:00	239 , 47, 188, 1, 1, 2, 0
#	2024-07-04 00:00:00 278 , 48, 218, 2, 1, 8, 1
#	2024-07-04 00:00:00	234 , 54, 87, 2, 14, 7, 70

# https://comic.naver.com/community/u/zirarval?lastPage=SearchResult


author_name = '지발'
replace_values = {
      (0,"2024-09-26"): [149,  54, 91, 2, 0, 1, 1],
     (3,"2024-09-26"):  [250, 168, 69, 6, 2, 2, 3],
    (4,"2024-09-07"): [ 286  , 61, 209, 4, 3, 8, 1],
    (5,"2024-08-22"): [349 , 61, 267, 4, 2, 13, 2],
       (6,"2024-07-23"): [249 ,  30, 203, 2, 4, 8, 2],
     (7,"2024-07-18"): [304 , 101, 191, 2, 4, 5, 1],
    (8,"2024-07-15 00:00:00"): [198 , 52, 137, 2, 1, 5, 1],
    (9,"2024-07-05 00:00:00"): [239 , 47, 188, 1, 1, 2, 0],
      (10,"2024-07-04 00:00:00"): [278 , 48, 218, 2, 1, 8, 1],
    (11,"2024-07-04 00:00:00"): [234 , 54, 87, 2, 14, 7, 70]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-26,149.0,54.0,91.0,2.0,0.0,1.0,1.0
3,2024-09-26,250.0,168.0,69.0,6.0,2.0,2.0,3.0
4,2024-09-07,286.0,61.0,209.0,4.0,3.0,8.0,1.0
5,2024-08-22,349.0,61.0,267.0,4.0,2.0,13.0,2.0
6,2024-07-23,249.0,30.0,203.0,2.0,4.0,8.0,2.0
7,2024-07-18,304.0,101.0,191.0,2.0,4.0,5.0,1.0
8,2024-07-15 00:00:00,198.0,52.0,137.0,2.0,1.0,5.0,1.0
9,2024-07-05 00:00:00,239.0,47.0,188.0,1.0,1.0,2.0,0.0
10,2024-07-04 00:00:00,278.0,48.0,218.0,2.0,1.0,8.0,1.0
11,2024-07-04 00:00:00,234.0,54.0,87.0,2.0,14.0,7.0,70.0

In [806]:
df3[(df3['작가명'] ==  '모죠')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
  
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',

#    2024-09-17	3786 , 113, 1112, 16, 6, 30, 2509
#	2024-08-13	1170 , 107, 986, 10, 4, 59, 4
#	2024-04-22	1587 , 156, 1173, 39, 4, 36, 179
#	2024-02-14	2544 , 463, 1727, 42, 124, 184, 4
#	2024-02-08 00:00:00	7710 , 593, 6825, 124, 16, 140, 12

# https://comic.naver.com/community/u/_fbot9?lastPage=SearchResult


author_name ='모죠'
replace_values = {
      (0,"2024-09-17"): [3786 , 113, 1112, 16, 6, 30, 2509],
     (2,"2024-08-13"):  [1170 , 107, 986, 10, 4, 59, 4],
    (4,"2024-04-22"): [ 1587 , 156, 1173, 39, 4, 36, 179],
    (5,"2024-02-14"): [2544 , 463, 1727, 42, 124, 184, 4],
       (6,"2024-02-08 00:00:00"): [7710 , 593, 6825, 124, 16, 140, 12]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-17,3786.0,113.0,1112.0,16.0,6.0,30.0,2509.0
1,2024-08-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024-08-13,1170.0,107.0,986.0,10.0,4.0,59.0,4.0
3,2024-04-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024-04-22,1587.0,156.0,1173.0,39.0,4.0,36.0,179.0
5,2024-02-14,2544.0,463.0,1727.0,42.0,124.0,184.0,4.0
6,2024-02-08 00:00:00,7710.0,593.0,6825.0,124.0,16.0,140.0,12.0

In [788]:
df3[(df3['작가명'] ==  '스프링')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-03-31	306   67,203, 9, 8, 15, 4

# https://comic.naver.com/community/u/_1bxb2?lastPage=SearchResult


author_name =  '스프링'
replace_values = {
      (1,"2024-03-31"): [306 , 67,203, 9, 8, 15, 4] 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-06-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-03-31,306.0,67.0,203.0,9.0,8.0,15.0,4.0

In [789]:
df3[(df3['작가명'] =='구아진')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#    2024-09-26	247 , 125 , 87, 7, 0, 27, 1
#	2024-09-07	236 , 131, 52, 35, 8, 10, 0
#	2024-08-28	277 , 126, 114, 4, 6, 25, 2
#	2024-06-06	120 , 49, 58, 1, 4, 7, 1
#	2024-02-29	107,	52, 43, 2, 4, 6, 0
#	2024-02-09 00:00:00	176, 55, 101, 4, 2, 13, 1

# https://comic.naver.com/community/u/999ajin?lastPage=SearchResult


author_name ='구아진'
replace_values = {
      (0,"2024-09-26"): [247 , 125 , 87, 7, 0, 27, 1],
      (1,"2024-09-07"):  [236 , 131, 52, 35, 8, 10, 0],
     (2,"2024-08-28"):  [277 , 126, 114, 4, 6, 25, 2],
    (5,"2024-06-06"): [120 , 49, 58, 1, 4, 7, 1],
       (8,"2024-02-29"): [ 107,	52, 43, 2, 4, 6, 0],
       (9,"2024-02-09 00:00:00"): [176, 55, 101, 4, 2, 13, 1]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-26,247.0,125.0,87.0,7.0,0.0,27.0,1.0
1,2024-09-07,236.0,131.0,52.0,35.0,8.0,10.0,0.0
2,2024-08-28,277.0,126.0,114.0,4.0,6.0,25.0,2.0
3,2024-08-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024-08-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2024-06-06,120.0,49.0,58.0,1.0,4.0,7.0,1.0
6,2024-04-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2024-03-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2024-02-29,107.0,52.0,43.0,2.0,4.0,6.0,0.0
9,2024-02-09 00:00:00,176.0,55.0,101.0,4.0,2.0,13.0,1.0

In [790]:
df3[(df3['작가명'] == '오성대')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',

#   2024-09-29	154 ,  54, 75, 15, 7, 1, 2
#	2024-09-16	101,   20, 72, 5, 1, 2, 1
#	2024-08-24	664  , 432, 179, 48, 2, 2, 1
#	2024-08-24	386 ,  240, 113, 26, 2, 4, 1
#	2024-05-10	104 , 38, 55, 6, 2, 3, 0
#	2024-04-21	159 ,  41, 100, 6, 6, 0, 6
#	2024-04-09	119 , 43, 55, 4, 11, 6, 0
#	2024-03-31 00:00:00	226 , 90, 120, 9, 4, 3, 0
#	2024-03-09 00:00:00	735 ,  432, 270, 8, 3, 20, 2

# https://comic.naver.com/community/u/cenioh?lastPage=SearchResult


author_name = '오성대'
replace_values = {
      (0,"2024-09-29"): [154 ,  54, 75, 15, 7, 1, 2],
      (1,"2024-09-16"):  [101,   20, 72, 5, 1, 2, 1],
     (2,"2024-08-24"):  [664  , 432, 179, 48, 2, 2, 1],
   (3,"2024-08-24"):  [386 ,  240, 113, 26, 2, 4, 1],
     (5,"2024-05-10"):  [104 , 38, 55, 6, 2, 3, 0],
    (6,"2024-04-21"):  [159 ,  41, 100, 6, 6, 0, 6],
    (7,"2024-04-09"): [119 , 43, 55, 4, 11, 6, 0],
       (8,"2024-03-31 00:00:00"): [ 	226 , 90, 120, 9, 4, 3, 0],
       (9,"2024-03-09 00:00:00"): [735 ,  432, 270, 8, 3, 20, 2]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-29,154.0,54.0,75.0,15.0,7.0,1.0,2.0
1,2024-09-16,101.0,20.0,72.0,5.0,1.0,2.0,1.0
2,2024-08-24,664.0,432.0,179.0,48.0,2.0,2.0,1.0
3,2024-08-24,386.0,240.0,113.0,26.0,2.0,4.0,1.0
4,2024-08-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2024-05-10,104.0,38.0,55.0,6.0,2.0,3.0,0.0
6,2024-04-21,159.0,41.0,100.0,6.0,6.0,0.0,6.0
7,2024-04-09,119.0,43.0,55.0,4.0,11.0,6.0,0.0
8,2024-03-31 00:00:00,226.0,90.0,120.0,9.0,4.0,3.0,0.0
9,2024-03-09 00:00:00,735.0,432.0,270.0,8.0,3.0,20.0,2.0

In [791]:
 
df3[(df3['작가명'] ==  '박씨')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
  
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-06-12	91   , 45, 37, 3, 2, 3, 1
#	2024-05-29	120 ,  70, 43, 2, 1, 4, 0
#	2024-05-14	139 ,  38, 66, 2, 4, 6, 23

# https://comic.naver.com/community/u/parkci?lastPage=SearchResult

author_name =  '박씨'
replace_values = {
      
      (1,"2024-06-12"):  [91   , 45, 37, 3, 2, 3, 1],
     (2,"2024-05-29"):  [120 ,  70, 43, 2, 1, 4, 0], 
     (3,"2024-05-14"): [139 ,  38, 66, 2, 4, 6, 23]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-07-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-06-12,91.0,45.0,37.0,3.0,2.0,3.0,1.0
2,2024-05-29,120.0,70.0,43.0,2.0,1.0,4.0,0.0
3,2024-05-14,139.0,38.0,66.0,2.0,4.0,6.0,23.0

In [792]:
df3[(df3['작가명'] == '이담')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#	2024-06-09	838 , 78, 686, 11, 8, 52, 3
#	2024-05-17	380 , 25, 326, 3, 3, 21, 2
#	2024-05-17	654 ,69, 544, 4, 6, 30, 1

# https://comic.naver.com/community/u/_dboz2?lastPage=SearchResult

author_name =  '이담'
replace_values = {
      
      (2,"2024-06-09"):  [838 , 78, 686, 11, 8, 52, 3],
     (4,"2024-05-17"):  [380 , 25, 326, 3, 3, 21, 2], 
     (5,"2024-05-17"): [654 ,69, 544, 4, 6, 30, 1]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-07-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-07-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024-06-09,838.0,78.0,686.0,11.0,8.0,52.0,3.0
3,2024-05-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024-05-17,380.0,25.0,326.0,3.0,3.0,21.0,2.0
5,2024-05-17,654.0,69.0,544.0,4.0,6.0,30.0,1.0
6,2024-02-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2023-10-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [793]:
df3[(df3['작가명'] == '히디')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
  
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#   2024-05-08	448 , 81, 342, 14, 5, 6, 0

# https://comic.naver.com/community/u/hidi?lastPage=SearchResult
author_name = '히디'
replace_values = {
      
      (8,"2024-05-08"):  [448 , 81, 342, 14, 5, 6, 0] 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-24,219.0,57.0,143.0,3.0,4.0,11.0,1.0
1,2024-09-20,444.0,103.0,303.0,9.0,2.0,25.0,2.0
2,2024-09-18,340.0,37.0,289.0,5.0,0.0,9.0,0.0
3,2024-09-13,416.0,32.0,121.0,9.0,23.0,7.0,224.0
4,2024-09-11,316.0,60.0,137.0,7.0,18.0,6.0,88.0
5,2024-06-12,591.0,40.0,535.0,4.0,0.0,12.0,0.0
6,2024-06-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2024-05-21,531.0,95.0,399.0,10.0,7.0,17.0,3.0
8,2024-05-08,448.0,81.0,342.0,14.0,5.0,6.0,0.0
9,2024-04-23,677.0,168.0,405.0,20.0,72.0,11.0,1.0
10,2024-04-10,607.0,160.0,426.0,12.0,4.0,4.0,1.0
11,2024-04-01,565.0,103.0,430.0,19.0,7.0,6.0,0.0
12,2024-03-26,624.0,193.0,243.0,18.0,140.0,15.0,15.0
13,2024-03-20,555.0,91.0,396.0,39.0,20.0,8.0,1.0
14,2024-03-20,847.0,122.0,677.0,14.0,8.0,25.0,1.0

In [794]:
df3[(df3['작가명'] =='정연')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
#    2024-10-08	746 , 534, 175, 3, 2, 31, 1
#	2024-07-08	752 , 187, 37, 15, 2, 14, 497
#	2024-04-17	494 , 363, 116, 2, 7, 3, 3
#	2024-03-15	1995 , 1428, 462, 14, 7, 63, 21
# https://comic.naver.com/community/u/_bbout?lastPage=SearchResult

 
author_name = '정연'
replace_values = {
      
      (0,"2024-10-08"):  [746 , 534, 175, 3, 2, 31, 1],
      (2,"2024-07-08"):  [752 , 187, 37, 15, 2, 14, 497],
    (3,"2024-04-17"):  [494 , 363, 116, 2, 7, 3, 3],
    (4,"2024-03-15"):  [1995 , 1428, 462, 14, 7, 63, 21]

}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-08,746.0,534.0,175.0,3.0,2.0,31.0,1.0
1,2024-07-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024-07-08,752.0,187.0,37.0,15.0,2.0,14.0,497.0
3,2024-04-17,494.0,363.0,116.0,2.0,7.0,3.0,3.0
4,2024-03-15,1995.0,1428.0,462.0,14.0,7.0,63.0,21.0
5,2024-02-22,1166.0,638.0,95.0,18.0,6.0,42.0,367.0
6,2024-01-16,176.0,128.0,28.0,1.0,1.0,4.0,14.0
7,2024-01-09 00:00:00,372.0,267.0,93.0,2.0,3.0,5.0,2.0
8,2023-12-19,344.0,239.0,84.0,1.0,3.0,16.0,1.0

In [796]:
df3[(df3['작가명'] == '박태준')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
# 2024-08-02 00:00:00   661 , 273, 299, 13, 5, 13, 8

author_name ='박태준'
replace_values = {
      
      (1,"2024-08-02 00:00:00"):  [661 , 273, 299, 13, 5, 13, 81]

}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-10-04 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-08-02 00:00:00,661.0,273.0,299.0,13.0,5.0,13.0,81.0
2,2024-07-24 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [800]:
df3[(df3['작가명'] == '제나')  & (df3.best_reaction.isnull())][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]
 
 
# 'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction', 'expect_reaction', 'sad_reaction',
 
# 	2024-09-10	149, 32, 108, 1, 0, 8, 0	 
#	2024-07-26	96, 15, 76, 2, 0, 3, 0 
#	2024-07-26	55, 13, 37, 0, 1, 4, 0
#	2024-07-25	112, 44, 60, 2, 0, 6, 0
#	2024-07-25	35, 4, 30, 0, 0, 1, 0
#	2024-07-25  34, 3, 30, 0, 0, 1, 0
#	2024-07-25	82, 19, 59, 0, 0, 3, 1
#	2024-06-27	250, 45, 186, 12, 0, 7, 0
#	2023-11-29	133, 76, 32, 11, 5, 4, 5

# https://comic.naver.com/community/u/zkstudio?lastPage=SearchResult

author_name = '제나'
replace_values = {
      (0,"2024-09-10"): [149, 32, 108, 1, 0, 8, 0	],
      (1,"2024-07-26"):  [96, 15, 76, 2, 0, 3, 0 ],
     (2,"2024-07-26"):  [55, 13, 37, 0, 1, 4, 0],
   (3,"2024-07-25"):  [112, 44, 60, 2, 0, 6, 0],
     (4,"2024-07-25"): [ 35, 4, 30, 0, 0, 1, 0],
     (5,"2024-07-25"):  [ 34, 3, 30, 0, 0, 1, 0],
    (6,"2024-07-25"):  [82, 19, 59, 0, 0, 3, 1],
    (7,"2024-06-27"): [250, 45, 186, 12, 0, 7, 0],
 
       (9,"2023-11-29"): [133, 76, 32, 11, 5, 4, 5]
 
}
# Null 값 대체
for (idx, date), values in replace_values.items():
    df3.loc[(df3.index == idx) & (df3["게시글 날짜"] == date)&(df3["작가명"] ==author_name) , 
            ["반응수", "best_reaction", "good_reaction", "warm_reaction", 
             "surp_reaction", "expect_reaction", "sad_reaction"]] = values

# 결과 출력
df3[(df3['작가명'] ==author_name)][['게시글 날짜',  '반응수','best_reaction','good_reaction', 'warm_reaction', 'surp_reaction',   'expect_reaction', 'sad_reaction']]

,게시글 날짜,반응수,best_reaction,good_reaction,warm_reaction,surp_reaction,expect_reaction,sad_reaction
0,2024-09-10,149.0,32.0,108.0,1.0,0.0,8.0,0.0
1,2024-07-26,96.0,15.0,76.0,2.0,0.0,3.0,0.0
2,2024-07-26,55.0,13.0,37.0,0.0,1.0,4.0,0.0
3,2024-07-25,112.0,44.0,60.0,2.0,0.0,6.0,0.0
4,2024-07-25,35.0,4.0,30.0,0.0,0.0,1.0,0.0
5,2024-07-25,34.0,3.0,30.0,0.0,0.0,1.0,0.0
6,2024-07-25,82.0,19.0,59.0,0.0,0.0,3.0,1.0
7,2024-06-27,250.0,45.0,186.0,12.0,0.0,7.0,0.0
8,2024-05-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2023-11-29,133.0,76.0,32.0,11.0,5.0,4.0,5.0

In [810]:
df3 = df3[df3['작가명'].notnull()]

In [811]:
df3.isnull().sum()

작가명                0
작가 관심수             0
게시글 날짜             0
게시글 내용             0
이미지 여부             0
댓글수                0
반응수                0
best_reaction      0
good_reaction      0
warm_reaction      0
surp_reaction      0
expect_reaction    0
sad_reaction       0
작가유형               0
장르                 0
만화명                0
성별                 0
데뷔년도               0
웹툰단계               0
월                  0
화                  0
수                  0
목                  0
금                  0
토                  0
일                  0
연재여부               0
이미지 내용             0
작가 관심수_변동          0
연재요일               0
dtype: int64

In [3]:
import pandas as pd
df3= pd.read_csv('네이버웹툰_데이터_최종.csv', index_col = 0)

In [12]:
df3.columns

Index(['작가명', '작가 관심수', '게시글 날짜', '게시글 내용', '이미지 여부', '댓글수', '반응수',
       'best_reaction', 'good_reaction', 'warm_reaction', 'surp_reaction',
       'expect_reaction', 'sad_reaction', '작가유형', '장르', '만화명', '성별', '데뷔년도',
       '웹툰단계', '월', '화', '수', '목', '금', '토', '일', '연재여부', '이미지 내용',
       '작가 관심수_변동', '연재요일'],
      dtype='object')

In [16]:
for author in df3['작가명'].unique():
    print( '==================', author, '==================')
    print(df3[df3['작가명']==author][['게시글 날짜','작가 관심수_변동']])

================== 임형 ==================
        게시글 날짜    작가 관심수_변동
0   2024-09-27  9309.000000
1   2024-09-16  8447.200000
2   2024-09-01  7585.400000
3   2024-08-26  6723.600000
4   2024-08-18  5861.800000
5   2024-08-16  5000.000000
6   2024-08-16  4789.473684
7   2024-08-15  4578.947368
8   2024-08-10  4368.421053
9   2024-08-07  4157.894737
10  2024-08-03  3947.368421
11  2024-07-23  3736.842105
12  2024-07-10  3526.315789
13  2024-07-06  3315.789474
14  2024-06-29  3105.263158
15  2024-06-18  2894.736842
16  2024-06-15  2684.210526
17  2024-06-13  2473.684211
18  2024-06-13  2263.157895
19  2024-06-11  2052.631579
20  2024-06-07  1842.105263
21  2024-06-01  1631.578947
22  2024-05-24  1421.052632
23  2024-05-24  1210.526316
24  2024-05-22  1000.000000
25  2024-05-21  1000.000000
26  2024-05-18  1000.000000
27  2024-05-17  1000.000000
28  2024-05-17  1000.000000
29  2024-05-17  1000.000000
================== 지페리 ==================
        게시글 날짜  작가 관심수_변동
0   2024-09-13    24068.0
1   2024-08-23    23254.4
2   2024-07-12    22440.8
3   2024-07-05    21627.2
4   2024-06-07    20813.6
5   2024-05-26    20000.0
6   2024-05-24    20000.0
7   2024-05-17    20000.0
8   2024-04-26    20000.0
9   2024-04-19    20000.0
10  2024-04-05    20000.0
11  2024-03-31    20000.0
12  2024-03-30    20000.0
13  2024-03-23    20000.0
14  2024-03-15    20000.0
15  2024-03-10    20000.0
16  2024-03-08    20000.0
17  2024-03-01    20000.0
18  2024-02-29    20000.0
19  2024-02-23    20000.0
20  2024-02-19    20000.0
21  2024-02-09    20000.0
22  2024-01-20    20000.0
23  2024-01-06    20000.0
24  2023-12-30    20000.0
25  2023-12-23    20000.0
26  2023-12-16    20000.0
27  2023-12-08    20000.0
28  2023-11-15    20000.0
29  2023-11-08    20000.0
30  2023-11-01    20000.0
31  2023-10-30    20000.0
32  2023-10-15    20000.0
33  2023-10-14    20000.0
34  2023-10-08    20000.0
35  2023-10-07    20000.0
36  2023-10-06    20000.0
37  2023-10-06    20000.0
38  2023-10-06    20000.0
39  2023-10-06    20000.0
40  2023-10-06    20000.0
41  2023-10-06    20000.0
42  2023-09-30    20000.0
================== 스튜디오MW ==================
        게시글 날짜    작가 관심수_변동
0   2024-10-05  5575.000000
1   2024-10-05  5431.250000
2   2024-10-04  5287.500000
3   2024-10-02  5143.750000
4   2024-09-30  5000.000000
5   2024-09-15  4428.571429
6   2024-09-14  3857.142857
7   2024-09-13  3285.714286
8   2024-09-12  2714.285714
9   2024-08-11  2142.857143
10  2024-08-10  1571.428571
11  2024-07-31  1000.000000
12  2024-07-28  1000.000000
13  2024-07-27  1000.000000
14  2024-06-01  1000.000000
15  2024-05-31  1000.000000
16  2024-04-07  1000.000000
17  2024-04-01  1000.000000
18  2024-03-21  1000.000000
19  2024-03-13  1000.000000
20  2024-03-02  1000.000000
21  2024-03-01  1000.000000
22  2024-02-28  1000.000000
23  2024-02-26  1000.000000
24  2024-02-08  1000.000000
25  2024-02-06  1000.000000
================== 수박양 ==================
       게시글 날짜  작가 관심수_변동
0  2024-10-08    20278.0
1  2024-08-09    20278.0
2  2024-06-21    20278.0
3  2024-05-09    20278.0
4  2024-04-01    20278.0
5  2024-02-16    20278.0
6  2024-01-06    20278.0
7  2023-12-29    20278.0
8  2023-10-05    20278.0
9  2023-09-16    20278.0
================== 승우 ==================
       게시글 날짜  작가 관심수_변동
0  2024-09-28    24130.0
1  2024-09-20    22065.0
2  2024-07-15    20000.0
3  2024-05-23    20000.0
4  2024-03-31    20000.0
5  2024-02-21    20000.0
6  2023-11-14    20000.0
7  2023-10-04    20000.0
================== 이동건 ==================
        게시글 날짜  작가 관심수_변동
0   2024-09-03    44330.0
1   2024-08-22    40000.0
2   2024-08-15    40000.0
3   2024-05-17    40000.0
4   2024-05-17    40000.0
5   2024-05-14    40000.0
6   2024-05-09    40000.0
7   2024-03-01    40000.0
8   2024-02-08    40000.0
9   2023-12-29    40000.0
10  2023-12-16    40000.0
11  2023-10-06    40000.0
12  2023-10-04    40000.0
13  2023-10-02    40000.0
14  2023-09-29    40000.0
15  2023-09-22    40000.0
16  2023-09-20    40000.0
17  2023-09-18    40000.0
18  2023-09-18    40000.0
19  2023-09-15    40000.0
20  2023-09-13    40000.0
21  2023-09-13    40000.0
================== 김대영 ==================
       게시글 날짜  작가 관심수_변동
0  2024-08-11      955.0
1  2024-08-03      955.0
2  2024-07-22      955.0
3  2023-10-23      955.0
================== 켄타 ==================
       게시글 날짜  작가 관심수_변동
0  2024-09-13     4724.0
1  2024-07-19     4724.0
2  2024-04-01     4724.0
3  2023-12-30     4724.0
4  2023-12-22     4724.0
5  2023-11-19     4724.0
6  2023-11-10     4724.0
================== 꼬모소이 ==================
       게시글 날짜    작가 관심수_변동
0  2024-09-12  4313.000000
1  2024-08-14  3208.666667
2  2024-07-10  2104.333333
3  2024-06-20  1000.000000
================== 이솔 ==================
       게시글 날짜    작가 관심수_변동
0  2024-09-20  6164.000000
1  2024-09-12  5582.000000
2  2024-09-07  5000.000000
3  2024-09-02  3666.666667
4  2024-08-20  2333.333333
5  2024-07-10  1000.000000
6  2024-07-09  1000.000000
7  2024-07-08  1000.000000
8  2024-07-08  1000.000000
================== 득7이 ==================
       게시글 날짜  작가 관심수_변동
0  2024-08-07     3253.0
1  2024-08-02     3253.0
2  2024-07-25     3253.0
3  2024-06-11     3253.0
4  2024-06-11     3253.0
================== 황양 ==================
        게시글 날짜    작가 관심수_변동
0   2024-10-04  3082.000000
1   2024-09-26  2892.727273
2   2024-09-22  2703.454545
3   2024-08-04  2514.181818
4   2024-07-21  2324.909091
5   2024-07-15  2135.636364
6   2024-07-08  1946.363636
7   2024-06-27  1757.090909
8   2024-05-31  1567.818182
9   2024-05-27  1378.545455
10  2024-05-13  1189.272727
11  2024-05-03  1000.000000
12  2024-04-18  1000.000000
13  2024-04-01  1000.000000
14  2024-03-17  1000.000000
15  2024-03-05  1000.000000
================== 이대한 ==================
       게시글 날짜  작가 관심수_변동
0  2024-09-16     4602.0
1  2024-08-11     3701.5
2  2024-08-04     2801.0
3  2024-05-20     1900.5
4  2024-04-26     1000.0
5  2024-03-30     1000.0
================== 하일권 ==================
        게시글 날짜     작가 관심수_변동
0   2024-10-06  11805.000000
1   2024-09-29  11504.166667
2   2024-09-21  11203.333333
3   2024-09-15  10902.500000
4   2024-09-08  10601.666667
5   2024-08-24  10300.833333
6   2024-08-18  10000.000000
7   2024-08-17  10000.000000
8   2024-07-28  10000.000000
9   2024-07-14  10000.000000
10  2024-06-30  10000.000000
11  2024-06-23  10000.000000
12  2024-06-09  10000.000000
13  2024-05-25  10000.000000
14  2024-05-18  10000.000000
15  2024-05-12  10000.000000
16  2024-05-05  10000.000000
17  2024-04-27  10000.000000
18  2024-04-20  10000.000000
19  2024-04-13  10000.000000
20  2024-04-06  10000.000000
21  2024-03-30  10000.000000
22  2024-03-23  10000.000000
23  2024-03-16  10000.000000
24  2024-03-09  10000.000000
25  2024-03-03  10000.000000
26  2024-02-24  10000.000000
27  2024-02-17  10000.000000
28  2024-01-05  10000.000000
29  2023-09-18  10000.000000
================== 명랑 ==================
       게시글 날짜  작가 관심수_변동
0  2024-10-03     6486.0
1  2024-08-09     5000.0
2  2024-06-26     5000.0
3  2024-06-13     5000.0
4  2024-05-26     5000.0
5  2024-05-26     5000.0
6  2024-05-08     5000.0
7  2024-05-01     5000.0
8  2024-04-08     5000.0
9  2024-04-06     5000.0
================== 강견 ==================
       게시글 날짜  작가 관심수_변동
0  2024-10-05     3987.0
1  2024-09-17     3987.0
2  2024-09-14     3987.0
3  2024-09-01     3987.0
4  2024-08-31     3987.0
5  2024-08-18     3987.0
6  2024-08-17     3987.0
7  2024-08-04     3987.0
8  2024-08-03     3987.0
9  2024-07-19     3987.0
================== 시바견 ==================
                 게시글 날짜  작가 관심수_변동
0   2024-09-29 00:00:00     3958.0
1   2024-09-28 00:00:00     3958.0
2   2024-07-07 00:00:00     3958.0
3   2024-07-07 00:00:00     3958.0
4   2024-07-01 00:00:00     3958.0
5   2024-06-16 00:00:00     3958.0
6   2024-06-16 00:00:00     3958.0
7   2024-06-02 00:00:00     3958.0
8   2024-05-27 00:00:00     3958.0
9   2024-05-22 00:00:00     3958.0
10  2024-05-20 00:00:00     3958.0
11  2024-05-05 00:00:00     3958.0
12  2024-05-05 00:00:00     3958.0
13  2024-04-28 00:00:00     3958.0
14  2024-04-22 00:00:00     3958.0
15  2024-04-16 00:00:00     3958.0
16  2024-04-16 00:00:00     3958.0
17  2024-04-01 00:00:00     3958.0
18  2024-04-01 00:00:00     3958.0
19  2024-03-27 00:00:00     3958.0
20  2024-03-20 00:00:00     3958.0
21  2024-03-19 00:00:00     3958.0
22  2024-03-18 00:00:00     3958.0
23  2024-03-10 00:00:00     3958.0
24  2024-03-10 00:00:00     3958.0
25  2024-03-10 00:00:00     3958.0
26  2024-02-26 00:00:00     3958.0
27  2024-02-26 00:00:00     3958.0
28  2024-02-25 00:00:00     3958.0
29  2024-02-25 00:00:00     3958.0
30  2024-02-25 00:00:00     3958.0
31  2024-02-12 00:00:00     3958.0
32  2024-02-11 00:00:00     3958.0
33  2024-02-11 00:00:00     3958.0
34  2024-02-03 00:00:00     3958.0
35  2024-01-30 00:00:00     3958.0
36  2024-01-10 00:00:00     3958.0
37  2023-12-21 00:00:00     3958.0
38  2023-12-21 00:00:00     3958.0
39  2023-12-20 00:00:00     3958.0
================== 운 ==================
       게시글 날짜  작가 관심수_변동
0  2024-09-18     3334.0
1  2024-09-18     3334.0
2  2024-08-31     3334.0
3  2024-08-18     3334.0
4  2024-06-24     3334.0
5  2024-04-13     3334.0
6  2024-02-15     3334.0
7  2024-01-11     3334.0
8  2023-12-28     3334.0
9  2023-12-02     3334.0
================== 배민기 ==================
       게시글 날짜  작가 관심수_변동
0  2024-10-02     2260.0
1  2024-09-27     2260.0
2  2024-09-19     2260.0
3  2024-06-24     2260.0
4  2024-01-30     2260.0
5  2024-01-11     2260.0
6  2023-11-09     2260.0
7  2023-11-08     2260.0
8  2023-09-28     2260.0
9  2023-09-21     2260.0
================== 부겸 ==================
       게시글 날짜  작가 관심수_변동
0  2024-08-12     1890.0
================== JP ==================
       게시글 날짜  작가 관심수_변동
0  2024-10-08     9285.0
1  2024-10-07     9285.0
2  2024-09-29     9285.0
3  2024-09-29     9285.0
4  2024-09-28     9285.0
5  2024-09-27     9285.0
6  2024-09-26     9285.0
7  2024-09-25     9285.0
8  2024-09-25     9285.0
9  2024-09-24     9285.0
================== 박진환 ==================
       게시글 날짜  작가 관심수_변동
0  2024-10-08    10153.0
1  2024-10-08    10000.0
2  2024-09-16     7500.0
3  2024-08-04     5000.0
4  2023-11-13     5000.0
5  2023-09-26     5000.0
================== 유누니 ==================
       게시글 날짜  작가 관심수_변동
0  2024-04-07     6655.0
1  2023-10-08     6655.0
2  2023-09-28     6655.0
3  2023-09-23     6655.0
================== 태완 ==================
       게시글 날짜  작가 관심수_변동
0  2024-08-06     5722.0
================== 제나 ==================
       게시글 날짜  작가 관심수_변동
0  2024-09-10  13419.000
1  2024-07-26  12991.625
2  2024-07-26  12564.250
3  2024-07-25  12136.875
4  2024-07-25  11709.500
5  2024-07-25  11282.125
6  2024-07-25  10854.750
7  2024-06-27  10427.375
8  2024-05-28  10000.000
9  2023-11-29  10000.000
================== 펀치킥 ==================
       게시글 날짜  작가 관심수_변동
0  2024-09-28     5129.0
1  2024-09-25     5000.0
2  2024-09-10     5000.0
3  2024-05-04     5000.0
4  2024-05-01     5000.0
5  2024-02-28     5000.0
6  2024-02-07     5000.0
7  2024-01-31     5000.0
8  2024-01-21     5000.0
9  2024-01-19     5000.0
================== 한가람 ==================
       게시글 날짜  작가 관심수_변동
0  2024-04-09    14302.0
================== 남자의 이야기 ==================
        게시글 날짜  작가 관심수_변동
0   2024-09-19     7334.0
1   2024-09-05     7334.0
2   2024-08-03     7334.0
3   2024-07-16     7334.0
4   2024-03-29     7334.0
5   2024-03-29     7334.0
6   2024-02-26     7334.0
7   2024-01-19     7334.0
8   2024-01-17     7334.0
9   2024-01-06     7334.0
10  2024-01-04     7334.0
11  2023-12-29     7334.0
12  2023-12-28     7334.0
13  2023-12-22     7334.0
14  2023-12-20     7334.0
15  2023-12-16     7334.0
16  2023-12-06     7334.0
17  2023-11-29     7334.0
18  2023-11-17     7334.0
19  2023-11-16     7334.0
20  2023-11-11     7334.0
21  2023-11-08     7334.0
22  2023-10-27     7334.0
23  2023-10-25     7334.0
24  2023-10-20     7334.0
25  2023-10-18     7334.0
26  2023-10-13     7334.0
27  2023-10-11     7334.0
28  2023-09-27     7334.0
29  2023-09-22     7334.0
30  2023-09-20     7334.0
================== 박만사 ==================
        게시글 날짜  작가 관심수_변동
0   2024-09-27    51514.0
1   2024-09-15    47676.0
2   2024-09-10    43838.0
3   2024-07-31    40000.0
4   2024-07-19    40000.0
5   2024-05-02    40000.0
6   2024-04-03    40000.0
7   2024-04-01    40000.0
8   2024-03-31    40000.0
9   2024-03-31    40000.0
10  2024-03-30    40000.0
11  2024-03-29    40000.0
12  2024-03-28    40000.0
13  2024-03-27    40000.0
14  2024-03-27    40000.0
15  2024-03-27    40000.0
16  2024-03-27    40000.0
17  2024-03-26    40000.0
18  2024-03-24    40000.0
19  2024-03-23    40000.0
20  2024-03-22    40000.0
21  2024-03-21    40000.0
22  2024-03-20    40000.0
23  2024-03-19    40000.0
24  2024-03-19    40000.0
25  2024-03-18    40000.0
26  2024-03-17    40000.0
27  2024-03-16    40000.0
28  2024-03-15    40000.0
29  2024-03-14    40000.0
30  2024-03-13    40000.0
31  2024-03-12    40000.0
32  2024-03-11    40000.0
33  2024-03-09    40000.0
34  2024-03-09    40000.0
35  2024-03-09    40000.0
36  2024-03-09    40000.0
37  2024-03-08    40000.0
38  2024-03-08    40000.0
39  2024-03-08    40000.0
40  2024-03-08    40000.0
41  2024-03-06    40000.0
42  2024-03-06    40000.0
43  2024-03-05    40000.0
44  2024-03-04    40000.0
45  2024-03-03    40000.0
46  2024-03-02    40000.0
47  2024-03-01    40000.0
48  2024-02-29    40000.0
49  2024-02-28    40000.0
50  2024-02-27    40000.0
51  2024-02-25    40000.0
52  2024-02-25    40000.0
53  2024-02-25    40000.0
54  2024-02-25    40000.0
55  2024-02-24    40000.0
56  2024-02-23    40000.0
57  2024-02-22    40000.0
================== 정종택 ==================
       게시글 날짜  작가 관심수_변동
0  2024-07-08     6413.0
1  2024-07-05     5706.5
2  2024-06-20     5000.0
3  2024-05-07     5000.0
4  2024-04-02     5000.0
5  2023-12-21     5000.0
6  2023-11-15     5000.0
7  2023-11-14     5000.0
8  2023-11-14     5000.0
9  2023-09-27     5000.0
================== 병장 ==================
        게시글 날짜  작가 관심수_변동
0   2024-08-05     6663.0
1   2024-08-04     5000.0
2   2024-07-13     5000.0
3   2024-05-07     5000.0
4   2024-05-05     5000.0
5   2024-02-29     5000.0
6   2023-12-26     5000.0
7   2023-11-29     5000.0
8   2023-11-23     5000.0
9   2023-11-20     5000.0
10  2023-11-14     5000.0
11  2023-10-31     5000.0
12  2023-10-26     5000.0
13  2023-10-24     5000.0
14  2023-10-19     5000.0
15  2023-10-10     5000.0
16  2023-10-09     5000.0
17  2023-10-03     5000.0
18  2023-10-03     5000.0
19  2023-09-30     5000.0
20  2023-09-29     5000.0
21  2023-09-26     5000.0
22  2023-09-25     5000.0
23  2023-09-25     5000.0
24  2023-09-25     5000.0
25  2023-09-25     5000.0
================== 임리나 ==================
       게시글 날짜  작가 관심수_변동
0  2024-10-05    20399.0
1  2024-09-17    20399.0
2  2024-09-14    20399.0
3  2024-08-17    20399.0
4  2024-02-20    20399.0
5  2023-10-28    20399.0
6  2023-09-13    20399.0
================== 이난 ==================
       게시글 날짜  작가 관심수_변동
0  2024-09-29     3658.0
1  2024-09-22     3658.0
2  2024-08-30     3658.0
3  2024-08-29     3658.0
4  2024-08-21     3658.0
5  2024-07-19     3658.0
6  2024-06-27     3658.0
7  2024-06-08     3658.0
8  2024-06-07     3658.0
9  2024-05-29     3658.0
================== 채키 ==================
                게시글 날짜  작가 관심수_변동
0  2024-10-03 00:00:00      401.0
1           2024-09-15      401.0
2           2024-08-28      401.0
3           2024-07-10      401.0
4           2024-06-26      401.0
5           2024-06-19      401.0
6           2024-05-17      401.0
7           2024-05-08      401.0
8           2024-05-08      401.0
================== 윤성 ==================
       게시글 날짜  작가 관심수_변동
0  2024-05-25     1247.0
1  2024-01-25     1247.0
2  2023-10-08     1247.0
3  2023-10-02     1247.0
================== 라군 ==================
       게시글 날짜  작가 관심수_변동
0  2024-05-20     1388.0
1  2024-01-26     1388.0
2  2023-12-28     1388.0
3  2023-12-03     1388.0
4  2023-09-29     1388.0
================== 돌석 ==================
       게시글 날짜    작가 관심수_변동
0  2024-10-09  2286.000000
1  2024-10-01  2102.285714
2  2024-09-17  1918.571429
3  2024-09-04  1734.857143
4  2024-09-03  1551.142857
5  2024-08-20  1367.428571
6  2024-08-13  1183.714286
7  2024-08-10  1000.000000
8  2024-08-06  1000.000000
9  2024-07-30  1000.000000
================== 이은재 ==================
                게시글 날짜  작가 관심수_변동
0  2024-09-21 00:00:00    11268.0
1  2024-09-21 00:00:00    10951.0
2  2024-09-21 00:00:00    10634.0
3           2024-09-05    10317.0
4           2024-09-02    10000.0
5           2024-08-01    10000.0
6           2024-07-30    10000.0
7           2024-07-27    10000.0
8           2024-07-18    10000.0
9           2024-07-17    10000.0
================== 조용석 ==================
       게시글 날짜  작가 관심수_변동
0  2024-06-26    15951.0
1  2024-01-05    15951.0
2  2023-11-09    15951.0
3  2023-10-16    15951.0
4  2023-10-06    15951.0
5  2023-10-06    15951.0
6  2023-09-17    15951.0
7  2023-09-17    15951.0
8  2023-09-14    15951.0
================== HO9 ==================
       게시글 날짜  작가 관심수_변동
0  2024-08-06     6830.0
================== 혀노 ==================
       게시글 날짜  작가 관심수_변동
0  2024-09-24    40031.0
1  2024-09-17    38024.8
2  2024-09-11    36018.6
3  2024-09-06    34012.4
4  2024-08-10    32006.2
5  2024-07-28    30000.0
6  2024-05-25    30000.0
7  2024-05-13    30000.0
8  2024-05-07    30000.0
================== 모랑지 ==================
                게시글 날짜  작가 관심수_변동
0  2024-09-25 00:00:00    20693.0
1  2024-09-19 00:00:00    20000.0
2  2024-04-01 00:00:00    20000.0
3  2024-01-07 00:00:00    20000.0
4  2023-12-21 00:00:00    20000.0
5  2023-09-27 00:00:00    20000.0
================== 박태준 ==================
                게시글 날짜  작가 관심수_변동
0  2024-10-04 00:00:00    61059.0
1  2024-08-02 00:00:00    61059.0
2  2024-07-24 00:00:00    61059.0
================== 포스스튜디오 ==================
                게시글 날짜  작가 관심수_변동
0  2024-10-01 00:00:00     5967.0
1  2024-04-10 00:00:00     5967.0
2  2024-04-02 00:00:00     5967.0
3  2024-04-02 00:00:00     5967.0
4  2024-04-01 00:00:00     5967.0
5  2023-10-20 00:00:00     5967.0
6  2023-10-18 00:00:00     5967.0
7  2023-10-18 00:00:00     5967.0
8  2023-10-13 00:00:00     5967.0
9  2023-10-11 00:00:00     5967.0
================== 허새보 ==================
                게시글 날짜  작가 관심수_변동
0  2024-10-10 00:00:00     3896.0
1  2024-10-05 00:00:00     3896.0
2  2024-10-04 00:00:00     3896.0
3  2024-09-14 00:00:00     3896.0
4  2024-09-10 00:00:00     3896.0
5  2024-09-02 00:00:00     3896.0
6  2024-08-14 00:00:00     3896.0
7  2024-08-06 00:00:00     3896.0
8  2024-07-28 00:00:00     3896.0
9  2024-07-24 00:00:00     3896.0
================== 손하기 ==================
                게시글 날짜  작가 관심수_변동
0  2024-08-25 00:00:00    11576.0
1  2024-07-18 00:00:00     9384.0
2  2024-05-16 00:00:00     7192.0
3  2024-05-16 00:00:00     5000.0
4  2024-05-01 00:00:00     5000.0
5  2023-11-30 00:00:00     5000.0
================== 범배 ==================
                게시글 날짜  작가 관심수_변동
0  2024-10-12 00:00:00     5036.0
1  2024-10-09 00:00:00     5036.0
2  2024-09-25 00:00:00     5036.0
3  2024-08-21 00:00:00     5036.0
4  2024-05-29 00:00:00     5036.0
5  2024-05-01 00:00:00     5036.0
6  2024-04-21 00:00:00     5036.0
7  2024-04-10 00:00:00     5036.0
8  2024-04-04 00:00:00     5036.0
9  2024-03-29 00:00:00     5036.0
================== 최다킬 ==================
                게시글 날짜  작가 관심수_변동
0           2024-08-12     2958.0
1           2024-08-05     2958.0
2  2024-04-28 00:00:00     2958.0
================== 지발 ==================
                 게시글 날짜  작가 관심수_변동
0            2024-09-26    16324.0
3            2024-09-26    16324.0
4            2024-09-07    16324.0
5            2024-08-22    16324.0
6            2024-07-23    16324.0
7            2024-07-18    16324.0
8   2024-07-15 00:00:00    16324.0
9   2024-07-05 00:00:00    16324.0

In [812]:
# df3.to_csv('네이버웹툰_데이터_최종.csv')
# df3.to_csv()

In [17]:
df3 = pd.read_csv('네이버웹툰_데이터_최종.csv', index_col = 0) 

# 시간 부분을 제거하고 날짜만 남기기
df3['게시글 날짜']=df3['게시글 날짜'].str.replace(r' 00:00:00$', '', regex=True)
 
df3['게시글 날짜']= pd.to_datetime(df3['게시글 날짜'])
df3.to_csv('네이버웹툰_데이터_최종.csv')